const fs = require('fs');

const BASE = 'C:/Projects/Learning';

const enhancements = {

'1-3': {
  addMinutes: 40,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — AI Tool Landscape Map (Quick Drill)', content: 'This 8-minute drill builds your mental map of the AI tool landscape — so you can instantly answer "which AI tool should I use for this?"\n\n**Step 1 — Open a blank document** (Google Docs, Word, or Notion) and draw four columns: "Conversation AI", "Search/Research AI", "Creative AI", "Productivity AI".\n\n**Step 2 — Without looking anything up**, list every AI tool you have heard of under the right column. Aim for 10+ tools total.\n\n**Step 3 — Open Claude.ai** and paste your list. Ask: *"Review my AI tool landscape map. What important tools or categories have I missed? What have I misclassified? Be specific."*\n\n**Step 4 — Update your map** based on Claude\'s feedback. Add the tools you missed.\n\n**Step 5 — For each column**, identify which single tool you would use first if someone gave you a task in that category. Write the name next to the column header.\n\n**Step 6 — Save your map.** This is your personal AI tools reference — update it as you discover new tools throughout this course.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build an AI Tool Recommendation System', content: 'You will build a reusable prompt that helps you (or anyone) choose the right AI tool for a given task. This is a genuinely useful tool — you will reference it every time you start a new AI-assisted task.\n\n**Step 1 — Open Claude.ai** and start a new conversation.\n\n**Step 2 — Describe 3 real tasks** from your work or life that you could imagine using AI for. Be specific: not "writing" but "writing weekly status reports for my manager" or not "research" but "researching competitor pricing".\n\n**Step 3 — Ask Claude:** *"For each of these 3 tasks, recommend the best AI tool available in 2026 and explain: (1) why this tool is best for this specific task, (2) one alternative tool and when to use it instead, (3) one thing to watch out for with this tool. Be specific and practical."*\n\n**Step 4 — Review Claude\'s recommendations.** Do they match what you expected? What surprised you?\n\n**Step 5 — Mandatory AI review:** Paste Claude\'s recommendations back with this message: *"Review your own tool recommendations above. Play devil\'s advocate — find 3 specific cases where your recommendation might be wrong or where a different tool would actually be better."*\n\n**Step 6 — Build your personal tool selection guide:** Based on the full exchange, write a short (1 page) guide: "Which AI tool I use for which type of task." Keep this — it will save you time every week.\n\n**Step 7 — Test your guide:** Pick any task from your work today and use your guide to select a tool. Does the guide\'s recommendation make sense?' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Head-to-Head Tool Comparison', content: 'The best way to understand what makes each AI tool different is to ask them the same thing and compare. This workshop reveals the real differences — not the marketing.\n\n**Step 1 — Choose a real task** from your work that you need to do anyway this week. Something where the quality of the output matters.\n\n**Step 2 — Craft a specific prompt** for the task. Write it clearly with context.\n\n**Step 3 — Run the exact same prompt** in at least two of these: Claude.ai, ChatGPT, Gemini. Keep tabs open side-by-side.\n\n**Step 4 — Compare the outputs** across these dimensions:\n- Length and detail level\n- Tone and style\n- Accuracy of specific facts (if applicable)\n- Usefulness for your actual task\n- What each one got wrong or missed\n\n**Step 5 — Ask Claude** to compare the approaches: *"I ran the same prompt in multiple AI tools. Here are the outputs: [paste them]. What are the meaningful differences in their approaches? Which is most useful for [your task] and why?"*\n\n**Step 6 — Write a one-paragraph verdict:** For this type of task, which tool would you use in the future and why? Add this verdict to your tool guide from Workshop B.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Your Personal AI Tools Shortlist', content: 'Most people end up using 2-3 AI tools regularly. This workshop helps you decide which ones those should be for you specifically.\n\n**Step 1 — Think about your work and life** over the last month. What were the most time-consuming or tedious tasks? List 5-8 of them.\n\n**Step 2 — For each task**, write: (a) which AI tool you have tried or would try, (b) whether you have actually used AI for this task.\n\n**Step 3 — Open Claude.ai** and paste your task list. Ask: *"I want to build a minimal AI tools setup — ideally 2-3 tools that cover my main use cases. Based on this task list, which 2-3 AI tools would you recommend I start with? Explain why these cover my specific needs. What would I miss by not adding a fourth tool?"*\n\n**Step 4 — Decide your shortlist.** Pick 2-3 tools you will actually use starting today.\n\n**Step 5 — Create accounts** (if you haven\'t already) for your chosen tools. Bookmark them or add them to your browser toolbar.\n\n**Step 6 — Commit to a 2-week experiment:** For the next 2 weeks, use only your shortlisted tools (no adding new ones). This forces you to learn them well before expanding.' },

    { type: 'quiz', question: 'A colleague asks which AI tool to use for drafting a business proposal. Which answer is most helpful?', options: ['Use ChatGPT — it\'s the most popular', 'It depends: Claude is strong for long documents and nuanced writing; ChatGPT is good if you need web search integrated', 'Use whichever you have a subscription to', 'AI tools are roughly equivalent for writing tasks'], correct: 1, explanation: 'Different AI tools have genuine strengths for different tasks. Claude excels at long, nuanced documents and careful reasoning. ChatGPT has integrated web search and image generation. Recommending the right tool requires knowing the task, not just what\'s popular or available.' },

    { type: 'quiz', question: 'Which AI tool category is specifically designed for research with cited sources?', options: ['Conversation AI (Claude, ChatGPT)', 'Creative AI (Midjourney, DALL-E)', 'Search/Research AI (Perplexity, Consensus)', 'Productivity AI (Copilot for M365)'], correct: 2, explanation: 'Perplexity, Consensus, Scite and similar tools are specifically built for research with citations — they retrieve current web sources and link every claim to its source. General conversation AI (Claude, ChatGPT) can discuss topics but doesn\'t automatically cite sources.' }
  ]
},

'1-4': {
  addMinutes: 40,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Hallucination Hunt (Quick Drill)', content: 'This 8-minute drill trains your eye to spot AI hallucinations. You will catch an AI making things up — deliberately.\n\n**Step 1 — Pick a subject you know well** — your job, your industry, your city, a hobby, a historical period you studied. You need genuine expertise to catch errors.\n\n**Step 2 — Ask Claude or ChatGPT** 3-5 specific factual questions about this subject. Include at least one question about:\n- A specific person (someone niche, not a celebrity)\n- A specific date or statistic\n- A procedure or process specific to your field\n\n**Step 3 — Read each answer carefully.** Check every specific claim against what you know or can quickly verify.\n\n**Step 4 — For every error you find**, make a note of: what AI said, what is actually true, and how confident the AI sounded.\n\n**Step 5 — If you found no errors**, make the questions harder. Ask about very recent events, niche technical details, or specific people in your industry.\n\n**Step 6 — Reflect:** How confident-sounding were the wrong answers? This is the core danger — hallucinations rarely sound uncertain.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Hallucination Verification Protocol', content: 'You will create a personal checklist for verifying AI output in your specific field or work context. This is one of the most practically valuable things you can build in this course.\n\n**Step 1 — Identify your high-stakes AI use cases:** Think about 3-5 situations where you would use AI and where a factual error would cause a real problem (embarrassment, bad decision, legal risk, financial loss).\n\n**Step 2 — For each use case**, write: what type of claim is AI most likely to get wrong? (Statistics? Dates? Names? Legal rules? Technical procedures?)\n\n**Step 3 — Open Claude.ai** and paste your use cases. Ask: *"For each of these AI use cases, what types of hallucinations are most common and most dangerous? What specific verification steps should I take before using AI output in each situation?"*\n\n**Step 4 — Build your verification checklist.** Format it as a simple table: Use case | Types of error to check | How to verify | Time required.\n\n**Step 5 — Mandatory AI review:** Paste your checklist back to Claude and ask: *"Don\'t tell me this looks good. Find 3 gaps in this verification protocol — situations where following this checklist would still let an error through."*\n\n**Step 6 — Update your checklist** based on the gaps Claude identified.\n\n**Step 7 — Save and use it.** Next time you use AI for anything in your high-stakes list, run through your checklist before acting on the output.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Stress Test an AI Tool', content: 'This workshop deliberately probes AI limitations — you are trying to make it fail, in controlled conditions.\n\n**Step 1 — Open Claude.ai or ChatGPT** in a fresh conversation.\n\n**Step 2 — Run these hallucination-prone prompts** (one at a time):\n- Ask for a bibliography of academic papers on a niche topic in your field\n- Ask for specific statistics with sources from the last 6 months\n- Ask about a local regulation or law specific to your country/region\n- Ask about a recent event from the last month\n- Ask it to quote a specific sentence from a document you know\n\n**Step 3 — For each response**, note: Did it give specific citations? Did it express uncertainty? Did it clearly state when it didn\'t know?\n\n**Step 4 — Compare behavior:** Ask the same prompts in a second AI tool. Does one handle uncertainty better than the other?\n\n**Step 5 — Discuss your findings with Claude:** *"I just asked you [these questions] and noticed [what you observed]. What does this reveal about when I should and shouldn\'t trust AI factual claims? Give me a practical rule of thumb."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Real-World Fact-Check Sprint', content: 'Apply hallucination awareness to a real task you need to do anyway.\n\n**Step 1 — Identify a real task** where you need factual information: writing a report, preparing for a meeting, researching a topic, making a decision.\n\n**Step 2 — Use AI to help with the task** — but flag every specific fact, statistic, name, date, or citation that AI provides.\n\n**Step 3 — Verify the top 5 most important facts** using a non-AI source (official website, published paper, news source, your own knowledge).\n\n**Step 4 — Record your findings:** How many of the 5 facts checked out? How many were wrong or unverifiable?\n\n**Step 5 — Adjust your workflow:** Based on your verification results, decide: for this type of task, do you need to verify (a) everything, (b) claims you\'ll share publicly, (c) statistics only, or (d) nothing because errors don\'t matter here?\n\n**Step 6 — Save this experience** as a note to yourself about AI reliability in your specific work context.' },

    { type: 'quiz', question: 'You ask an AI for three recent statistics about your industry. The AI provides three numbers with specific decimal places and confident language. What should you do?', options: ['Use the statistics — specific numbers indicate the AI retrieved real data', 'Verify each statistic against its original source before using it in any document or presentation', 'Ask the AI to double-check its own figures', 'Use the statistics only if the AI also names a source'], correct: 1, explanation: 'Specific, confident-sounding numbers are one of the most common forms of hallucination. AI models generate plausible-sounding statistics based on patterns in training data — they can produce precise-looking numbers that are fabricated. Always verify statistics against the original source before using them, especially in professional contexts.' },

    { type: 'quiz', question: 'Which of these AI outputs requires the most verification before acting on it?', options: ['A summary of a document you pasted into the conversation', 'A list of strategies for improving team communication', 'The name and contact details of a specific government official', 'An explanation of how compound interest works'], correct: 2, explanation: 'Specific factual claims about named individuals (names, roles, contact details, affiliations) are high-hallucination-risk. AI may confuse people, invent details, or report outdated information. General knowledge (how compound interest works) and reasoning tasks (communication strategies) are lower risk. Document summaries are lowest risk as the source is right there.' }
  ]
},

'1-5': {
  addMinutes: 40,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Privacy Audit of Your Own Prompts (Quick Drill)', content: 'This 8-minute exercise reviews prompts you have already written for hidden privacy risks.\n\n**Step 1 — Look through your recent AI conversations** (Claude, ChatGPT, or whichever tool you use). Find 3-5 prompts you have sent.\n\n**Step 2 — For each prompt**, check whether it contains:\n- A real person\'s name and a sensitive detail about them\n- Your own location, address, or personal identifier\n- Confidential business information (client names, financial figures, internal processes)\n- Medical, legal, or financial details that should stay private\n- Login credentials, API keys, or system details\n\n**Step 3 — Rate each prompt:** Green (safe), Yellow (borderline — should I have shared this?), Red (I shouldn\'t have shared this).\n\n**Step 4 — Ask Claude:** *"I will describe what I shared in an AI prompt. Tell me what the privacy risk is and whether I should be concerned: [describe your yellow or red prompts in general terms — don\'t paste the actual private content again]."*\n\n**Step 5 — Note any patterns:** Are there types of information you routinely share with AI that you shouldn\'t?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build Your Personal AI Privacy Policy', content: 'You will create a short, practical document that defines what you will and won\'t share with AI tools — based on your actual work and life context. Use this before every AI session.\n\n**Step 1 — List your AI use cases:** What do you use AI for regularly or plan to use it for? Write 6-10 specific use cases.\n\n**Step 2 — For each use case**, ask: what private information might naturally come up?\n\n**Step 3 — Open Claude.ai** and paste your use case list. Ask: *"For each of these AI use cases, what private or sensitive information is likely to be involved? For each, recommend: (1) what I should anonymise or remove before sharing, (2) whether to use a privacy-first AI tool instead (e.g., local model), (3) whether this use case should be avoided with cloud AI entirely."*\n\n**Step 4 — Draft your personal AI privacy policy:** A one-page document with three sections: (a) Fine to share with cloud AI, (b) Only share after anonymising, (c) Never share with cloud AI.\n\n**Step 5 — Mandatory AI review:** Share your policy (not the sensitive content itself) with Claude and say: *"Review this AI privacy policy critically. Find 3 gaps — situations where following this policy would still expose private information I should protect."*\n\n**Step 6 — Update your policy** based on the gaps found.\n\n**Step 7 — Save your policy** somewhere you\'ll see it: a sticky note on your monitor, a pinned document, or as instructions in your Claude Project.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Anonymisation Practice', content: 'Practice turning sensitive real content into safe AI input without losing usefulness.\n\n**Step 1 — Find a real work document** that contains private information: a client email, a report with names, meeting notes with sensitive content.\n\n**Step 2 — Anonymise it** before you would share it with AI:\n- Replace real names with "Client A", "Colleague B", "Company X"\n- Replace specific figures with approximate ranges ("around £50,000")\n- Remove location details unless relevant\n- Remove identifying context unless necessary\n\n**Step 3 — Check your anonymised version:** Could someone reading it identify who it refers to? If yes, anonymise further.\n\n**Step 4 — Use the anonymised version** to complete a real task with Claude (summarise it, draft a response, analyse it).\n\n**Step 5 — Evaluate:** Did anonymising hurt the quality of AI assistance? If yes — what would you need to restore (keeping it still safe)? If no — the anonymised version was enough.\n\n**Step 6 — Write a one-sentence rule** for yourself about when and how to anonymise content for this type of task.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Team or Family AI Safety Guidelines', content: 'Apply what you\'ve learned to create guidelines for others who share your AI tools.\n\n**Step 1 — Identify your audience:** Is this for your work team, your household, your students, or yourself?\n\n**Step 2 — Ask Claude:** *"Help me write clear AI privacy guidelines for [audience]. They need to understand: (1) what information they should never type into AI tools, (2) what to do if they realise they\'ve already shared something sensitive, (3) which AI tools are appropriate for different levels of sensitivity. Keep it to one page, plain language, no jargon."*\n\n**Step 3 — Review the guidelines.** Are they realistic for your audience? Too strict? Not strict enough?\n\n**Step 4 — Refine for your specific context:** Add any organisation-specific rules (regulatory requirements, contractual obligations, company policy).\n\n**Step 5 — Share or display:** Send the guidelines to your team or household, or post them somewhere visible near where you work.' },

    { type: 'quiz', question: 'Your company\'s AI policy says "don\'t share client information with AI." A client emails you a problem and you want AI help drafting a reply. What should you do?', options: ['Skip using AI — the policy says no client information', 'Paste the full email — the AI company says they don\'t train on API inputs', 'Remove the client\'s name, company, and any identifying details from the email before asking AI to help you draft a response', 'Check whether the client gave consent to AI processing first'], correct: 2, explanation: 'The right approach is anonymisation — you can still get AI assistance without violating the policy. Replace identifying details with placeholders before sharing. This lets you get useful help while respecting privacy commitments. Skipping AI entirely (A) is overly restrictive when anonymisation solves the problem. Relying on vendor policies (B) doesn\'t satisfy your company\'s own policy requirements.' },

    { type: 'quiz', question: 'Which of these is safe to paste directly into a cloud AI tool without modification?', options: ['Your salary slip to ask for help understanding deductions', 'A spreadsheet of customer names and purchase history for analysis', 'A project brief that describes internal strategy not yet announced publicly', 'An industry report you downloaded from a public website'], correct: 3, explanation: 'Publicly available content (option D) is safe to share — it\'s already accessible to anyone. Your salary slip (A) contains personal financial data. Customer lists (B) contain personal data that may be regulated under GDPR or similar laws. Internal unpublished strategy (C) is confidential business information. When in doubt: would this content be acceptable if it leaked?' }
  ]
},

'1-6': {
  addMinutes: 40,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Copyright Scenario Drill', content: 'This 8-minute drill tests your instincts on AI and copyright — the legal area that trips up most content creators and business users.\n\n**Step 1 — Open Claude.ai** and paste this request: *"I will describe 5 content scenarios. For each, tell me: (1) what copyright risk exists, (2) what I should do to stay safe. Be specific and practical, not theoretical."*\n\n**Step 2 — Then describe these 5 scenarios** (adapting to your work):\n- You ask AI to write marketing copy "in the style of" a famous copywriter\n- You paste a news article into AI and ask it to summarise it for your newsletter\n- You use AI to create an image for a client\'s website\n- You ask AI to rewrite a competitor\'s product description to use on your own site\n- You publish an AI-written blog post under your own name\n\n**Step 3 — Read Claude\'s analysis** carefully. Which answers surprised you?\n\n**Step 4 — Identify your highest-risk current behaviour:** Is there something you already do with AI that carries legal risk you hadn\'t considered?\n\n**Step 5 — Write a one-sentence rule** you will apply to your own AI use going forward.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Write an AI Disclosure Policy for Your Content', content: 'If you publish anything — articles, social posts, reports, designs — you need a clear position on AI disclosure. This workshop builds that policy.\n\n**Step 1 — List your content outputs:** What do you publish or produce that others will read or use? (Blog posts, reports, emails to clients, designs, social media, documentation, etc.)\n\n**Step 2 — Ask Claude:** *"Help me write an AI content disclosure policy for someone who produces [list your content types]. The policy should cover: (1) when to disclose AI involvement, (2) how to disclose it, (3) what counts as \'AI-assisted\' vs \'AI-generated\', (4) what my readers/clients/employer would expect. Make it practical, not just legally defensive."*\n\n**Step 3 — Draft your disclosure policy.** Tailor it to your specific context.\n\n**Step 4 — Mandatory AI review:** Share your draft with Claude and ask: *"Review this disclosure policy critically. Find 3 situations where following this policy would still mislead someone about how much AI was involved."* Update the policy based on what Claude finds.\n\n**Step 5 — Decide on your disclosure language.** Write 2-3 ready-to-use disclosure statements you can add to content when needed. For example: "This report was drafted with AI assistance and reviewed and edited by [name]."' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Legal Risk Assessment for Your AI Workflow', content: 'Identify the specific legal risks in how you actually use AI — not theoretical risks, but real ones.\n\n**Step 1 — Describe your real AI workflow** to Claude in detail: what tools you use, for what tasks, what inputs you give them, what outputs you use and how.\n\n**Step 2 — Ask Claude:** *"Based on this workflow, identify the top 3 legal risks. For each risk: (1) what law or regulation is relevant, (2) how likely is this to be a problem for someone in my situation, (3) what one change to my workflow would eliminate or reduce this risk."*\n\n**Step 3 — Research the top risk further:** Ask Claude to explain the relevant law in plain English for your country. Then ask: "Who should I consult if I want professional advice on this?"\n\n**Step 4 — Make one concrete change** to your workflow to reduce your top legal risk.\n\n**Step 5 — Note the limits:** Claude\'s legal analysis is for general awareness, not legal advice. If your legal risk is significant, identify who you would consult for proper legal advice.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — AI Compliance Checklist for Your Role', content: 'Build a practical compliance checklist tailored to your specific role and jurisdiction.\n\n**Step 1 — Identify your role and industry:** What regulations apply to your work? (Healthcare — HIPAA/GDPR. Finance — FCA/SEC rules. Legal — privilege and confidentiality. Education — FERPA. Marketing — GDPR/CAN-SPAM. General business — employment law, data protection.)\n\n**Step 2 — Ask Claude:** *"I work in [role] in [industry] in [country]. What AI-specific legal and regulatory considerations apply to my work? Create a practical compliance checklist I can run through before starting any AI project."*\n\n**Step 3 — Review and adapt the checklist** for your specific organisation (add any company policies, contractual obligations, client requirements).\n\n**Step 4 — Test the checklist** against your current most-used AI workflow. Does your workflow pass? If not, what needs to change?\n\n**Step 5 — Save the checklist** and share it with one colleague who also uses AI.' },

    { type: 'quiz', question: 'You use AI to write an article that you publish on your company blog with your name on it. Legally and ethically, which statement is most accurate?', options: ['This is fully legal and no disclosure is needed since you own what AI generates for you', 'The article may not be copyright-protected in some jurisdictions since AI generated the content, and readers may expect disclosure of AI involvement', 'AI-generated content automatically transfers copyright to whoever runs the AI service', 'As long as you edited the AI output, full copyright belongs to you in all jurisdictions'], correct: 1, explanation: 'Copyright law for AI-generated content is unsettled and varies by jurisdiction — some courts and jurisdictions have ruled that purely AI-generated content cannot be copyright-protected (it requires human authorship). Additionally, many professional contexts have disclosure expectations. The legally and ethically safest approach is to disclose AI involvement and ensure substantial human editing and creative contribution.' },

    { type: 'quiz', question: 'A client asks you to use AI to generate images for their marketing campaign. What should you check before delivering the images?', options: ['Whether the images look professional enough', 'Whether the AI image tool\'s terms of service grant commercial use rights and whether you must disclose AI generation to the end client', 'Whether the images were generated quickly enough to meet the deadline', 'Whether the client will be able to tell the images were AI-generated'], correct: 1, explanation: 'Before delivering AI-generated images commercially, you must check: (1) whether the tool\'s terms grant commercial use — some AI image tools restrict commercial use on free plans, (2) whether you need to disclose AI generation to your client — many clients have policies or may have legal requirements to know, (3) whether the generated images resemble recognisable real people or existing copyrighted works. These are legal and contractual issues, not just aesthetic ones.' }
  ]
},

'2-3': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — ChatGPT Quick Feature Tour', content: 'This 8-minute drill gets you hands-on with ChatGPT\'s distinctive capabilities that Claude doesn\'t have.\n\n**Step 1 — Open ChatGPT** (chat.openai.com) in a browser tab.\n\n**Step 2 — Test GPT-4o vision:** Click the image icon and upload a photo from your phone or desktop — a product, a document, a whiteboard. Ask: "What do you see? What would be useful to know about this?"\n\n**Step 3 — Test web search:** Ask ChatGPT about something that happened in the last 48 hours. Does it use a search tool? Does it cite sources?\n\n**Step 4 — Test DALL-E image generation:** Ask it to generate an image relevant to your work (a diagram concept, a marketing visual, an illustration).\n\n**Step 5 — Test the voice mode** (if on mobile): Hold the microphone button and have a 1-minute verbal conversation about a topic from your work.\n\n**Step 6 — Rate each feature:** Which one is most immediately useful for your work? Which surprised you most?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Real Work Output with ChatGPT', content: 'Use ChatGPT to complete a real, specific task from your work — not a test task, something you actually need.\n\n**Step 1 — Choose a real task** that plays to ChatGPT\'s strengths: something requiring web search (current information), image analysis, data analysis, or image generation.\n\n**Step 2 — Run the task with ChatGPT.** Use whatever combination of features (chat, images, search, vision) makes sense. Don\'t settle for the first response — push for what you actually need.\n\n**Step 3 — Evaluate the output:** Is it usable as-is? What needs editing? What did ChatGPT get wrong or miss?\n\n**Step 4 — Mandatory AI review:** Paste ChatGPT\'s output back with: *"Review your own output above. Find 3 specific weaknesses — factual errors, gaps, or ways the response doesn\'t quite do what I asked."* Fix at least one issue based on the self-review.\n\n**Step 5 — Compare:** Run the same task in Claude.ai. Which output was better for this specific task? Note your finding in your AI tools guide.\n\n**Step 6 — Add ChatGPT** to (or remove it from) your personal shortlisted AI tools based on this experience.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — ChatGPT Memory and Personalisation Setup', content: 'Configure ChatGPT to know who you are — so it stops asking you to re-explain context at the start of every conversation.\n\n**Step 1 — Open ChatGPT settings.** Go to Settings → Personalization → Memory.\n\n**Step 2 — Read what ChatGPT has already stored** about you. Is it accurate? Delete anything wrong or outdated.\n\n**Step 3 — Add key context** by starting a new conversation and saying: *"I want to add to your memory about me. Please remember: I work in [role], my main AI use cases are [list], I prefer [response preferences], and [any other relevant context]."* Confirm it saved.\n\n**Step 4 — Test the memory:** Start a fresh conversation (new chat) and ask a work question without explaining who you are. Does ChatGPT apply what it knows about you?\n\n**Step 5 — Compare to Claude:** Claude\'s memory (Settings → Memory) works differently — it\'s more transparent and on-demand. Which approach do you prefer?\n\n**Step 6 — Set a reminder** to review and update both AI memories in 3 months.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — ChatGPT Custom GPT for a Recurring Task', content: 'If you have a task you do weekly or monthly with AI help, a Custom GPT can make it dramatically faster.\n\n**Step 1 — Identify a recurring task** where you always give AI the same type of context (same formatting requirements, same audience, same constraints).\n\n**Step 2 — In ChatGPT**, go to Explore GPTs → Create a GPT.\n\n**Step 3 — Configure your Custom GPT** with:\n- A name and description\n- System instructions that include all the context you always provide\n- The response format you always want\n- Any constraints or preferences\n\n**Step 4 — Test your Custom GPT** on your recurring task. Does it need less setup than a regular ChatGPT conversation?\n\n**Step 5 — Refine the instructions** based on your test. Ask the GPT: *"Review your own system instructions. What\'s ambiguous or missing that would cause you to give a suboptimal response?"*\n\n**Step 6 — Use your Custom GPT for the real task** and record: how much setup time did it save?' },

    { type: 'quiz', question: 'You need to research current market trends for a client presentation due tomorrow. Which tool is better suited for this specific task?', options: ['Claude — it\'s better at analysis and structured writing', 'ChatGPT with web search — it can retrieve current information and cite sources', 'Either tool will give the same result for research', 'Neither — you should use a search engine for research'], correct: 1, explanation: 'For current information research with citations, ChatGPT with web search (or Perplexity) is better suited. Claude\'s knowledge has a training cutoff and it cannot browse the web in real-time (without tools). For analyzing and synthesizing research you\'ve already gathered, Claude is very strong. Choosing the right tool for the task type is the key skill.' },

    { type: 'quiz', question: 'ChatGPT\'s memory feature stores information about you and applies it to future conversations. What is the main risk of this feature?', options: ['It makes responses slower because it has to load memory first', 'Outdated or incorrect memories can cause AI to make wrong assumptions that you don\'t notice', 'Memory is stored on your device, creating a security risk', 'It costs extra credits to use memory-enabled conversations'], correct: 1, explanation: 'The main practical risk of AI memory is staleness — memories saved months ago may no longer be accurate (you changed jobs, projects, preferences). If AI acts on outdated memories, you might not notice the wrong assumptions it\'s making. This is why periodic memory reviews are important: Settings → Personalization → Memory, check what\'s stored, and delete or update stale entries.' }
  ]
},

'2-4': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Gemini Multimodal Quick Test', content: 'Gemini\'s biggest differentiator is deep Google integration and multimodal capability. This drill tests both in 8 minutes.\n\n**Step 1 — Open Gemini** (gemini.google.com) in a browser tab.\n\n**Step 2 — Test image analysis:** Upload a screenshot of a work document, a photo, or an image from your work. Ask: "Analyse this image and tell me the 3 most important things you notice."\n\n**Step 3 — Test Google integration:** Ask Gemini to check your Google Calendar for tomorrow or find a recent email about a topic (requires Google account connection).\n\n**Step 4 — Test long-form content:** Paste a document you\'ve been working on (1,000+ words) and ask for a structured summary. Gemini has very large context windows.\n\n**Step 5 — Compare to Claude:** Ask the same question in Claude.ai. Which answer is more useful?\n\n**Step 6 — Identify Gemini\'s best use case for you specifically.** Where does the Google ecosystem integration help your workflow?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Real Research Task with Gemini', content: 'Use Gemini to complete a real research or analysis task — then review and improve the output.\n\n**Step 1 — Choose a real research task** from your work: a topic to investigate, a decision to inform, a background brief to prepare.\n\n**Step 2 — Run the research task** with Gemini. If you have the Google Workspace integration, use it to pull in relevant documents or data.\n\n**Step 3 — Evaluate Gemini\'s output:** Is the information current? Are sources cited? Is the analysis relevant to your actual question?\n\n**Step 4 — Mandatory AI review:** Paste the output back and say: *"Review your own research above critically. What sources should I verify independently? Where is your confidence lowest? What important angles did you miss?"*\n\n**Step 5 — Verify one specific claim** from Gemini\'s output against an independent source. Was it accurate?\n\n**Step 6 — Decide:** For this type of research task, is Gemini, Claude, or Perplexity the best fit? Add your decision to your AI tools guide.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Gemini vs Claude on Analysis', content: 'A direct comparison on an analytical task reveals where each AI genuinely excels.\n\n**Step 1 — Choose an analytical task:** Analyse a piece of text, compare two options, evaluate a plan, identify risks in a document.\n\n**Step 2 — Run it in Gemini** first. Record the response.\n\n**Step 3 — Run the identical prompt in Claude.** Record the response.\n\n**Step 4 — Compare side-by-side:**\n- Which was more thorough?\n- Which understood the nuance better?\n- Which organised the response more usefully?\n- Which made any factual errors?\n\n**Step 5 — Ask Claude** to compare the two approaches: *"Here are two AI responses to the same analytical prompt [paste both]. What are the meaningful differences? Which analytical approach is stronger and why?"*\n\n**Step 6 — Write your finding:** For analytical tasks in your work, which tool do you prefer and why?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Google Workspace AI Integration Setup', content: 'If you use Google Docs, Gmail, or Google Drive, Gemini can be integrated directly into your workflow.\n\n**Step 1 — Check your Gemini access:** In Google Workspace (if your organisation provides it) or Google One AI Premium, look for Gemini in the side panel of Google Docs or Gmail.\n\n**Step 2 — In Google Docs:** Open a document you are working on. Open the Gemini side panel. Ask it to: (a) summarise the document, (b) suggest improvements to a specific section, (c) draft a new section based on what exists.\n\n**Step 3 — In Gmail:** Find an email thread you need to reply to. Ask Gemini to: (a) summarise the thread, (b) draft a reply, (c) identify the action items you\'ve been asked to do.\n\n**Step 4 — Evaluate the integration:** Is Gemini inside your Google apps faster or more convenient than switching to a separate AI tab? What does it do well or poorly in this context?\n\n**Step 5 — Decide on one specific workflow** where you\'ll use Gemini inside Google apps going forward.' },

    { type: 'quiz', question: 'Which scenario is where Gemini has the clearest advantage over Claude?', options: ['Writing a detailed legal analysis document', 'Summarising a complex research paper', 'Automatically pulling data from your Gmail and Google Calendar to help plan your week', 'Generating creative story concepts'], correct: 2, explanation: 'Gemini\'s strongest differentiator is deep integration with Google Workspace — it can read your Gmail, Calendar, Drive documents, and other Google apps directly, without you needing to copy-paste. This makes it uniquely powerful for tasks that span your Google data. For pure writing, analysis, or creativity, the tools are more comparable.' },

    { type: 'quiz', question: 'Gemini is described as having a very large "context window." What does this mean practically?', options: ['It can generate very long responses', 'It can remember conversations for longer than other AI tools', 'It can process and reason about very large amounts of input text in a single conversation', 'It requires more computing power than other AI tools'], correct: 2, explanation: 'A large context window means you can provide very large amounts of input — entire books, large codebases, many documents — and the AI can reason across all of it in a single session. This is practically useful for tasks like "summarise this 200-page report" or "analyse all our customer feedback from Q1" where you need to process large volumes of text at once.' }
  ]
},

'2-5': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Perplexity Research Drill with Citation Checking', content: 'Perplexity\'s value is cited, current answers. This drill trains you to use AND verify its output.\n\n**Step 1 — Open Perplexity** (perplexity.ai).\n\n**Step 2 — Research a real topic** you need to know about for work: an industry trend, a competitor, a regulatory update, a technology. Write a clear question.\n\n**Step 3 — Read the answer** and identify: (a) which claims are cited with source links, (b) which claims have no citation.\n\n**Step 4 — Click through to 3 of the cited sources.** Does the actual source say what Perplexity claims it says?\n\n**Step 5 — Test a Focus Mode:** Click the Focus dropdown and switch from "All" to "Academic" (for scholarly sources) or "Reddit" (for community opinions). How does the answer change?\n\n**Step 6 — Rate your research:** How useful was Perplexity for this specific question compared to a Google search?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Research Sprint: From Question to Cited Brief', content: 'Use Perplexity to produce a fully cited research brief on a topic that matters to your work — then review it rigorously.\n\n**Step 1 — Identify a real research question** from your work: something you\'ve been meaning to look into, a topic for an upcoming meeting, background for a decision.\n\n**Step 2 — Run your research in Perplexity.** Start broad, then follow up with specific sub-questions. Aim for 3-5 exchanges that progressively deepen your understanding.\n\n**Step 3 — Save or copy the research output** and its key citations.\n\n**Step 4 — Bring the research into Claude.ai.** Paste the Perplexity output and ask: *"Based on this research, what are the 3 most important implications for someone in [your role]? What questions does this research NOT answer that I should investigate further?"*\n\n**Step 5 — Mandatory review:** Ask Claude: *"Critically review this research brief. What claims seem most uncertain? What important perspectives might be missing? What should I verify before acting on this?"*\n\n**Step 6 — Produce your final brief:** A one-page summary of the topic with 3-5 key findings, each with a source citation. Keep it — this is a real work deliverable.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Perplexity Focus Modes Comparison', content: 'Perplexity\'s Focus Modes give very different results for the same question. Understanding them helps you choose the right one.\n\n**Step 1 — Choose a question that has multiple valid perspectives:** A business decision, a technology choice, a policy debate, a health topic.\n\n**Step 2 — Ask the same question in 3 different Focus Modes:**\n- "All" — general web sources\n- "Academic" — scholarly papers\n- "Reddit" — community discussion\n\n**Step 3 — Compare the 3 answers:** How are they different? Which is most useful for your specific question?\n\n**Step 4 — Identify when to use each:**\n- Academic: When you need peer-reviewed evidence\n- Reddit/Social: When you need real-user experience\n- All: When you want a balanced general picture\n\n**Step 5 — Apply this to your workflow:** For your most common research tasks, which Focus Mode should you default to?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Set Up Perplexity for Your Work Domain', content: 'Configure Perplexity to work better for your specific field.\n\n**Step 1 — Identify your most frequent research topics** at work: the subjects you search for regularly.\n\n**Step 2 — In Perplexity**, test how it handles your domain-specific questions. Are the sources it uses appropriate for your field?\n\n**Step 3 — Create a research prompt template** for your domain. A standard prompt that includes your context and always gets better results:\n\n```\nContext: I work in [role] in [industry]. [Key context about what I need.]\nQuestion: [Your specific question]\nPlease focus on [academic sources / practitioner sources / recent news] and include publication dates for all sources.\n```\n\n**Step 4 — Test your template** on 3 different questions in your field. Refine it until the results are consistently useful.\n\n**Step 5 — Save your template** in your prompt library.' },

    { type: 'quiz', question: 'You find a Perplexity answer with 8 numbered citations. Before using this information in a client report, what should you do?', options: ['Trust the citations — Perplexity is specifically designed for cited research', 'Click through to at least 3-5 of the most important citations to verify the original source actually says what Perplexity claims', 'Ask Perplexity to double-check its own citations', 'Only use citations from .gov or .edu domains'], correct: 1, explanation: 'Perplexity citations link to real sources but the excerpt attribution can be inaccurate — the source may exist but may not actually support the specific claim. For anything that will appear in a client report, click through to the original source and verify it says what was attributed. This takes 5 minutes and prevents professional embarrassment.' },

    { type: 'quiz', question: 'You need to understand what customers actually experience when using a competitor\'s product. Which Perplexity Focus Mode is best?', options: ['Academic — for objective, peer-reviewed analysis', 'All — for the broadest range of sources', 'Reddit or Social — for authentic user experiences and community discussion', 'Writing — for a well-structured analytical summary'], correct: 2, explanation: 'For genuine user experience and community opinion, Reddit/Social focus mode surfaces discussions, reviews, and community posts that reflect what real users actually think and experience — not marketing claims or formal reviews. Academic mode finds scholarly papers (overkill for consumer experience). The skill is matching the focus mode to what type of source would best answer your specific question.' }
  ]
},

'2-6': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Microsoft Copilot First Tasks', content: 'Microsoft Copilot runs in Windows, Edge, and Bing. This drill tests it in your actual environment.\n\n**Step 1 — Open Microsoft Copilot** in the way most accessible to you: the Copilot button in Windows 11, the Copilot sidebar in Edge browser, or copilot.microsoft.com.\n\n**Step 2 — Test Copilot in Edge sidebar:** Navigate to a webpage relevant to your work. Open the Copilot sidebar and ask: "Summarise this page in 5 bullet points" and "What questions does this page not answer that I would need to know?"\n\n**Step 3 — Test web-connected answers:** Ask Copilot about something current in your industry. Does it cite sources? How current is the information?\n\n**Step 4 — Test image generation:** Ask Copilot to generate an image (it uses DALL-E 3). Request something work-related.\n\n**Step 5 — Compare to Claude:** Ask the same question you used in step 2 in Claude.ai. Which gave more useful analysis?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Complete a Real Work Task with Copilot', content: 'Use Microsoft Copilot to complete a task you actually need done this week.\n\n**Step 1 — Choose a task** that suits Copilot: something that benefits from web-connected responses, involves browsing a web page, or is a Microsoft-ecosystem task.\n\n**Step 2 — Run the task** through Copilot. Work through the conversation until you have a usable output.\n\n**Step 3 — Evaluate the output:** Is it accurate? Is it formatted in a way you can use? Did it miss anything important?\n\n**Step 4 — Mandatory review:** Paste the output to Claude.ai and say: *"Review this output. I\'m using it for [describe your task]. Find 3 specific problems, gaps, or inaccuracies I should fix before using it."* Implement at least one fix.\n\n**Step 5 — Record your comparison:** Is Microsoft Copilot better than Claude or ChatGPT for this type of task? Under what conditions would you choose Copilot over the others?\n\n**Step 6 — Update your AI tools guide** with your Copilot findings.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Copilot vs Claude on a Business Writing Task', content: 'Compare how Microsoft Copilot and Claude approach professional writing.\n\n**Step 1 — Choose a real business writing task:** Draft an email, write a summary, produce a report section, create a meeting agenda.\n\n**Step 2 — Run the task in Microsoft Copilot first.** Note the response quality, length, tone, and any formatting.\n\n**Step 3 — Run the same task in Claude.** Note differences in approach.\n\n**Step 4 — Evaluate both outputs against these criteria:**\n- Which is closer to your actual professional tone?\n- Which requires less editing before use?\n- Which misunderstood the task more?\n- Which would be more appropriate to share with your actual audience?\n\n**Step 5 — Ask Claude** to compare both outputs: *"Here are two AI responses to a business writing task [paste both]. What are the key differences in approach and quality? For professional business writing in [your context], which approach is more appropriate and why?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Add Copilot to Your Daily Windows Workflow', content: 'If you work on Windows 11, Copilot can be embedded in your daily routine without switching apps.\n\n**Step 1 — Set up Copilot access:** Enable it in your Windows taskbar (if not already visible). Pin the Edge Copilot sidebar to your browser.\n\n**Step 2 — Identify 2-3 daily tasks** that you could run through Copilot without switching apps: summarising a web page you\'re reading, drafting a quick email, searching for information while staying in your browser.\n\n**Step 3 — Test each task** using Copilot in the sidebar or Windows panel rather than opening a separate AI tab.\n\n**Step 4 — Rate the convenience:** Is in-context Copilot faster than switching to a dedicated AI tab? For which tasks?\n\n**Step 5 — Decide:** Will you use the embedded Copilot as your quick, in-context AI, with dedicated Claude or ChatGPT for heavier tasks? Write your personal workflow rule.' },

    { type: 'quiz', question: 'What is the main advantage of Microsoft Copilot over Claude for many Microsoft 365 users?', options: ['It produces higher quality writing than Claude', 'It is more accurate and less prone to hallucination', 'It integrates directly into Windows, Edge, and Microsoft 365 apps without switching applications', 'It is faster to respond than other AI tools'], correct: 2, explanation: 'Copilot\'s main advantage is seamless integration into the Microsoft ecosystem — it works inside Windows, Edge browser, Outlook, Teams, Word, Excel, and other M365 apps. This reduces context switching. It\'s not necessarily better at writing or accuracy than Claude; the advantage is workflow integration for Microsoft-heavy users.' },

    { type: 'quiz', question: 'You are reading an important 20-page report in your Edge browser and want a quick summary. What is the fastest approach?', options: ['Copy the entire report and paste it into Claude.ai', 'Open the Copilot sidebar in Edge and ask it to summarise the current page', 'Download the PDF and upload it to ChatGPT', 'Read it manually — AI summaries may miss key details'], correct: 1, explanation: 'The Edge Copilot sidebar can read and summarise the current page without copying or downloading anything — it\'s the fastest option for web-based documents. Claude is excellent for deep analysis once you have the content, but requires you to paste or upload the text. Copilot\'s in-browser integration is its biggest practical advantage for everyday page reading tasks.' }
  ]
},

'2-9': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Copilot in Outlook: Email Drafting Drill', content: 'This 8-minute drill uses Copilot in Outlook to handle a real email — the most immediate productivity win for M365 users.\n\n**Step 1 — Open Outlook** (web or desktop) with Copilot enabled.\n\n**Step 2 — Find a real email** you need to reply to — ideally one that requires a thoughtful, professional response.\n\n**Step 3 — Click "Draft with Copilot"** (or the Copilot button in the compose window). Give it context: the tone, length, and key points you want to make.\n\n**Step 4 — Review the draft.** Does it sound like you? Does it include everything you wanted? What did it miss or get wrong?\n\n**Step 5 — Ask Copilot to refine it:** "Make this more concise" or "Add a paragraph about [specific topic]" or "Change the tone to be warmer."\n\n**Step 6 — Edit the final version** yourself before sending — Copilot drafts need your personal voice and final review.\n\n**Step 7 — Time yourself:** How long did this take vs writing the email from scratch?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Copilot M365 Power Workflow', content: 'Chain Copilot across multiple M365 apps to complete a real multi-step work task end-to-end.\n\n**Step 1 — Identify a workflow** that spans multiple M365 apps. Example: you have a meeting (Teams/Outlook), need to summarise it (Teams/Word), and then follow up with stakeholders (Outlook/Teams).\n\n**Step 2 — Map your workflow steps:** List each step and which app it uses.\n\n**Step 3 — Run the workflow using Copilot in each app:**\n- In Teams: Use "Recap" to get meeting notes and action items\n- In Word: Use Copilot to draft a report based on the meeting notes\n- In Outlook: Use Copilot to draft follow-up emails\n\n**Step 4 — Evaluate each Copilot output:** Where was Copilot most useful? Where did it produce something you had to heavily edit?\n\n**Step 5 — Mandatory review:** In Word or a chat, ask Copilot: *"Review the outputs you generated in this workflow. What errors or gaps do you notice? What would a careful human reviewer catch that you missed?"* Fix the top issue.\n\n**Step 6 — Document your workflow:** Write a short guide for doing this workflow with Copilot so you can repeat it efficiently next time.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Excel Copilot: Data Analysis Without Formulas', content: 'Copilot in Excel lets you analyse data in plain English — no formulas or pivot table knowledge needed.\n\n**Step 1 — Open an Excel file** with data you work with — a sales report, a budget, a list of anything with numbers.\n\n**Step 2 — Open the Copilot pane** in Excel (Home tab → Copilot).\n\n**Step 3 — Ask plain-English questions about your data:**\n- "What are the top 5 items by [column]?"\n- "Show me a chart of [column] by [time period]"\n- "What patterns do you notice in this data?"\n- "Highlight rows where [condition]"\n\n**Step 4 — Evaluate the analysis:** Did Copilot correctly understand your data structure? Did it give useful insights?\n\n**Step 5 — Ask Copilot to check its own work:** *"Review the analysis you just did. What should I verify before relying on these findings? What might you have misunderstood about the data?"*\n\n**Step 6 — Compare:** Would this have taken you longer without Copilot? What would you have needed to know (formulas, pivot tables) to do it manually?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Your Personal M365 Copilot Playbook', content: 'Build a reference guide for how you specifically will use Copilot across your M365 apps.\n\n**Step 1 — List your top 5 most time-consuming M365 tasks** (email management, document writing, data analysis, meeting management, presentation building).\n\n**Step 2 — For each task**, identify: which M365 app does it involve, and how could Copilot help?\n\n**Step 3 — Test Copilot on at least 2 of these tasks** if you haven\'t already in this lesson.\n\n**Step 4 — Ask Claude.ai** to help you build the guide: *"I use Microsoft 365 daily and want to build a quick-reference guide for Copilot. Here are my top tasks: [list]. For each, write a 2-3 sentence guide: what Copilot prompt to use, what to watch out for, and when to not use Copilot for this task."*\n\n**Step 5 — Review and refine the guide** with your own experience from this lesson.\n\n**Step 6 — Save and share:** Keep this guide somewhere accessible and share it with a colleague who also uses M365.' },

    { type: 'quiz', question: 'You use Copilot in Teams to generate a meeting recap. Before sharing the recap with stakeholders, what is the most important step?', options: ['Format it in a professional template', 'Review it for accuracy — AI meeting recaps regularly miss action items, misattribute comments, or misrepresent decisions', 'Ask Copilot to shorten it', 'Add the recording link'], correct: 1, explanation: 'AI meeting recaps are useful starting points but need human review before sharing. Common errors include: misattributing who said what, missing key decisions made verbally, misunderstanding technical terms specific to your team, and omitting action items that were implicit rather than explicitly stated. Always review before sharing, especially for decisions or commitments you will be held accountable to.' },

    { type: 'quiz', question: 'Copilot in Word offers to "draft with Copilot" for a report. What is the best way to use this feature?', options: ['Let Copilot draft the full report and publish it after a spell-check', 'Use Copilot to draft sections, then review each section for accuracy and add your specific expertise and data', 'Only use Copilot for the introduction and conclusion — draft the body yourself', 'Avoid Copilot for reports — it\'s only good for short-form content'], correct: 1, explanation: 'The optimal approach is human-AI collaboration: let Copilot generate a working draft of sections, which gives you structure and a starting point, then review each section critically. Copilot won\'t know your specific data, your organisation\'s context, or the nuances of your situation — you need to add those. Full Copilot publish without review (A) is the main risk pattern to avoid.' }
  ]
},

'2-10': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — AI Meeting Summary Quick Test', content: 'Test an AI meeting tool on a real or recorded meeting in 8 minutes.\n\n**Step 1 — Access a meeting recording** you have available: a Teams/Zoom recording, an Otter.ai session, or a YouTube video of a talk or webinar you attended.\n\n**Step 2 — Run it through an AI summary tool:**\n- Otter.ai: upload or record directly\n- Teams: check the AI recap in the meeting chat\n- Zoom: use the AI summary in the recording\n- Alternative: paste a transcript into Claude and ask for a meeting summary\n\n**Step 3 — Evaluate the summary against these criteria:**\n- Does it correctly identify who said what?\n- Does it capture all action items and who owns them?\n- Does it correctly represent any decisions made?\n- Does it miss any important context?\n\n**Step 4 — Compare to your own recollection** of the meeting. What did the AI get wrong?\n\n**Step 5 — Write a 2-sentence verdict:** When is an AI meeting summary accurate enough to share, and when does it need heavy review?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — End-to-End Meeting AI Workflow', content: 'Build a complete AI-assisted meeting workflow: before, during, and after.\n\n**Step 1 — Choose an upcoming real meeting** (or one you had recently). Use this meeting for the full workflow.\n\n**BEFORE the meeting:**\n**Step 2 —** Ask Claude.ai: *"Help me prepare for a meeting about [topic] with [attendees/roles]. Generate: (a) 5 clarifying questions I should ask, (b) key information I should know beforehand, (c) my meeting objectives."*\n\n**DURING/AFTER the meeting:**\n**Step 3 —** Use Otter.ai, Teams recap, or Zoom AI to generate a meeting summary.\n\n**POST-MEETING:**\n**Step 4 —** Paste the AI summary into Claude.ai. Ask: *"Based on this meeting summary, generate: (a) a clear list of action items with owners and deadlines, (b) a 3-sentence decision log, (c) a follow-up email I should send to attendees."*\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review what you just generated from this meeting summary. What action items might you have missed? What decisions are ambiguous? What follow-ups are missing?"* Add anything identified.\n\n**Step 6 — Send the follow-up email** (after editing to add your personal voice).\n\n**Step 7 — Record:** How much time did the AI workflow save compared to your normal post-meeting process?' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Test Meeting AI Accuracy', content: 'Deliberately stress-test an AI meeting summary for common failure modes.\n\n**Step 1 — Take a meeting (real or recorded)** where you know what was discussed.\n\n**Step 2 — Generate an AI summary** using whichever tool you have access to.\n\n**Step 3 — Deliberately check for these common failures:**\n- Action items attributed to the wrong person\n- Decisions described as "discussed" when they were actually decided\n- Technical terms misheard or misspelled\n- Key context mentioned early in the meeting that changes meaning of later points\n- Informal commitments not captured as action items\n\n**Step 4 — Rate the summary:** On a scale of 1-10, how useful is the raw AI summary before you edit it?\n\n**Step 5 — Decide your editing protocol:** Based on this accuracy test, what level of review do you need before sharing an AI meeting summary? Write your personal rule.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Meeting Prompt Template Library', content: 'Build a set of reusable prompts for every stage of your meeting workflow.\n\n**Step 1 — List the meeting types you regularly attend** (one-on-ones, team standups, client meetings, project reviews, all-hands, etc.).\n\n**Step 2 — For each meeting type**, identify: what preparation do you usually do, what follow-ups do you usually send?\n\n**Step 3 — Ask Claude:** *"Create a prompt template library for someone who has these types of meetings: [list]. For each meeting type, provide: (1) a pre-meeting preparation prompt, (2) a post-meeting action item extraction prompt, (3) a follow-up email prompt. Make each template specific to the type of meeting."*\n\n**Step 4 — Review and adapt** the templates to your personal style and the specifics of your role.\n\n**Step 5 — Save your template library** in your prompt library document or Claude Project.\n\n**Step 6 — Test one template** on your next real meeting.' },

    { type: 'quiz', question: 'You receive an AI-generated recap of a client meeting where an important commitment was made. Before forwarding it to the client, you should:', options: ['Forward it immediately — AI transcription is accurate and will save time', 'Review the recap carefully, verify that all commitments and decisions are accurately captured, and edit before sending', 'Add a disclaimer that the recap was AI-generated', 'Re-listen to the entire recording to double-check everything'], correct: 1, explanation: 'AI meeting recaps require review before sharing externally, especially with clients. Client-facing communications create legal and relationship implications — a miscaptured commitment or decision can cause serious problems. Review the key decisions and commitments specifically. Re-listening to everything (D) is usually excessive; targeted review of important moments is the right balance.' },

    { type: 'quiz', question: 'What is the main limitation of Otter.ai for a meeting with 6 participants?', options: ['It can only transcribe 4 speakers accurately', 'Speaker identification accuracy drops significantly with more speakers, especially if voices sound similar or people talk over each other', 'It cannot process audio files longer than 1 hour', 'It does not work with remote meetings, only in-person'], correct: 1, explanation: 'Speaker diarization (identifying who is speaking) is one of the harder problems in meeting AI. With 6+ speakers, especially in real meetings where people talk over each other or have similar vocal qualities, attribution accuracy drops noticeably. This is why reviewing action item ownership in AI summaries is important — an action assigned to the wrong person based on a speaker mis-identification is a practical failure mode.' }
  ]
},

'2-11': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Browser AI Extension Quick Test', content: 'Install and test a browser AI extension on a real webpage in 8 minutes.\n\n**Step 1 — Install one browser AI extension** if you haven\'t already. Options:\n- Sider (sider.ai) — works in Chrome, Edge, Firefox\n- Monica — AI assistant in Chrome\n- Merlin — AI on any page\n- Or use the native Copilot sidebar in Edge\n\n**Step 2 — Navigate to a webpage you actually read** for work: an industry publication, a long article, a company\'s product page, documentation.\n\n**Step 3 — Open the AI extension sidebar** and test 3 things:\n- "Summarise this page" — how good is the summary?\n- Ask a specific question about the page content — does it answer correctly?\n- Ask something the page doesn\'t cover — does it acknowledge it doesn\'t know, or make something up?\n\n**Step 4 — Test it on a page you know deeply** — something in your area of expertise. Catch any errors in what it tells you.\n\n**Step 5 — Rate the extension:** Is it faster and more useful than copying text into Claude? When would you use each?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — AI Research Workflow for Industry Reading', content: 'Build a browser AI workflow that makes your regular industry reading faster and more useful.\n\n**Step 1 — Identify 3 websites you read regularly** for work: news sites, industry blogs, competitor sites, documentation.\n\n**Step 2 — Open a real article** from one of these sites. Use your browser AI extension to:\n- Get a summary\n- Extract the 3 most important implications for your specific work\n- Identify any claims that seem questionable or that you should verify\n\n**Step 3 — Ask the AI:** *"What questions should I research further based on this article? What context would change how I interpret the main claims?"*\n\n**Step 4 — Mandatory review:** Ask the AI: *"Review your own summary. What important nuance or context from the article did you omit? What might a reader of your summary misunderstand?"* Compare to the original.\n\n**Step 5 — Create a "reading workflow" prompt** you will use every time you read industry content: a standard set of questions that extract the most value from any article for your specific role.\n\n**Step 6 — Save your reading workflow prompt** in your prompt library.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Accuracy Test: Browser AI vs Reality', content: 'Browser AI extensions read and summarise pages — but how accurate are they?\n\n**Step 1 — Choose an article or page you have already read** and understand well.\n\n**Step 2 — Without telling the AI you know the content**, ask it to summarise the page and answer 3 specific questions about it.\n\n**Step 3 — Evaluate each answer:**\n- Is the summary accurate to what was actually said?\n- Did it correctly answer the specific questions?\n- Did it add anything not in the original (hallucination)?\n- Did it miss the most important point?\n\n**Step 4 — Ask the AI to identify the single most controversial or surprising claim in the article.** Was its identification accurate?\n\n**Step 5 — Write your finding:** For this type of content (technical/news/opinion/etc.), how much do you trust the browser AI\'s analysis without verification?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build Your Browser AI Toolkit', content: 'Set up a consistent browser AI workflow you\'ll actually use every day.\n\n**Step 1 — Choose your browser AI tool.** If you use Edge: built-in Copilot sidebar. If Chrome/Firefox: install one extension (Sider is a solid choice).\n\n**Step 2 — Configure it** with any personalisation options available: preferred AI model, response language, default summarisation style.\n\n**Step 3 — Create a personal quick-prompt menu.** Most extensions let you save custom prompts. Save these:\n- "Summarise for someone in [your role]"\n- "What are the key implications for [your industry]?"\n- "What should I verify before acting on this?"\n- "Extract all action items and deadlines mentioned"\n\n**Step 4 — Test your saved prompts** on 3 different pages.\n\n**Step 5 — Set a 2-week commitment:** Use your browser AI extension every time you read a long article for work. After 2 weeks, decide if it\'s worth keeping.' },

    { type: 'quiz', question: 'You use a browser AI extension to summarise a complex legal document. The summary looks clean and professional. What should you do before relying on it?', options: ['Use it directly — browser AI extensions are specifically designed for document analysis', 'Read the key sections of the original document to verify the summary captured the critical points accurately', 'Ask the extension to verify its own summary', 'Use two different extensions and compare summaries'], correct: 1, explanation: 'Browser AI summaries of complex documents (legal, medical, financial, technical) should always be verified against the original for critical decisions. AI excels at making content readable but can miss critical qualifications, conditions, exceptions, or nuances that are legally or practically important. For complex professional documents, the summary is a starting point for reading, not a replacement for it.' },

    { type: 'quiz', question: 'Which browser AI use case provides the least value and should probably be done another way?', options: ['Summarising a 5,000-word industry report before deciding whether to read it in full', 'Translating a webpage from another language', 'Asking a browser AI to fact-check information it found on the very page you are reading', 'Extracting a list of key statistics from a research paper'], correct: 2, explanation: 'Asking a browser AI to fact-check using the source it just read is circular — it\'s verifying claims against the same document that contains those claims. This provides no independent verification. Fact-checking requires an independent source. The other options (summarising before deciding to read, translation, extraction) are all legitimate uses where AI adds genuine value.' }
  ]
},

'2-12': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Slack AI Quick Summary Test', content: 'If you use Slack, this drill gets Slack AI summarising real channels — immediately reducing your backlog.\n\n**Step 1 — Open Slack** with Slack AI enabled (Pro, Business+, or Enterprise plan).\n\n**Step 2 — Find a channel** you\'ve been away from for 1+ day with unread messages.\n\n**Step 3 — Ask Slack AI** to summarise what you missed: type "Summarize this channel" or use the channel summary button.\n\n**Step 4 — Read the summary**, then scroll through the actual messages to verify:\n- Did it capture the key decisions?\n- Are any action items attributed correctly?\n- Was anything marked as important that isn\'t, or missed that is?\n\n**Step 5 — Test thread summarisation:** Find a long thread. Ask Slack AI to summarise just that thread.\n\n**Step 6 — Rate the accuracy:** On a scale of 1-10, how accurate was the channel summary? What type of messages does it handle best vs worst?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Notion AI Document Improvement Sprint', content: 'Use Notion AI to improve a real document — then review the improvement critically.\n\n**Step 1 — Open Notion** (create a free account if you don\'t have one).\n\n**Step 2 — Paste or write a real work document** in a Notion page: a report, a plan, meeting notes, a process document, a brief — anything you actually need to improve.\n\n**Step 3 — Use Notion AI to improve it.** Try each of these:\n- Select all text → Ask AI to "Improve writing"\n- Select a specific section → Ask AI to "Make this more concise"\n- Put your cursor at the end → Ask AI to "Continue writing" with a direction\n- Ask AI to "Summarise this page"\n\n**Step 4 — Compare the before and after.** Which improvements are genuinely better? Which did AI make worse?\n\n**Step 5 — Mandatory review:** Select the AI-improved text and ask AI: *"Review what you just wrote. Find 3 places where your revision weakened the original or introduced inaccuracies."* Fix any genuine regressions.\n\n**Step 6 — Keep the improved document.** This is a real work deliverable.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — AI Across Your Communication Stack', content: 'Map how AI currently exists (or could exist) across all your communication tools.\n\n**Step 1 — List every communication tool you use regularly:** Email client, chat (Slack/Teams), document platform (Notion/Confluence/Google Docs), video meetings, project management.\n\n**Step 2 — For each tool**, answer:\n- Does it have built-in AI? (Yes/No/Limited)\n- What does the AI do?\n- Have you actually used the AI feature?\n\n**Step 3 — Identify your biggest communication bottleneck:** Where do you spend the most time on communication tasks that feel repetitive or draining?\n\n**Step 4 — Ask Claude:** *"I use these communication tools: [list]. My biggest bottleneck is [describe it]. What AI features or integrations would most reduce this bottleneck? Be specific about tool names and features, not just general advice."*\n\n**Step 5 — Take one action** from Claude\'s suggestions today.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build a Team Knowledge Base with Notion AI', content: 'Notion AI can build and maintain a team knowledge base faster than writing it manually.\n\n**Step 1 — Identify a team knowledge need:** Is there something your team frequently explains to each other, to new members, or to clients that doesn\'t have a clear written reference?\n\n**Step 2 — Open Notion** and create a new page titled "[Topic] — Team Reference".\n\n**Step 3 — Dump rough notes.** Write bullet points with everything you know about the topic — don\'t worry about formatting or completeness.\n\n**Step 4 — Ask Notion AI** to: "Turn these notes into a well-structured team reference document. Add clear headings, organise the content logically, and make it easy for someone new to understand."\n\n**Step 5 — Review and fill gaps:** What did the AI miss or get wrong? Add your expertise back in.\n\n**Step 6 — Ask Notion AI:** *"Review this document. What questions would a new team member have that this page doesn\'t answer?"* Add answers to those gaps.\n\n**Step 7 — Share with your team** and get one piece of real feedback.' },

    { type: 'quiz', question: 'You use Slack AI to summarise a week of messages in a busy project channel. A colleague asks you what was decided about the project budget. You should:', options: ['Quote the Slack AI summary directly', 'Search for the actual budget discussion in the channel and verify the decision before stating it', 'Ask Slack AI to search for budget-related messages specifically', 'Say you\'ll check and get back to them'], correct: 1, explanation: 'For specific decisions — especially financial ones — always verify from the original source, not the AI summary. Slack AI summaries work well for general context but can mischaracterise specific decisions, numbers, or conditions. Find the actual message thread where the budget was discussed and confirm the exact decision before repeating it to a colleague.' },

    { type: 'quiz', question: 'Notion AI offers to auto-categorise entries in a project database. What is the appropriate way to use this?', options: ['Enable it and trust the auto-categorisation without review', 'Enable it as a time-saver but periodically review that the categories are being assigned correctly', 'Avoid it — manual categorisation is always more accurate', 'Only use it for low-stakes databases, never for project tracking'], correct: 1, explanation: 'AI auto-categorisation is a useful time-saver but degrades in accuracy over time or when edge cases appear. The right pattern is: use it to eliminate manual work, but build in a periodic review (weekly or monthly) to catch miscategorisations before they cause problems.' }
  ]
}

};

function enhance(id, filePath) {
  const raw = fs.readFileSync(filePath, 'utf8');
  const lesson = JSON.parse(raw);
  const enh = enhancements[id];
  if (!enh) { console.log('SKIP '+id+' — no enhancement defined'); return; }

  // Find insertion point: before last success callout
  let successIdx = -1;
  for (let i = lesson.sections.length - 1; i >= 0; i--) {
    if (lesson.sections[i].type === 'callout' && lesson.sections[i].variant === 'success') {
      successIdx = i;
      break;
    }
  }
  const insertAt = successIdx >= 0 ? successIdx : lesson.sections.length;

  // Insert new sections
  lesson.sections.splice(insertAt, 0, ...enh.sections);
  lesson.estimatedMinutes += enh.addMinutes;

  fs.writeFileSync(filePath, JSON.stringify(lesson, null, 2));
  const ws = lesson.sections.filter(s=>s.type==='workshop').length;
  const qz = lesson.sections.filter(s=>s.type==='quiz').length;
  console.log('OK '+id+' | workshops:'+ws+' quizzes:'+qz+' mins:'+lesson.estimatedMinutes);
}

const lessons = [
  ['1-3','data/lessons/part-01/1-3.json'],
  ['1-4','data/lessons/part-01/1-4.json'],
  ['1-5','data/lessons/part-01/1-5.json'],
  ['1-6','data/lessons/part-01/1-6.json'],
  ['2-3','data/lessons/part-02/2-3.json'],
  ['2-4','data/lessons/part-02/2-4.json'],
  ['2-5','data/lessons/part-02/2-5.json'],
  ['2-6','data/lessons/part-02/2-6.json'],
  ['2-9','data/lessons/part-02/2-9.json'],
  ['2-10','data/lessons/part-02/2-10.json'],
  ['2-11','data/lessons/part-02/2-11.json'],
  ['2-12','data/lessons/part-02/2-12.json'],
];

lessons.forEach(([id, rel]) => {
  try { enhance(id, 'C:/Projects/Learning/'+rel); }
  catch(e) { console.log('FAIL '+id+': '+e.message); }
});
