const fs = require('fs');

const enhancements = {

'10-1': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Workflow Audit Drill', content: 'Map your most repetitive tasks to identify automation opportunities.\n\n**Step 1 — For the next 8 minutes, brainstorm your most repetitive tasks.** Think about:\n- Tasks you do the same way more than once a week\n- Tasks that involve copying data between apps\n- Tasks that follow a predictable trigger-action pattern\n- Tasks where you think "I should automate this someday"\n\n**Step 2 — List them** with: task name, frequency, estimated time per occurrence, tools involved.\n\n**Step 3 — Ask Claude:** *"I have these repetitive tasks: [list them]. Which are best suited to workflow automation? Which would be hard to automate? Explain why for each."*\n\n**Step 4 — Score each task** on: automation potential (1-5) × time saved per week = automation priority score.\n\n**Step 5 — Identify your #1 automation target** — the highest-scoring task that you\'ll build in this part.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Manual Process Documentation', content: 'Before automating anything, document the current manual process precisely.\n\n**Step 1 — Choose your #1 automation target** from Workshop A.\n\n**Step 2 — Write a step-by-step description** of how you currently do this task manually:\n- What triggers you to start it?\n- What data do you need?\n- What is each step in order?\n- What decisions do you make along the way?\n- What is the final output?\n- Where does the output go?\n\n**Step 3 — Ask Claude to review your description:** *"Here is my manual process: [paste it]. Is this complete? What steps might I have forgotten? What edge cases does this process need to handle?"*\n\n**Step 4 — Refine the documentation** based on Claude\'s questions.\n\n**Step 5 — Identify the automation building blocks:** Which steps are pure data transformation? Which require external service calls? Which require human judgement?' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Automation ROI Calculator', content: 'Calculate the actual return on investment for your automation.\n\n**Step 1 — For your top 3 automation candidates**, calculate:\n```\nTime saved per occurrence: [minutes]\nFrequency per week: [times]\nWeekly time saved: [minutes × times]\nAnnual time saved: [weekly × 52]\nAt [your hourly rate], annual value: [hours × rate]\n```\n\n**Step 2 — Estimate automation build time:**\n- Simple trigger → action: 1-2 hours\n- Multi-step with conditions: 3-8 hours\n- Complex with AI processing: 8-20 hours\n\n**Step 3 — Calculate break-even point:**\n`Build hours ÷ hours saved per week = weeks to break even`\n\n**Step 4 — Ask Claude:** *"For a non-programmer, which of these 3 processes would be easiest to automate with tools like n8n or Zapier? Which would be most complex? What would each require?"*\n\n**Step 5 — Prioritise based on ROI and feasibility** — not just time saved.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Design Your First Automation Blueprint', content: 'Create a blueprint for your first automation before writing any code or using any tool.\n\n**Step 1 — Choose your automation target** (the highest ROI + feasibility combo).\n\n**Step 2 — Design the automation using this template:**\n```\n# Automation Blueprint: [Name]\n\n## Trigger\n[What starts this automation? Time, event, new data, webhook?]\n\n## Inputs\n[What data does it need?]\n\n## Steps\n1. [First action]\n2. [Second action]\n   If [condition]: [action A]\n   Otherwise: [action B]\n3. [Continue...]\n\n## Output\n[What does it produce? Where does it go?]\n\n## Error handling\n[What happens when something fails?]\n```\n\n**Step 3 — Ask Claude:** *"Review this automation blueprint. What failure modes did I not plan for? What steps require AI processing vs simple data transformation? Which tool (n8n, Zapier, Make, or custom code) would handle this best?"*\n\n**Step 4 — Refine the blueprint** based on feedback. You\'ll implement it in Lessons 10-2 through 10-4.' },

    { type: 'quiz', question: 'Which of these tasks is the BEST candidate for workflow automation?', options: ['Deciding which job applicants to interview', 'Sending a weekly report email compiled from data in a spreadsheet, formatted the same way every time', 'Providing customer support for complex technical issues', 'Strategic planning for next quarter'], correct: 1, explanation: 'Automation works best for tasks that are: consistent (same process every time), rule-based (no subjective judgement), involve data movement between systems, and happen repeatedly. Sending a compiled weekly report matches all these criteria. The other options require human judgement, contextual understanding, or creative thinking — AI can assist with these but they shouldn\'t be fully automated without human oversight.' },

    { type: 'quiz', question: 'You automate a process and it saves 30 minutes per week. It took you 20 hours to build. When does this automation break even?', options: ['After 1 week', 'After about 40 weeks (roughly 10 months)', 'After 2 weeks', 'It never breaks even because it\'s too expensive to maintain'], correct: 1, explanation: '20 hours build time ÷ 0.5 hours saved per week = 40 weeks to break even. This is on the long side — a process saving only 30 min/week needs a faster build or a longer lifespan to justify the investment. This calculation helps prioritise: a process saving 2 hours/week and taking 10 hours to build breaks even in 5 weeks, which is much more compelling. Always calculate break-even before investing automation build time.' }
  ]
},

'10-2': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop A — n8n Installation and First Workflow', content: 'Get n8n running and execute your first workflow.\n\n**Step 1 — Install n8n:**\n```powershell\nnpx n8n\n```\nOr via Docker: `docker run -it --rm --name n8n -p 5678:5678 n8nio/n8n`\n\n**Step 2 — Open n8n** at http://localhost:5678 and create an account.\n\n**Step 3 — Create your first workflow:**\n- Add a **Schedule Trigger** node (runs every minute for testing)\n- Add a **Set** node that creates a variable `message = "Hello from n8n at {{$now}}"`\n- Add a **No Operation** node to see the output\n- Connect them in order\n\n**Step 4 — Execute the workflow** manually and verify the output in the execution log.\n\n**Step 5 — Ask Claude:** *"I\'m learning n8n. What are the 5 most important node types to understand first? For each, describe what it does and a common use case."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Real n8n Workflow with AI', content: 'Build a genuinely useful n8n workflow using AI assistance.\n\n**Step 1 — Choose your automation blueprint** from Lesson 10-1 Workshop D.\n\n**Step 2 — Ask Claude Code** to help you design the n8n workflow:\n```\nI want to build this workflow in n8n: [describe your automation].\n\nHelp me:\n1. Which n8n nodes should I use for each step?\n2. What should the workflow look like structurally?\n3. For any step involving AI processing, how do I use the OpenAI or HTTP Request node to call the Anthropic API?\n4. What are the common pitfalls for this type of workflow?\n```\n\n**Step 3 — Build the workflow** in n8n following Claude\'s guidance.\n\n**Step 4 — Test with real data.** Does it work as expected?\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review this n8n workflow I built [describe it]. What failure modes haven\'t I handled? What happens when [specific API] is down or returns an error?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — n8n Error Handling', content: 'Add robust error handling to your n8n workflows.\n\n**Step 1 — Ask Claude:** *"What are the most common ways n8n workflows fail in production? For each failure mode, what is the n8n error handling approach?"*\n\n**Step 2 — Identify the failure points** in your workflow from Workshop B.\n\n**Step 3 — Add error handling** to each critical node:\n- Add an **Error Trigger** workflow that runs when any workflow fails\n- Add retry logic to HTTP Request nodes\n- Add condition nodes to handle empty/null responses\n- Add a notification step (email or Slack) on failure\n\n**Step 4 — Test error handling** by intentionally breaking part of the workflow (use a wrong API key or URL) and verify the error notification fires.\n\n**Step 5 — Ask Claude:** *"For a production n8n workflow, what monitoring and alerting should I set up beyond just error notifications?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — n8n + AI Processing Pipeline', content: 'Build an n8n workflow that includes AI text processing via the Anthropic API.\n\n**Step 1 — Choose a use case** where AI processing adds value in the middle of a workflow:\n- Classify incoming emails by topic\n- Summarise long documents before saving to Notion\n- Extract structured data from unstructured text\n- Generate personalised content based on input data\n\n**Step 2 — Ask Claude Code to generate the Anthropic API call configuration:**\n```\nGenerate an n8n HTTP Request node configuration to call the Anthropic API.\nEndpoint: https://api.anthropic.com/v1/messages\nModel: claude-haiku-4-5-20251001\nTask: [describe what you want the AI to do with each input]\nThe input comes from: [previous node output]\n```\n\n**Step 3 — Build the workflow** with the AI processing step.\n\n**Step 4 — Test with diverse inputs.** Does the AI consistently produce the right output format?\n\n**Step 5 — Add output validation:** If the AI output doesn\'t match the expected format, route to a fallback branch.' },

    { type: 'quiz', question: 'You build an n8n workflow that processes incoming emails with AI. It works in testing but occasionally fails in production. What is the most likely cause?', options: ['n8n is not production-ready software', 'Real-world inputs are more varied than test inputs — the workflow hits edge cases (empty fields, unusual characters, unexpected email formats) that weren\'t represented in tests', 'The AI model changes its behaviour over time', 'n8n workflows expire after 30 days'], correct: 1, explanation: 'The most common cause of automation failures moving from test to production: real data is messier than test data. Your test emails were well-formed; production emails might have empty subjects, unusual character encodings, very long bodies, attachment-only messages, or formats your workflow didn\'t anticipate. Fix: test with a diverse sample of real data before going live, and build defensive handling for every field your workflow reads.' },

    { type: 'quiz', question: 'An n8n workflow sends an automatic response email based on AI classification of incoming messages. What safety mechanism is most important to implement?', options: ['Rate limiting to prevent too many emails', 'A human review queue for any message the AI classifies with less than 90% confidence, or for any response that includes personal commitments or sensitive content', 'Only process emails during business hours', 'Log all AI classifications for later review'], correct: 1, explanation: 'Automated responses sent under your name or your organisation\'s name carry real consequences. The critical safety mechanism: identify cases where the automation might respond incorrectly and route those to human review. Low-confidence classifications are one signal; response content is another — any automated response that makes a commitment (scheduling a meeting, approving a request, providing pricing) should require human approval first.' }
  ]
},

'10-3': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Zapier AI Actions Exploration', content: 'Explore what Zapier\'s AI Actions capabilities can do.\n\n**Step 1 — Log into Zapier** (or create a free account).\n\n**Step 2 — Explore the app integrations** relevant to your work. Search for apps you use daily.\n\n**Step 3 — Ask Claude:** *"Compare Zapier and n8n for someone who: (1) doesn\'t want to run their own server, (2) needs to connect to common SaaS apps quickly, (3) wants AI processing within their automations. What are the trade-offs?"*\n\n**Step 4 — Explore a pre-built Zap template** related to your work. What does it do? What would you need to customise?\n\n**Step 5 — Identify your best Zapier use case:** Which automation from your blueprint would be better on Zapier (managed hosting, easy app connections) vs n8n (self-hosted, more control, free)?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Zapier + AI Zap', content: 'Build a Zapier workflow that uses AI processing.\n\n**Step 1 — Choose a simple but real automation** that can run on Zapier\'s free tier:\n- New Gmail → AI summary → save to Notion\n- New Typeform response → AI classification → add to Airtable\n- RSS feed item → AI rewrite → post to Slack\n\n**Step 2 — In Zapier**, create a new Zap:\n- Set your Trigger app and event\n- Add a Zapier AI step (using ChatGPT or Anthropic integration if available) or an HTTP Request step to call the Anthropic API\n- Add a final action to deliver the output\n\n**Step 3 — Write the AI prompt** for the processing step. Ask Claude to help: "Write a prompt for this Zap step that [describe the AI task]. The input will be [describe the trigger data format]."\n\n**Step 4 — Test the Zap** with real data.\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review this Zap I built [describe it]. What will break when [specific edge case]?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Zapier vs n8n Decision Framework', content: 'Build a decision framework for choosing between automation tools.\n\n**Step 1 — Compare on these dimensions:**\n| Criteria | Zapier | n8n | Winner for my use case |\n|---|---|---|---|\n| Hosting/maintenance | Fully managed | Self-hosted | |\n| App integrations | 5000+ native | 400+ native + HTTP | |\n| Cost at scale | Expensive | Free (self-hosted) | |\n| AI capabilities | Built-in AI steps | HTTP + any API | |\n| Privacy/data | Cloud processed | Your infrastructure | |\n| Technical skill required | Low | Medium | |\n\n**Step 2 — Fill in the "winner" column** based on YOUR specific situation and priorities.\n\n**Step 3 — Ask Claude:** *"A developer who values data privacy, plans to automate 10+ workflows, and has time to maintain infrastructure vs a non-technical marketer who needs 3 simple automations quickly — which tool fits each person?"*\n\n**Step 4 — Make your personal recommendation** based on your context.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Automation Monitoring System', content: 'Build monitoring for your automations so you know when they break.\n\n**Step 1 — Identify all automations you\'re running** (across Zapier, n8n, or other tools).\n\n**Step 2 — For each automation**, define:\n- What is the expected output or frequency?\n- How would you know if it\'s broken? (no emails sent, no records created, wrong data)\n- Who needs to be notified if it breaks?\n\n**Step 3 — Build a monitoring Zap or n8n workflow:**\n- A daily check that verifies automations ran\n- Alert if expected outputs haven\'t appeared\n\n**Step 4 — Ask Claude to design the monitoring logic:** *"I have these automations [list them]. Design a monitoring system that would alert me within 24 hours if any of them stop working. I\'d prefer to detect failures by [watching outputs, not by checking tool status]."*\n\n**Step 5 — Implement at least one monitoring check** for your most important automation.' },

    { type: 'quiz', question: 'You\'re on Zapier\'s free plan and your Zap runs 100 times per month. The free plan allows 100 tasks per month. What happens when you add a second step to the Zap?', options: ['Nothing changes — task count is per Zap, not per step', 'Each step counts as one task per Zap run — a 2-step Zap uses 200 tasks for 100 runs, exceeding the free plan limit', 'The Zap runs at half speed to conserve tasks', 'Zapier automatically upgrades your plan'], correct: 1, explanation: 'Zapier counts tasks per step per Zap run. A 3-step Zap running 100 times = 300 tasks. This is a critical pricing consideration when adding AI processing steps (which often use an additional step) — what worked on the free plan with one step may require a paid plan once you add AI processing. Always calculate: (steps in Zap) × (expected runs per month) = tasks needed, then compare to your plan limit.' },

    { type: 'quiz', question: 'A Zapier automation fails silently — it runs but produces no output and no error. What is the most likely cause and how do you diagnose it?', options: ['Zapier is down — check their status page', 'A filter or condition step evaluated to false and stopped the Zap — check the Zap\'s run history to see which step stopped processing', 'The Zap was paused by Zapier for inactivity', 'The trigger app stopped sending data to Zapier'], correct: 1, explanation: 'Silent failures in Zapier are usually caused by Filter or Path steps that evaluate to false and halt execution without error — this is by design, but it can look like a failure when the condition is wrong. Check the Run History: click on a specific run to see each step\'s input/output and at which step execution stopped. If a Filter stopped it, check the filter condition against the actual input data.' }
  ]
},

'10-4': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Make Scenario Exploration', content: 'Explore Make (formerly Integromat) and understand its visual approach.\n\n**Step 1 — Log into Make** (make.com — free plan available).\n\n**Step 2 — Explore the visual scenario builder.** How does it differ from Zapier\'s linear Zap model? Note that Make supports:\n- Loops (iterate over arrays)\n- Multiple branches/routes\n- Error handlers at the module level\n- Aggregators (combine multiple records)\n\n**Step 3 — Ask Claude:** *"Compare Make\'s visual automation builder to Zapier for complex workflows. What specific capabilities does Make have that Zapier cannot do or does poorly? When would I choose Make over Zapier?"*\n\n**Step 4 — Explore a template** from Make\'s template library for a workflow relevant to your work.\n\n**Step 5 — Identify a workflow** that would be complex on Zapier but simpler on Make (involving loops, multiple data transformations, or non-linear branching).' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Make Scenario with Data Transformation', content: 'Build a Make scenario that involves real data transformation — Make\'s strength.\n\n**Step 1 — Choose a scenario** where you need to process multiple items:\n- Fetch all GitHub issues, classify each with AI, save classified results to a spreadsheet\n- Get a daily report CSV, transform each row, send personalised emails\n- Process a list of URLs, extract content from each, summarise all and send a digest\n\n**Step 2 — Ask Claude Code to design the Make scenario:**\n```\nI want to build this in Make (formerly Integromat):\n[describe your scenario]\n\nHelp me:\n1. Which modules should I use?\n2. How should I structure the iterator/aggregator?\n3. For the AI step, write the HTTP module configuration to call the Anthropic API\n4. What\'s the data transformation approach at each step?\n```\n\n**Step 3 — Build the scenario** following Claude\'s design.\n\n**Step 4 — Test with real data.** Verify the output for 3 input items.\n\n**Step 5 — Mandatory review:** Ask: *"What failure modes exist in this scenario? What happens when the Anthropic API returns an unexpected format?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Make Error Handling and Monitoring', content: 'Configure Make\'s error handling features.\n\n**Step 1 — Ask Claude:** *"Explain Make\'s error handling approaches: error handlers, ignore, break, resume, rollback, commit. When should I use each?"*\n\n**Step 2 — Add error handling to your scenario:**\n- Add a Break handler to the HTTP module (stops iteration on that item, continues with others)\n- Add a final error notification module\n\n**Step 3 — Test error handling** by sending a malformed input that will cause the HTTP module to fail. Does the scenario handle it gracefully?\n\n**Step 4 — Configure scenario monitoring:**\n- Set up email notifications for scenario failures\n- Configure Make\'s built-in scenario monitoring (if available on your plan)\n\n**Step 5 — Ask Claude:** "Design a monitoring approach for a Make scenario that processes 500 records nightly. How would I know if 10% of records failed to process correctly?"' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Automation Consolidation Review', content: 'Review all the automation tools you\'ve tried and consolidate your approach.\n\n**Step 1 — List every automation you\'ve built or tested** across Lessons 10-1 through 10-4: n8n, Zapier, Make.\n\n**Step 2 — For each automation**, rate it:\n- Does it work reliably? (1-5)\n- Does it deliver real value? (1-5)\n- Is it maintainable? (1-5)\n\n**Step 3 — Ask Claude:** *"Based on these automations [describe them], which should I invest time in improving vs abandoning? What is the highest-value next automation I should build?"*\n\n**Step 4 — Choose ONE tool** as your primary automation platform going forward (or define when you\'d use each). Write a one-paragraph explanation of your choice.\n\n**Step 5 — Commit to running at least one automation in production** for 30 days before evaluating whether to continue.' },

    { type: 'quiz', question: 'Make\'s iterator module processes 100 items and 5 fail. What happens by default, and what should you configure instead?', options: ['The entire scenario fails if any item fails', 'By default, a failing item breaks the iterator; configure a Break error handler to skip failed items, continue with successful ones, and log failures separately', 'Make automatically retries failed items 3 times', 'Failed items are automatically added to a retry queue'], correct: 1, explanation: 'Make\'s default iterator behaviour on error can halt the entire batch. For scenarios processing multiple items where partial failure is acceptable, configure error handlers appropriately: Break (skip the failed item and continue), or Resume (mark as failed but continue). Also add a post-processing step to collect and report on failures. A scenario that successfully processes 95/100 items with a clear failure report is much more useful than one that stops at the first failure.' },

    { type: 'quiz', question: 'Make charges per operation (module run). A scenario with 5 modules runs on 200 items. How many operations does this use?', options: ['200 operations — per run of the scenario', '5 operations — per module in the scenario', '1000 operations — 5 modules × 200 items', '200 operations — the iterator counts as one'], correct: 2, explanation: 'Make counts per module execution, not per scenario run. If an iterator processes 200 items through 5 modules each: 200 × 5 = 1000 operations. This is critical for cost planning: a scenario that seems simple (5 modules) but processes large datasets becomes expensive at scale. Design Make scenarios to minimise modules in the inner loop (inside iterators) and use aggregators or bulk operations where possible.' }
  ]
},

'10-5': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop A — AI Git Workflow Drill', content: 'Use Claude Code to improve your git workflow in the next 8 minutes.\n\n**Step 1 — In a real git repository**, run:\n```bash\ngit log --oneline -20\n```\nAsk Claude Code: "Review these 20 commit messages. Which are clear and descriptive? Which are too vague? What pattern should I follow for good commit messages?"\n\n**Step 2 — Make a real code change** in the repository.\n\n**Step 3 — Ask Claude Code** to write the commit message:\n"I just made these changes: [describe them]. Write a commit message following conventional commits format (type(scope): description). Make the description explain WHY, not just WHAT."\n\n**Step 4 — Review the message.** Is it accurate? Use it or improve it.\n\n**Step 5 — Ask Claude Code:** "What other git workflow improvements would most reduce friction for a developer working on [describe your project type]?"' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — AI-Assisted PR Workflow', content: 'Build a complete AI-assisted pull request workflow.\n\n**Step 1 — Implement a small feature or bug fix** in a real repository.\n\n**Step 2 — Ask Claude Code to review your changes before you commit:**\n"Review my staged changes. Check: are there any obvious bugs, missing error handling, or code style issues? Does the implementation match what the tests would expect?"\n\n**Step 3 — Fix any issues** Claude Code identifies. Stage the fixes.\n\n**Step 4 — Ask Claude Code to write the PR description:**\n```\nWrite a pull request description for these changes.\n\nBased on the diff, include:\n- What was the problem? (or what feature was requested?)\n- What did I change and why?\n- How can a reviewer test this change?\n- Are there any concerns or trade-offs in this implementation?\n```\n\n**Step 5 — Create the PR.** Did the AI-assisted description save time and improve quality vs your usual PR descriptions?\n\n**Step 6 — Mandatory review:** Read the PR description carefully before publishing — is every claim accurate?' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Git Hooks with AI', content: 'Set up git hooks that use AI for automated quality checks.\n\n**Step 1 — Ask Claude:** *"What are the most useful git hooks for a developer using AI coding tools? For each hook (pre-commit, commit-msg, pre-push), what automated checks could I run?"*\n\n**Step 2 — Create a commit-msg hook** that validates commit message format:\n```bash\n# .git/hooks/commit-msg\n#!/bin/bash\ncommit_msg=$(cat "$1")\nif [[ ${#commit_msg} -lt 10 ]]; then\n    echo "Error: Commit message too short"\n    exit 1\nfi\n```\n\n**Step 3 — Test the hook** by trying to commit with a short message.\n\n**Step 4 — Ask Claude Code** to design a more comprehensive pre-commit hook that checks for common issues (secrets in code, large files, broken syntax).\n\n**Step 5 — Implement one additional hook** based on your most common commit mistakes.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — AI Git Aliasing', content: 'Create git aliases that use Claude Code for common AI-enhanced operations.\n\n**Step 1 — Ask Claude:** *"Design git aliases that integrate Claude Code assistance. For example, an alias that: runs git diff, pipes it to Claude Code for review, and waits for approval before committing. What other git + Claude Code workflows would be useful?"*\n\n**Step 2 — Create a shell function** (not a git alias, since these need multi-step logic) for "smart commit":\n```bash\n# Add to your .bashrc or .zshrc\nsmartcommit() {\n  git diff --staged | claude --print "Write a conventional commits message for this diff. One line only." | xargs git commit -m\n}\n```\n\n**Step 3 — Test the function** on a real staged change.\n\n**Step 4 — Create one more function** for a workflow pain point (smart PR description, automated changelog entry, etc.).\n\n**Step 5 — Evaluate after one week:** Did these functions become part of your actual workflow or did you forget about them?' },

    { type: 'quiz', question: 'Claude Code reviews your code changes and says "this looks good." Before merging to main, what should still happen?', options: ['Nothing — Claude Code\'s review is sufficient', 'A human code review — AI review catches many issues but misses business logic errors, architectural concerns, and issues requiring organisational context', 'Run automated tests only', 'Check that the code compiles'], correct: 1, explanation: 'AI code review is a first pass, not a replacement for human review. AI finds: syntax errors, common antipatterns, obvious logic bugs, style issues. AI misses: whether this change aligns with the team\'s architectural direction, whether it correctly implements the business requirement (understanding business rules requires context the AI doesn\'t have), security issues requiring deep domain knowledge, and the impact on other team members\' in-progress work.' },

    { type: 'quiz', question: 'You use Claude Code to write all your commit messages. A colleague reviews your commit history and asks who wrote the thoughtful messages. Should you tell them?', options: ['No — the messages are yours since you approved them', 'It depends on your team\'s norms, but transparency is generally better — say "I use Claude Code to draft commit messages which I then review and edit"', 'Yes — attribute every commit as AI-generated', 'Only tell them if they directly ask how you generate commit messages'], correct: 1, explanation: 'Transparency about AI tool use in professional settings is generally the better policy. Most teams are fine with AI-assisted commit messages (they\'re a convenience tool, not a professional judgement), but hiding tool use can damage trust if discovered. The honest approach: "I draft commit messages with Claude Code and review them" — most colleagues will be curious about your workflow, not critical. Teams increasingly set explicit policies about AI tool disclosure; your disclosure helps normalise it.' }
  ]
},

'10-6': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop A — First GitHub Actions Workflow', content: 'Create a GitHub Actions workflow that uses Claude for code review.\n\n**Step 1 — Create a GitHub repository** (or use an existing one).\n\n**Step 2 — Create `.github/workflows/ai-review.yml`:**\n```yaml\nname: AI Code Quality Check\non:\n  pull_request:\n    types: [opened, synchronize]\njobs:\n  lint:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Run linter\n        run: |\n          npm install --save-dev eslint\n          npx eslint . --ext .js,.ts || true\n```\n\n**Step 3 — Commit and push.** Create a PR to trigger the workflow.\n\n**Step 4 — View the workflow run** in GitHub Actions. What does it report?\n\n**Step 5 — Ask Claude Code** to improve the workflow: "Make this workflow also run tests and report results as a PR comment."' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — AI-Powered CI Pipeline', content: 'Build a CI pipeline that includes AI quality gates.\n\n**Step 1 — Ask Claude Code** to design a complete CI pipeline for your project type:\n```\nDesign a GitHub Actions CI pipeline for a [Python/Node.js/etc] project that:\n1. Runs on every PR\n2. Checks: linting, tests, security scan\n3. Posts a summary comment on the PR\n4. Blocks merge if tests fail\n5. Is fast (target: under 3 minutes)\n\nWrite the complete workflow YAML file.\n```\n\n**Step 2 — Review the generated YAML** carefully before using it — understand every step.\n\n**Step 3 — Implement the workflow** in a real repository.\n\n**Step 4 — Create a PR to trigger it.** Did all checks pass?\n\n**Step 5 — Mandatory review:** Ask: *"Review this GitHub Actions workflow. What security risks exist? What steps could be made faster? What important checks are missing?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — GitHub Actions Security', content: 'Learn to write secure GitHub Actions workflows.\n\n**Step 1 — Ask Claude:** *"What are the most common security vulnerabilities in GitHub Actions workflows? For each, show an example of the vulnerable pattern and the secure alternative."*\n\n**Step 2 — Audit your workflow from Workshop B:**\n- Are you pinning action versions by hash? (not @v3 but @sha256:...)\n- Are secrets passed via environment variables, not command args?\n- Is the GITHUB_TOKEN permission scoped to minimum needed?\n- Are you running code from fork PRs safely?\n\n**Step 3 — Fix at least one security issue** in your workflow.\n\n**Step 4 — Ask Claude Code** to write a more secure version of the workflow with all security best practices applied.\n\n**Step 5 — Compare the two workflows.** What changed? Are the secure practices meaningfully more complex?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Automated Deployment Pipeline', content: 'Build a deployment pipeline that uses AI for deployment safety checks.\n\n**Step 1 — Ask Claude Code** to design a deployment workflow:\n```\nDesign a GitHub Actions deployment workflow for [describe your project and hosting]:\n1. Triggered on merge to main\n2. Runs full test suite\n3. Builds the production artifact\n4. Deploys to [staging/production]\n5. Runs a smoke test after deployment\n6. Rolls back if smoke test fails\n7. Notifies [Slack/email] on success or failure\n```\n\n**Step 2 — Implement the staging deployment step** (even if you don\'t have a real staging environment, create the YAML structure).\n\n**Step 3 — Add a smoke test job** that checks the deployed application is responding correctly.\n\n**Step 4 — Mandatory review:** Ask Claude: *"Review this deployment pipeline. What could go wrong in the rollback step? What if deployment partially succeeds before the failure? How do we handle a failed deployment state?"*' },

    { type: 'quiz', question: 'A GitHub Actions workflow runs `npm install && npm test` on every PR. A malicious contributor submits a PR that adds code to package.json\'s postinstall script. What is the risk?', options: ['No risk — GitHub Actions is sandboxed', 'The postinstall script runs during npm install and could execute malicious code in your CI environment, potentially exfiltrating secrets', 'The PR would be automatically rejected', 'npm install never runs custom scripts in CI'], correct: 1, explanation: 'Running untrusted code (from external PRs) in CI is a real attack vector. The postinstall hook runs during npm install — if a malicious PR modifies package scripts, those scripts execute in your CI environment, which has access to repository secrets and deployment credentials. Mitigation: never run workflows triggered by pull_request_target with write permissions or access to secrets for untrusted PRs; review workflow triggers carefully.' },

    { type: 'quiz', question: 'Your CI workflow takes 15 minutes to run. Every PR triggers the full pipeline. What is the highest-impact change to make it faster?', options: ['Buy more expensive GitHub Actions runners', 'Parallelise independent jobs (linting, testing, building) and add caching for dependencies (node_modules, pip packages)', 'Skip tests on small PRs', 'Run only the tests related to changed files'], correct: 1, explanation: 'The two highest-ROI CI optimisations: (1) parallelisation — run lint, test, and build as separate jobs that run simultaneously instead of sequentially; and (2) caching — use actions/cache for node_modules, pip packages, Go modules, etc., so dependencies aren\'t reinstalled on every run. Together these can reduce a 15-minute pipeline to 4-5 minutes without skipping any checks.' }
  ]
},

'10-7': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Personal Workflow Inventory', content: 'Map your complete personal AI-assisted workflow.\n\n**Step 1 — List every AI tool** you use regularly in your work:\n- In-editor assistance (Copilot, Continue.dev, Tabnine)\n- Terminal/CLI (Claude Code)\n- Chat (Claude.ai, ChatGPT)\n- Automation (n8n, Zapier, Make)\n- Specialty tools (Cursor, Windsurf, etc.)\n\n**Step 2 — For each tool**, estimate:\n- Hours per week saved\n- Most frequent use cases\n- Biggest friction points\n\n**Step 3 — Draw your workflow diagram:** For a typical work day, when do you reach for which tool? Where are the handoffs?\n\n**Step 4 — Ask Claude:** *"Based on this AI tool stack [describe it], what important gaps exist? What workflows are inefficient because I\'m using the wrong tool or switching between too many tools?"*\n\n**Step 5 — Identify your single biggest workflow inefficiency** to address this week.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Design Your Ideal AI Workflow', content: 'Design the AI-assisted workflow you want, then identify the gaps to close.\n\n**Step 1 — Choose a major type of work** you do regularly: software development, content creation, research, client work.\n\n**Step 2 — Design your IDEAL workflow** for this work type:\n- What AI tools are involved at each stage?\n- Where does AI assist vs where does it automate?\n- What human decisions remain?\n- What does the output look like?\n\n**Step 3 — Compare to your CURRENT workflow:** What\'s different between ideal and current?\n\n**Step 4 — Identify the 3 changes** that would most close the gap between ideal and current.\n\n**Step 5 — For the highest-priority change**, ask Claude Code to help implement it:\n"I want to add [specific improvement] to my workflow. Design the implementation: what tools, configuration, or automation would I build?"' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Workflow Anti-Patterns', content: 'Identify and eliminate common AI workflow anti-patterns.\n\n**Step 1 — Ask Claude:** *"What are the most common anti-patterns in AI-assisted workflows — things people do that reduce productivity or quality? For each, describe: the pattern, why people fall into it, and the better alternative."*\n\n**Step 2 — Check yourself:** Which of these anti-patterns do YOU currently practice?\n\n**Step 3 — Common anti-patterns to specifically check:**\n- Copy-pasting AI output without review\n- Using chat AI for tasks that need agentic tools\n- Asking AI to do 5 things in one prompt instead of iterating\n- Not giving AI enough context on the first try\n- Switching tools mid-task instead of staying in one tool\n\n**Step 4 — For each anti-pattern you identified in yourself**, define the specific behaviour change you\'ll make.\n\n**Step 5 — Schedule a 30-day review** to check if you\'ve actually changed those behaviours.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Document and Share Your Workflow', content: 'Create a workflow document that could help a colleague adopt AI tools effectively.\n\n**Step 1 — Write a workflow guide** for your primary work type:\n```markdown\n# My AI-Assisted [Work Type] Workflow\n\n## Overview\n[2-3 sentence summary of your workflow]\n\n## Tools Used\n[List tools and their roles]\n\n## Daily Workflow\n### Morning\n- [Step 1: which tool, what for]\n- [Step 2: ...]\n\n### During work\n- [How AI assists the main work]\n\n### Review/output\n- [How you review AI-generated content]\n```\n\n**Step 2 — Ask Claude to review the guide:** *"Review this workflow guide. What would confuse someone new to AI tools? What important context is missing?"*\n\n**Step 3 — Refine the guide** based on feedback.\n\n**Step 4 — Share with one colleague** this week. What is their reaction? What questions do they have?\n\n**Step 5 — Update the guide** based on their feedback.' },

    { type: 'quiz', question: 'You have 6 different AI tools in your workflow. Switching between them takes 2-3 minutes each time and breaks concentration. What is the most effective solution?', options: ['Buy a faster computer to reduce switching time', 'Designate primary tool(s) for each task type and only switch when the primary tool truly cannot do the job — reduce tool sprawl', 'Use only one AI tool for everything', 'Accept that tool switching is inevitable in a complex workflow'], correct: 1, explanation: 'Context switching is a real productivity cost — not just the mechanical time but the cognitive reset required. The solution isn\'t to use one tool for everything (different tools genuinely excel at different tasks) but to be deliberate about when you switch. Define: "I use tool X for Y tasks, tool Z for W tasks" and resist the temptation to switch "just to try" in the middle of a task. Reduce your active tool set to 2-3 that cover 90% of your needs.' },

    { type: 'quiz', question: 'You\'ve spent Part 10 learning workflow automation. What is the most important mindset for maintaining these automations long-term?', options: ['Build as many automations as possible to maximise time savings', 'Treat automations like code: they need maintenance, testing, and occasional review — they will break as APIs change, and a broken automation can be worse than doing the task manually', 'Avoid complex automations — simple ones are more reliable', 'Automate everything and review failures quarterly'], correct: 1, explanation: 'Automations are maintenance commitments, not one-time builds. APIs change, services update, data formats evolve — an automation built last year may silently produce wrong results today. Budget time for automation maintenance: monthly checks that outputs are still correct, quarterly reviews of whether the automation still matches the actual process, and immediate investigation when an automation\'s output changes unexpectedly. A well-maintained automation saves time; an unmaintained one creates hidden errors.' }
  ]
},

'11-2': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Anthropic API Overview Drill', content: 'Build a mental model of the Anthropic API structure.\n\n**Step 1 — Ask Claude:** *"Explain the Anthropic API structure. What are the main endpoints? What is the messages API and how does it differ from a completions API? What are the key parameters for each request?"*\n\n**Step 2 — Read the official API docs** (console.anthropic.com/docs or docs.anthropic.com). Compare to what Claude described.\n\n**Step 3 — Map the API to what you know:** How is the Anthropic API different from or similar to REST APIs you\'ve used before?\n\n**Step 4 — Ask Claude:** *"What are the key differences between the Anthropic API\'s messages format and OpenAI\'s chat completions format? If I\'m switching from OpenAI, what do I need to change?"*\n\n**Step 5 — Sketch the request/response structure** on paper: what a minimal API call looks like.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Explore API Capabilities via Code', content: 'Write a small program to explore Anthropic API capabilities.\n\n**Step 1 — Ask Claude Code to write a Python or JavaScript script** that demonstrates multiple API features:\n```\nWrite a Python script that calls the Anthropic API and demonstrates:\n1. Basic single-turn conversation\n2. Multi-turn conversation (maintaining context)\n3. System prompt customisation\n4. Different max_tokens settings and their effect\n\nFor each demo, print the request and response clearly labelled.\n```\n\n**Step 2 — Review the code** before running it.\n\n**Step 3 — Run the script.** Does each demo work as expected?\n\n**Step 4 — Modify one parameter** and observe the effect.\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review the code you wrote. What best practices are missing? What would make this production-quality rather than exploratory?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — API Rate Limits and Error Handling', content: 'Understand Anthropic API limits and how to handle them.\n\n**Step 1 — Ask Claude:** *"What are the Anthropic API rate limits? How do they work (requests per minute, tokens per minute, tokens per day)? How do they change between plans?"*\n\n**Step 2 — Ask about error responses:** "What are the most common Anthropic API errors (rate limit, overload, invalid request, auth error)? For each, what is the HTTP status code and how should my code handle it?"\n\n**Step 3 — Ask Claude Code to write error handling code:**\n"Write a Python function that calls the Anthropic API with proper error handling: exponential backoff for rate limits, retry logic for transient errors, and clear error messages for user-caused errors."\n\n**Step 4 — Review and test the error handling** by simulating errors (wrong API key, very long input).\n\n**Step 5 — Ask:** "What monitoring should I add to detect when my application is approaching rate limits before it starts getting 429 errors?"' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build an API Wrapper Class', content: 'Build a reusable wrapper class around the Anthropic API.\n\n**Step 1 — Ask Claude Code** to design an Anthropic API wrapper:\n```\nDesign and implement a Python class AnthropicClient that wraps the Anthropic API with:\n- Retry logic with exponential backoff\n- Token counting before requests\n- Response caching for identical requests\n- Conversation history management\n- Configurable model and default parameters\n- Logging of all requests and responses\n\nMake it production-quality with proper error handling.\n```\n\n**Step 2 — Review the design** before implementation. Does it meet your needs?\n\n**Step 3 — Implement and test the class** with real API calls.\n\n**Step 4 — Mandatory review:** Ask Claude: *"Review this wrapper class. Find 3 bugs or design problems that would cause issues in production."*\n\n**Step 5 — Fix the issues** and add tests for the retry logic.' },

    { type: 'quiz', question: 'The Anthropic API uses a messages format with alternating user/assistant turns. What happens if you send two consecutive user messages?', options: ['The API processes them as a single combined message', 'The API returns an error — messages must strictly alternate between user and assistant roles (with optional system message first)', 'The API ignores the first user message', 'The API automatically inserts a placeholder assistant message'], correct: 1, explanation: 'The Anthropic messages API requires alternating user/assistant roles in the conversation history. Sending two consecutive user messages will return a validation error. To send multiple pieces of context from the user side, combine them into a single user message before sending. For multi-turn conversations, always maintain the correct alternating pattern: system (optional), user, assistant, user, assistant...' },

    { type: 'quiz', question: 'You\'re building an application using the Anthropic API. Your API key is in a .env file. What is the critical security step before deployment?', options: ['Encrypt the .env file', 'Ensure .env is in .gitignore and never committed to version control — use environment variables or a secrets manager in production', 'Use a read-only API key', 'Rotate the API key weekly'], correct: 1, explanation: 'The most common API key exposure: accidental git commit. API keys in committed .env files can be found by automated scanners within minutes of a push — even to a private repository. Steps: (1) add .env to .gitignore immediately, (2) verify it\'s not tracked with `git check-ignore -v .env`, (3) if already committed, assume the key is compromised and rotate it immediately. In production, use environment variables set in your hosting platform, not .env files.' }
  ]
},

'11-3': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — API Key Security Drill', content: 'Practice secure API key management from day one.\n\n**Step 1 — Go to console.anthropic.com** and create an API key (or use your existing one).\n\n**Step 2 — Immediately practice secure storage.** Do NOT paste the key anywhere — store it in your OS keychain or password manager:\n```powershell\n# Windows: Use environment variables\n[System.Environment]::SetEnvironmentVariable("ANTHROPIC_API_KEY", "your-key-here", "User")\n\n# Then access it in your code:\nimport os\napi_key = os.environ.get("ANTHROPIC_API_KEY")\n```\n\n**Step 3 — Create a .env file** for local development:\n```\nANTHROPIC_API_KEY=your-key-here\n```\nImmediately add `.env` to `.gitignore`.\n\n**Step 4 — Ask Claude:** *"What are the most common ways API keys are accidentally exposed? For each, what is the prevention?"*\n\n**Step 5 — Audit any existing projects** for hardcoded API keys or committed .env files.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Test Your API Key Setup', content: 'Verify your API key works and is set up securely.\n\n**Step 1 — Write a minimal test script** that reads the API key from environment variables and makes a simple API call:\n```python\nimport anthropic\nimport os\n\nclient = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))\n\nmessage = client.messages.create(\n    model="claude-haiku-4-5-20251001",\n    max_tokens=100,\n    messages=[{"role": "user", "content": "Respond with \'API key works\' and nothing else"}]\n)\nprint(message.content[0].text)\n```\n\n**Step 2 — Run with the key set** in your environment. Does it respond?\n\n**Step 3 — Test the failure case:** Unset the variable and run again. What error appears? Is the error message useful?\n\n**Step 4 — Add proper error handling** for the case where the environment variable isn\'t set.\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review this API key setup code. What security or reliability improvements would you make for production use?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Understanding API Pricing', content: 'Understand how Anthropic API pricing works to avoid surprise bills.\n\n**Step 1 — Visit the Anthropic pricing page** and record current prices for:\n- claude-haiku-4-5 (input and output per million tokens)\n- claude-sonnet-4-6 (input and output per million tokens)\n- claude-opus-4-8 if relevant\n\n**Step 2 — Ask Claude:** *"Help me estimate the monthly API cost for this use case: [describe your planned application — what it does, how many users, how many requests per user per day, approximate message length]. What is the monthly cost at each model tier?"*\n\n**Step 3 — Build a simple cost model:**\n```\nRequests per day: X\nAverage input tokens: Y\nAverage output tokens: Z\nMonthly tokens: (Y + Z) × X × 30\nMonthly cost at Haiku: [calculate]\nMonthly cost at Sonnet: [calculate]\n```\n\n**Step 4 — Set a billing alert** in console.anthropic.com to notify you when spending reaches a threshold.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Spend Monitoring for Your API', content: 'Build spend monitoring into your API usage from the start.\n\n**Step 1 — Ask Claude Code** to add token counting to your API wrapper:\n```\nModify the AnthropicClient class I built in Lesson 11-2 to:\n1. Count and log tokens used in each request\n2. Track cumulative tokens and estimated cost for the current session\n3. Warn when estimated cost for the session exceeds a configurable threshold\n4. After each request, print: "Request: Xin/Yout tokens, ~$Z"\n```\n\n**Step 2 — Test the monitoring** with several API calls. Is the cost estimate accurate?\n\n**Step 3 — Ask Claude:** "How do I track per-user or per-feature API costs in a multi-user application? What data should I store?"\n\n**Step 4 — Design a cost attribution system** for your planned application — how will you know which features are most expensive?' },

    { type: 'quiz', question: 'You accidentally committed your Anthropic API key to a public GitHub repository. What is the correct immediate response?', options: ['Delete the commit from GitHub', 'Immediately go to console.anthropic.com, revoke the exposed key and generate a new one — assume the key was already accessed by automated scanners', 'Make the repository private', 'Change the key in your .env file'], correct: 1, explanation: 'Automated scanners continuously watch GitHub for exposed API keys and typically find them within minutes. Once committed to a public repo, assume the key is compromised regardless of whether you can see it in the commit history. The only correct response: immediately revoke the key in Anthropic\'s console, generate a new key, and update your systems with the new key. Deleting commits or making repositories private does not undo the exposure — the key was already scraped.' },

    { type: 'quiz', question: 'You\'re building a web app where each user makes Anthropic API calls. You give all users the same API key. What is the problem?', options: ['There is no problem — shared keys are fine for web apps', 'All users share the same rate limits, any one user can exhaust the quota for everyone, and you cannot track or limit costs per user', 'The API key will expire faster with multiple users', 'Users can see each other\'s conversations'], correct: 1, explanation: 'Shared API keys for multi-user applications cause several problems: (1) rate limits are shared — one heavy user throttles everyone else; (2) no per-user cost attribution — you can\'t identify which users are expensive; (3) no per-user limits — a single user can spend your entire budget; (4) key rotation requires updating all users simultaneously. Better: proxy all API calls through your backend, where you can implement per-user rate limiting and cost tracking.' }
  ]
},

'11-4': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop A — First API Call Drill', content: 'Make your first Anthropic API call via curl and understand the request/response.\n\n**Step 1 — Make a minimal curl request:**\n```bash\ncurl https://api.anthropic.com/v1/messages \\\n  --header "x-api-key: $ANTHROPIC_API_KEY" \\\n  --header "anthropic-version: 2023-06-01" \\\n  --header "content-type: application/json" \\\n  --data \'{\n    "model": "claude-haiku-4-5-20251001",\n    "max_tokens": 50,\n    "messages": [{"role": "user", "content": "What is 2 + 2? Answer in one word."}]\n  }\'\n```\n\n**Step 2 — Read the response JSON.** Identify:\n- `content[0].text` — the response\n- `usage.input_tokens` and `usage.output_tokens`\n- `model` — which model responded\n- `stop_reason` — why it stopped\n\n**Step 3 — Modify the request:** Change `max_tokens` to 10 and re-run. What changes?\n\n**Step 4 — Add a system prompt:** Add `"system": "You are a pirate. Respond in pirate dialect."` to the JSON.\n\n**Step 5 — Ask Claude:** *"Explain each field in the Anthropic API request and response JSON. What is the role of anthropic-version header?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a curl-Based API Tool', content: 'Build a shell script that uses curl to interact with the Anthropic API.\n\n**Step 1 — Ask Claude Code** to write a shell script:\n```\nWrite a bash script called `ask-claude.sh` that:\n1. Takes a question as a command line argument: ./ask-claude.sh "What is the capital of France?"\n2. Calls the Anthropic API via curl with that question\n3. Extracts only the text response from the JSON (using jq)\n4. Prints the response cleanly\n5. Handles the case where the API key is not set\n6. Shows the token usage after each response\n```\n\n**Step 2 — Test the script** with several different questions.\n\n**Step 3 — Extend the script:** Add a `-s` flag to set a custom system prompt: `./ask-claude.sh -s "You are a coding expert" "How does recursion work?"`\n\n**Step 4 — Mandatory review:** Ask Claude: *"Review this shell script. What could fail in edge cases? What security risks exist?"*' },

    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop C — Multi-Turn Conversation via curl', content: 'Build a multi-turn conversation using curl.\n\n**Step 1 — Ask Claude** to explain how to build multi-turn context with the messages API.\n\n**Step 2 — Write a script** that maintains conversation history:\n```bash\n# Start with an empty history\nhistory=\'[]\'\n\n# Function to add to conversation and get response\nask() {\n  local question="$1"\n  # Add user message to history, call API, extract response\n  # Append assistant response to history for next turn\n}\n\n# Interactive loop\nwhile read -p "You: " input; do\n  ask "$input"\ndone\n```\n\n**Step 3 — Ask Claude Code** to complete this implementation.\n\n**Step 4 — Test a multi-turn conversation.** Does the assistant remember earlier context?\n\n**Step 5 — Identify the limitation:** What happens as the conversation gets very long? How do tokens accumulate?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — API Testing Framework', content: 'Build a simple framework for testing your API prompts.\n\n**Step 1 — Ask Claude Code** to write a prompt testing script:\n```\nWrite a Python script that:\n1. Takes a YAML file with test cases:\n   ```yaml\n   tests:\n     - name: "factual question"\n       prompt: "What year was the Eiffel Tower built?"\n       expected_contains: "1889"\n     - name: "math"\n       prompt: "What is 15% of 200?"\n       expected_contains: "30"\n   ```\n2. Runs each test case against the Anthropic API\n3. Checks if the response contains the expected string\n4. Reports PASS/FAIL for each test\n5. Shows total pass rate and token cost\n```\n\n**Step 2 — Create 5 test cases** relevant to your intended use case.\n\n**Step 3 — Run the tests** and review the results.\n\n**Step 4 — Mandatory review:** Ask Claude: *"Review these test cases. What important failure modes am I not testing?"*' },

    { type: 'quiz', question: 'A curl request to the Anthropic API returns HTTP 401. What does this mean and how do you fix it?', options: ['The API is down — wait and retry', 'Authentication failed — the API key is missing, wrong, or expired; check that the x-api-key header contains the correct key', 'Your request was too large', 'You\'ve exceeded your rate limit'], correct: 1, explanation: 'HTTP 401 Unauthorized means authentication failed. Diagnose: (1) is the x-api-key header present? (2) is the key value correct (no extra spaces, no quotes in the value)? (3) has the key been revoked in console.anthropic.com? (4) are you using the right API URL? In shell scripts, verify the environment variable is set: `echo $ANTHROPIC_API_KEY` should show the key value (redact it after checking). A 403 Forbidden would mean the key exists but lacks permission; 401 means the key isn\'t authenticating at all.' },

    { type: 'quiz', question: 'Your curl request to the Anthropic API is successful but the response text contains garbled output. What is the most likely cause?', options: ['The API is returning corrupted data', 'The JSON parsing is incorrect — you\'re extracting the wrong field or not unescaping the JSON string properly', 'The model is not working correctly', 'Your terminal encoding is wrong'], correct: 1, explanation: 'Garbled API response text usually comes from incorrect JSON parsing. The response is valid JSON, but extracting text from it requires navigating the structure correctly: `response.content[0].text` in JavaScript, or `jq \'.content[0].text\'` in bash. Common mistakes: extracting the whole content array instead of the first item\'s text, or not handling the text as a JSON string (which may need unescaping for special characters). Always verify the full raw response first, then work on parsing.' }
  ]
},

'11-5': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop A — SDK Quickstart', content: 'Get the Anthropic SDK working in your language of choice.\n\n**Step 1 — Install the SDK:**\n```bash\n# Python\npip install anthropic\n\n# JavaScript/TypeScript\nnpm install @anthropic-ai/sdk\n```\n\n**Step 2 — Write a minimal example:**\n```python\nimport anthropic\n\nclient = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env\n\nmessage = client.messages.create(\n    model="claude-haiku-4-5-20251001",\n    max_tokens=1024,\n    messages=[{"role": "user", "content": "Explain the Anthropic SDK in one sentence."}]\n)\nprint(message.content[0].text)\nprint(f"Tokens: {message.usage.input_tokens} in, {message.usage.output_tokens} out")\n```\n\n**Step 3 — Run it.** Does it work?\n\n**Step 4 — Ask Claude Code** to show you the equivalent using JavaScript/TypeScript.\n\n**Step 5 — Ask:** "What does the Anthropic SDK provide over using curl/HTTP directly? When would I use the SDK vs raw HTTP?"' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Real Tool with the SDK', content: 'Build a genuinely useful command-line tool using the Anthropic SDK.\n\n**Step 1 — Choose a real tool** you would actually use:\n- `summarise.py`: takes a file path, returns a summary\n- `review.py`: takes a code file, returns a review\n- `explain.py`: takes any text, explains it simply\n- `translate.py`: translates a file to another language\n\n**Step 2 — Ask Claude Code** to implement it:\n```\nBuild a Python CLI tool called [name].py that:\n- Takes [input] as a command line argument\n- Calls the Anthropic API using the SDK\n- Processes the result appropriately\n- Handles errors gracefully\n- Shows a spinner during the API call (use the rich library)\n- Prints the result formatted nicely\n\nMake it a tool I\'d actually want to use daily.\n```\n\n**Step 3 — Test it on real input** — not toy examples.\n\n**Step 4 — Mandatory review:** Ask Claude: *"Review this tool. What makes it annoying to use? What would a power user want that\'s missing?"*\n\n**Step 5 — Make 2 improvements** based on the review.' },

    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop C — Tool Use / Function Calling', content: 'Use the Anthropic SDK to implement tool use (function calling).\n\n**Step 1 — Ask Claude to explain tool use:** "Explain Anthropic\'s tool use feature. How do I define tools and how does Claude call them?"\n\n**Step 2 — Build a simple tool use example:**\n```python\nimport anthropic\nimport json\n\nclient = anthropic.Anthropic()\n\ntools = [{\n    "name": "get_weather",\n    "description": "Get the current weather for a location",\n    "input_schema": {\n        "type": "object",\n        "properties": {\n            "location": {"type": "string", "description": "City name"}\n        },\n        "required": ["location"]\n    }\n}]\n\n# Ask something that requires the tool\nresponse = client.messages.create(\n    model="claude-haiku-4-5-20251001",\n    max_tokens=1024,\n    tools=tools,\n    messages=[{"role": "user", "content": "What\'s the weather in London?"}]\n)\nprint(response.content)\nprint(response.stop_reason)\n```\n\n**Step 3 — Observe the response.** The stop_reason should be `tool_use` — Claude is asking you to call the tool.\n\n**Step 4 — Implement the full tool use loop** with Claude Code\'s help.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Production SDK Patterns', content: 'Implement production-quality patterns for the Anthropic SDK.\n\n**Step 1 — Ask Claude Code** to implement these production patterns:\n```\nImplement these production patterns for the Anthropic SDK in Python:\n\n1. Async client (using asyncio) for concurrent requests\n2. Connection pooling configuration\n3. Request timeout handling\n4. Automatic retry with exponential backoff for 529 (overload) errors\n5. Context manager for tracking costs across a code block:\n   with anthropic_cost_tracker() as tracker:\n       # make API calls\n   print(f"This block cost ${tracker.total_cost:.4f}")\n```\n\n**Step 2 — Review each pattern** before using it — does the implementation match your expectations?\n\n**Step 3 — Test the async client** with 5 concurrent requests and measure the speed improvement vs sequential.\n\n**Step 4 — Mandatory review:** Ask Claude: *"Review these production patterns. Which has the most edge cases that could cause problems in production? What am I missing?"*' },

    { type: 'quiz', question: 'You\'re using the Anthropic Python SDK and get an `anthropic.APIConnectionError`. What is the most likely cause?', options: ['Your API key is wrong', 'Network connectivity issue — the SDK cannot reach the Anthropic API servers', 'The model name is incorrect', 'You\'ve exceeded your rate limit'], correct: 1, explanation: 'APIConnectionError means the SDK couldn\'t establish or maintain a connection to the API — this is a network-level error, not an authentication or API error. Possible causes: no internet connection, firewall blocking the request, DNS resolution failure, or the Anthropic API being temporarily unreachable. Distinguish from: APIStatusError (the API responded with an error code), AuthenticationError (bad API key), or RateLimitError (too many requests). Check network connectivity first, then look at Anthropic\'s status page.' },

    { type: 'quiz', question: 'You call the Anthropic API with `max_tokens=100` but the response seems cut off at a strange point. What is happening?', options: ['The API is broken', 'The model generated 100 tokens and stopped — max_tokens is a hard limit on output tokens, not on output length or completion quality', 'The response was rate-limited and truncated', 'The model decided the response was complete'], correct: 1, explanation: 'max_tokens is a hard limit on output tokens — when reached, the response stops exactly there, even mid-sentence. The stop_reason will be "max_tokens" (not "end_turn"). For production use: (1) set max_tokens high enough that normal responses complete (check stop_reason to verify), (2) if the response hits the limit, you may want to continue the conversation to get the rest of the output, (3) use max_tokens as a budget cap, not as a response length target.' }
  ]
},

'11-6': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Token Counting Drill', content: 'Build intuition for how tokens work by counting them.\n\n**Step 1 — Use the Anthropic tokeniser** (or ask Claude Code to count tokens): ask Claude to estimate the token count of several texts:\n- A single word: "Hello"\n- A tweet-length text: "Just finished my first Claude API integration!"\n- A paragraph: [paste a paragraph from this lesson]\n- A code snippet: [paste 10 lines of Python]\n\n**Step 2 — Ask Claude:** *"What are the general rules for how many tokens common things use? For example: characters per token, words per token, code vs prose, different languages."*\n\n**Step 3 — Estimate tokens BEFORE Claude tells you:**\n- A JSON object with 5 string fields\n- A complete URL\n- A 200-word essay\nThen verify your estimates.\n\n**Step 4 — Calculate the cost** of processing each text through claude-haiku-4-5-20251001 (at current pricing).\n\n**Step 5 — Develop a rule of thumb** for estimating your API costs before building.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build Token-Aware Code', content: 'Modify your API wrapper to be token-aware.\n\n**Step 1 — Ask Claude Code** to add token counting to your existing API wrapper:\n```\nAdd these token-aware features to the AnthropicClient class:\n1. Before each API call, estimate the token count and warn if it exceeds a configurable threshold\n2. After each API call, track running totals: input tokens, output tokens, estimated cost\n3. Implement a `token_budget` parameter — if the conversation history grows beyond this budget, automatically truncate oldest messages while keeping the system prompt\n4. Add a `get_usage_summary()` method that returns current session stats\n```\n\n**Step 2 — Test the token budget feature** with a very long conversation. Does it truncate correctly?\n\n**Step 3 — Verify the cost tracking** against the Anthropic console after your test session.\n\n**Step 4 — Mandatory review:** Ask Claude: *"Review the truncation logic. What conversations would this handle badly? What context might be inappropriately dropped?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Model Selection Strategy', content: 'Build a strategy for choosing which Claude model to use.\n\n**Step 1 — Ask Claude:** *"Compare Claude Haiku, Sonnet, and Opus for these use cases: (1) classifying customer support emails, (2) writing detailed technical documentation, (3) answering simple factual questions, (4) complex reasoning tasks. For each, recommend the model and explain the cost/quality trade-off."*\n\n**Step 2 — Build a decision matrix:**\n| Task Type | Recommended Model | Reason |\n|---|---|---|\n| Simple classification | | |\n| Short Q&A | | |\n| Complex analysis | | |\n| Creative generation | | |\n| Code review | | |\n\n**Step 3 — Fill in the matrix** based on Claude\'s guidance.\n\n**Step 4 — Calculate the cost difference** for your primary use case at Haiku vs Sonnet vs Opus. What is the monthly saving of choosing Haiku over Sonnet?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Cost Optimisation Experiment', content: 'Reduce API costs for a real use case through optimisation.\n\n**Step 1 — Take a real prompt** you use regularly.\n\n**Step 2 — Establish baseline cost:** Run it and record token counts.\n\n**Step 3 — Apply these optimisations** and measure the token reduction:\n1. Remove redundant context (information the model doesn\'t need)\n2. Compress verbose instructions (be more concise)\n3. Use structured output format to reduce output tokens\n4. Test with a smaller model first\n\n**Step 4 — For each optimisation**, verify the output quality didn\'t degrade. Cost reduction is only valuable if quality is maintained.\n\n**Step 5 — Calculate the final optimisation:** What % cost reduction did you achieve? At what scale does this matter?' },

    { type: 'quiz', question: 'You\'re building an app that processes 1000 documents per day, averaging 2000 tokens each. Should you use Claude Haiku or Sonnet?', options: ['Always use Sonnet for better quality', 'Test both models on your specific task first — if Haiku\'s quality is sufficient, it will cost significantly less at this volume', 'Always use Haiku to minimise cost', 'Use different models for different documents based on content complexity'], correct: 1, explanation: 'Model selection should be empirical, not assumed. Test Haiku on your actual task with diverse examples and evaluate quality. If Haiku meets your quality bar, the cost savings at scale are substantial. If quality is insufficient, Sonnet\'s cost is justified. The wrong approach: automatically using the most capable model without testing whether a cheaper model suffices. At 1000 documents/day × 2000 tokens, even a 5× price difference translates to significant monthly savings.' },

    { type: 'quiz', question: 'Your API cost is unexpectedly high. What is the most effective diagnostic step?', options: ['Switch to a cheaper model immediately', 'Log the token counts of each API call for one day to identify which calls are consuming the most tokens — the highest spenders are the optimisation targets', 'Reduce max_tokens for all API calls', 'Check the Anthropic console for billing details'], correct: 1, explanation: 'Unexpectedly high API costs have specific causes — usually a small number of expensive call patterns, not uniformly high usage. Without logs, you\'re guessing. Log: which endpoint/feature made the call, input tokens, output tokens, and model for each request. After one day of logging, sort by cost to identify the top 3 most expensive call patterns. Optimising those (shorter prompts, smaller model, caching) typically delivers 70%+ of possible savings.' }
  ]
},

'11-7': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop A — Streaming First Response', content: 'Experience streaming and understand when it matters.\n\n**Step 1 — Make a non-streaming API call** for a long response (ask for a 500-word essay). Note the delay before text appears.\n\n**Step 2 — Make the same call with streaming:**\n```python\nwith client.messages.stream(\n    model="claude-haiku-4-5-20251001",\n    max_tokens=1024,\n    messages=[{"role": "user", "content": "Write a 500-word essay about the history of computing."}]\n) as stream:\n    for text in stream.text_stream:\n        print(text, end="", flush=True)\nprint()  # newline at end\n```\n\n**Step 3 — Compare the user experience.** Which feels more responsive? At what response length does streaming become clearly better?\n\n**Step 4 — Ask Claude:** *"When does streaming matter most for user experience? When is it unnecessary overhead? How do token timing and TTFB (time to first byte) relate to streaming?"*\n\n**Step 5 — Build intuition:** For a 10-token response, is streaming worth it? For a 500-token response?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Streaming Chat Interface', content: 'Build a streaming chat interface in the terminal.\n\n**Step 1 — Ask Claude Code** to implement a full streaming chat:\n```\nBuild a Python terminal chat application using the Anthropic SDK with:\n1. Streaming responses that print word-by-word\n2. Conversation history maintained across turns\n3. A typed indicator while the model is generating ("Claude is thinking...")\n4. Token usage displayed after each response\n5. A /clear command to reset conversation history\n6. A /exit or Ctrl+C to quit gracefully\n\nMake it feel polished like a real chat interface.\n```\n\n**Step 2 — Test the chat** with a real conversation.\n\n**Step 3 — Intentionally ask something that generates a long response.** How does the streaming experience feel?\n\n**Step 4 — Mandatory review:** Ask Claude: *"Review this chat implementation. What bugs might occur in edge cases? What would crash the chat unexpectedly?"*\n\n**Step 5 — Fix at least one issue** from the review.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Streaming in Web Applications', content: 'Understand how to implement streaming in web applications.\n\n**Step 1 — Ask Claude:** *"How does API streaming work in a web application? Specifically: if I call the Anthropic API from my backend and want to stream the response to the frontend browser, what technology does this require (Server-Sent Events, WebSockets, etc.)?"*\n\n**Step 2 — Compare the two main approaches:**\n| Approach | How it works | Best for |\n|---|---|---|\n| Server-Sent Events | Server pushes events to browser | One-way streaming, simple |\n| WebSockets | Bidirectional persistent connection | Real-time bidirectional |\n\n**Step 3 — Ask Claude Code** to generate a simple FastAPI + SSE streaming endpoint:\n"Write a FastAPI endpoint that streams an Anthropic API response to the browser using Server-Sent Events."\n\n**Step 4 — Review the code.** Do you understand how the stream flows from Anthropic → your server → the browser?\n\n**Step 5 — Ask:** "What are the failure modes of this streaming approach? What happens if the user closes the browser tab mid-stream?"' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Add Streaming to Your API Tool', content: 'Upgrade your API tool from Lesson 11-5 to use streaming.\n\n**Step 1 — Take the CLI tool** you built in Lesson 11-5 Workshop B.\n\n**Step 2 — Ask Claude Code to add streaming:**\n"Modify my [tool name] tool to stream the response. Show each word/chunk as it arrives instead of waiting for the full response. Add a --no-stream flag for cases where I want the full response at once."\n\n**Step 3 — Compare the experience** with and without streaming. For your tool\'s typical use case, is streaming meaningfully better?\n\n**Step 4 — Add progress indication:** For very long responses, add a live token counter that updates as tokens arrive: "Generating... [143 tokens]"\n\n**Step 5 — Test edge cases:** What happens if you interrupt (Ctrl+C) during streaming? Is the interrupt handled gracefully?' },

    { type: 'quiz', question: 'You implement streaming in your app but users report they see the entire response appear all at once. What is the most likely cause?', options: ['The Anthropic API stopped supporting streaming', 'Output buffering — your web server or proxy is accumulating the stream before sending it to the client; disable buffering or send explicit flush signals', 'Streaming requires a paid plan', 'The response is too short to benefit from streaming'], correct: 1, explanation: 'The classic streaming failure: output buffering at an intermediate layer. NGINX, AWS Application Load Balancer, Gunicorn, and other components between your code and the user\'s browser often buffer responses for efficiency. Symptoms: streaming works locally (direct connection) but not in production (through a proxy). Fix: set appropriate headers (`X-Accel-Buffering: no` for NGINX, `Transfer-Encoding: chunked`), and ensure your server flushes after each chunk.' },

    { type: 'quiz', question: 'A user closes their browser tab while your application is streaming a response. What should your server do?', options: ['Continue generating the response and cache it for when they return', 'Detect the client disconnection and cancel the streaming API call to avoid wasting tokens on a response no one will see', 'Complete the response and bill it to the next request', 'Throw an error and restart the session'], correct: 1, explanation: 'When a client disconnects mid-stream, the right response is to abort the API call — you\'re paying for tokens that are being generated for no recipient. In FastAPI with SSE, detect client disconnection in the async generator and break the loop, which will cause the API stream to cancel. This avoids wasting both API cost and compute resources. For non-streaming calls, this is less critical (the call is already complete), but for long-running streams, it\'s a meaningful cost consideration.' }
  ]
},

'11-8': {
  addMinutes: 30,
  sections: [
    { type: 'workshop', tag: 'BUILD', title: 'Workshop A — Build the Summarizer CLI', content: 'Build the text summariser tool described in the lesson.\n\n**Step 1 — Ask Claude Code to scaffold the full project:**\n```\nBuild a production-ready CLI tool called summarise.py that:\n1. Accepts a file path or stdin as input\n2. Calls the Anthropic API to summarise the content\n3. Supports flags:\n   --length short/medium/long (controls summary detail)\n   --format bullet/prose/structured\n   --model haiku/sonnet (default: haiku for cost)\n4. Handles large files by chunking if needed (over 50k tokens)\n5. Shows a progress spinner during processing\n6. Outputs the summary cleanly, then shows token usage and cost\n\nWrite the complete implementation.\n```\n\n**Step 2 — Review the code** thoroughly before running it.\n\n**Step 3 — Test on real files:** a code file, a document, a long email.' },

    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop B — Add Features to Your CLI', content: 'Extend your summariser based on real usage experience.\n\n**Step 1 — Use the summariser on 5 real documents** from your work.\n\n**Step 2 — Identify the most annoying limitation** in its current form.\n\n**Step 3 — Ask Claude Code to add the feature:**\n- Batch processing: `summarise.py *.txt > summaries.md`\n- Output to file: `--output summary.md`\n- Compare mode: summarise two files and highlight differences\n- Follow-up questions: after summarising, enter an interactive mode to ask questions about the document\n\n**Step 4 — Test the new feature** with real input.\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review the implementation of [new feature]. What edge cases did I miss? What would break with unusual inputs?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop C — Test Your Tool End-to-End', content: 'Write tests for your CLI tool.\n\n**Step 1 — Ask Claude Code to write a test suite:**\n```\nWrite a pytest test suite for summarise.py that:\n1. Tests each --length option produces different output lengths\n2. Tests --format produces correctly formatted output\n3. Tests that file-not-found is handled gracefully\n4. Tests that very short input (under 10 words) is handled gracefully\n5. Tests that the token count in output is a positive integer\n\nUse pytest-vcr or mock the Anthropic API calls so tests don\'t cost real money.\n```\n\n**Step 2 — Run the tests:** `pytest tests/ -v`\n\n**Step 3 — Fix any failures.** Are the failures real bugs or test issues?\n\n**Step 4 — Check coverage:** `pytest --cov=summarise`' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Deploy and Share Your Tool', content: 'Package your CLI tool for distribution.\n\n**Step 1 — Ask Claude Code** to help package the tool:\n```\nHelp me package summarise.py for distribution:\n1. Create a pyproject.toml so it can be installed with pip install\n2. Create a requirements.txt\n3. Write a README.md with installation instructions and usage examples\n4. Add a --version flag\n5. Make it available as a global command: `summarise` after installation\n```\n\n**Step 2 — Install your own tool:** `pip install -e .`\n\n**Step 3 — Test that the global command works:** `summarise README.md`\n\n**Step 4 — Share with one colleague** and observe how they use it. What confused them? What did they want that was missing?' },

    { type: 'quiz', question: 'Your summariser CLI works great on 5-page documents but hangs on a 200-page PDF. What is happening and how do you fix it?', options: ['PDFs are not supported by the API', 'The document exceeds the context window — you need to chunk the document into segments, summarise each, then summarise the summaries', 'The API has a 200-page limit', 'You need a more powerful computer'], correct: 1, explanation: 'Every model has a context window limit. A 200-page document might be 100,000+ tokens — more than any single API call can handle. The solution is hierarchical summarisation: (1) split the document into chunks that fit within the context window (with overlap for context continuity), (2) summarise each chunk, (3) combine chunk summaries into a meta-summary. This is called the "map-reduce" summarisation pattern and is essential for handling documents of arbitrary length.' },

    { type: 'quiz', question: 'You build a summariser that works well for English text but produces poor results for French documents. What is the most likely reason and fix?', options: ['The API doesn\'t support French', 'Your system prompt doesn\'t specify the target language — add "Respond in the same language as the document" or explicitly "Respond in French" to the system prompt', 'French uses more tokens and you need higher max_tokens', 'You need a different model for non-English text'], correct: 1, explanation: 'Claude supports many languages but defaults to responding in English when the language isn\'t specified. For multilingual applications, add explicit language instructions to the system prompt: "Summarise the document in the same language it was written in." You can also dynamically detect the language of the input and add a specific instruction. Without this, Claude may respond in English even when the source document is in another language.' }
  ]
},

'11-9': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Token Cost Mapping', content: 'Map the cost landscape for different token optimisation strategies.\n\n**Step 1 — Ask Claude:** *"Explain Anthropic\'s prompt caching feature. How does it work, what is the price difference for cached vs non-cached tokens, and what types of content benefit most from caching?"*\n\n**Step 2 — Calculate the savings** for your use case:\n```\nMy system prompt: ~500 tokens\nRequests per day: 100\nWithout caching: 500 tokens × 100 × input price = X\nWith caching: 500 tokens × 0.10 × input price (first request) + (cached price × 100 × 500) = Y\nMonthly savings: (X - Y) × 30\n```\n\n**Step 3 — Ask Claude:** "Explain model routing — using cheaper models for simpler requests and expensive models only for complex ones. Design a routing strategy for [describe your application\'s request types]."\n\n**Step 4 — Calculate the model routing savings** for your use case.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Implement Prompt Caching', content: 'Add prompt caching to your API wrapper to save on repeated system prompts.\n\n**Step 1 — Read the Anthropic prompt caching documentation** to understand the cache_control parameter.\n\n**Step 2 — Ask Claude Code** to modify your API wrapper to use prompt caching:\n```\nModify the AnthropicClient class to support prompt caching:\n1. Add a cache_system_prompt parameter (default True)\n2. When enabled, add cache_control: {type: "ephemeral"} to the system message\n3. Track cache_creation_input_tokens and cache_read_input_tokens separately\n4. Update the cost calculator to use correct prices for cached tokens\n5. Show cache hit rate in usage summaries\n```\n\n**Step 3 — Test caching by making the same system prompt call multiple times.** Do the cached token counts appear in the response?\n\n**Step 4 — Verify the cost reduction** in the usage statistics.' },

    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop C — Model Router Implementation', content: 'Build a model router that selects the cheapest model adequate for each request.\n\n**Step 1 — Ask Claude Code** to design and implement a model router:\n```\nBuild a model_router function that:\n1. Classifies the request as simple/medium/complex based on:\n   - Input length (short/medium/long)\n   - Presence of reasoning keywords ("analyse", "explain why", "compare")\n   - Whether it asks for creative generation\n2. Routes simple requests to claude-haiku-4-5-20251001\n3. Routes medium requests to claude-haiku-4-5-20251001 (with higher max_tokens)\n4. Routes complex/creative requests to claude-sonnet-4-6\n5. Logs which model was selected for each request\n```\n\n**Step 2 — Test the router** with 10 diverse requests. Does it classify correctly?\n\n**Step 3 — Compare the output quality** of routed vs always-Sonnet responses on the same requests.\n\n**Step 4 — Mandatory review:** Ask Claude: *"Review the routing logic. What request types will be misclassified? What are the failure modes?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Full Cost Engineering Implementation', content: 'Combine all cost engineering techniques into a production-ready setup.\n\n**Step 1 — For your most expensive API use case**, apply all three strategies:\n1. **Prompt caching:** cache the system prompt\n2. **Token minimisation:** review and trim the system prompt and few-shot examples\n3. **Model routing:** use the cheapest model that maintains quality\n\n**Step 2 — Measure before and after** — track tokens and estimated cost for 10 identical requests before and after optimisation.\n\n**Step 3 — Calculate the annual savings** if this call is made at your expected production volume.\n\n**Step 4 — Mandatory review:** Ask Claude: *"Review my cost optimisation. What am I missing? What additional techniques could further reduce cost without impacting quality?"*\n\n**Step 5 — Document the final optimisation strategy** as a reference for your next API project.' },

    { type: 'quiz', question: 'Prompt caching saves money when the same system prompt is reused across many requests. What is the condition that must be met for caching to work?', options: ['The system prompt must be under 1000 tokens', 'The cached content must be identical across requests and meet the minimum token threshold (typically 1024 tokens for the system message)', 'Caching only works for the same user', 'You must pre-register prompts to be cached'], correct: 1, explanation: 'Anthropic\'s prompt caching requires: (1) the content must be exactly identical across requests (any character difference means a cache miss), (2) the content must meet the minimum token threshold (typically 1024 tokens), and (3) the cache_control parameter must be set in the API request. Caching is particularly effective for long system prompts that are reused across many requests — a 2000-token system prompt reused 100 times saves significantly.' },

    { type: 'quiz', question: 'Your model router incorrectly classifies a complex analysis request as "simple" and routes it to Claude Haiku. The user receives a lower-quality response. How do you improve the router?', options: ['Always use Claude Sonnet — routing is too risky', 'Collect examples of misclassified requests, analyse the pattern, and improve the routing logic — then add a feedback mechanism where users can flag poor responses for manual review', 'Lower the threshold so more requests go to Sonnet', 'Ask users to manually select the model tier'], correct: 1, explanation: 'Model routing is an empirical problem — the right approach is to build feedback loops. Collect cases where routing produced poor results, analyse what features of those requests caused misclassification, and update the routing logic. Also add a quality signal: track user feedback or proxy metrics (did the user ask a follow-up question indicating the response was insufficient?). Use these signals to continuously improve routing accuracy over time.' }
  ]
}

};

function enhance(id, filePath) {
  const raw = fs.readFileSync(filePath, 'utf8');
  const lesson = JSON.parse(raw);
  const enh = enhancements[id];
  if (!enh) { console.log('SKIP '+id); return; }
  let successIdx = -1;
  for (let i = lesson.sections.length - 1; i >= 0; i--) {
    if (lesson.sections[i].type === 'callout' && lesson.sections[i].variant === 'success') {
      successIdx = i; break;
    }
  }
  const insertAt = successIdx >= 0 ? successIdx : lesson.sections.length;
  lesson.sections.splice(insertAt, 0, ...enh.sections);
  lesson.estimatedMinutes += enh.addMinutes;
  fs.writeFileSync(filePath, JSON.stringify(lesson, null, 2));
  const ws = lesson.sections.filter(s=>s.type==='workshop').length;
  const qz = lesson.sections.filter(s=>s.type==='quiz').length;
  console.log('OK '+id+' | ws:'+ws+' qz:'+qz+' mins:'+lesson.estimatedMinutes);
}

const lessons = [
  ['10-1','data/lessons/part-10/10-1.json'],
  ['10-2','data/lessons/part-10/10-2.json'],
  ['10-3','data/lessons/part-10/10-3.json'],
  ['10-4','data/lessons/part-10/10-4.json'],
  ['10-5','data/lessons/part-10/10-5.json'],
  ['10-6','data/lessons/part-10/10-6.json'],
  ['10-7','data/lessons/part-10/10-7.json'],
  ['11-2','data/lessons/part-11/11-2.json'],
  ['11-3','data/lessons/part-11/11-3.json'],
  ['11-4','data/lessons/part-11/11-4.json'],
  ['11-5','data/lessons/part-11/11-5.json'],
  ['11-6','data/lessons/part-11/11-6.json'],
  ['11-7','data/lessons/part-11/11-7.json'],
  ['11-8','data/lessons/part-11/11-8.json'],
  ['11-9','data/lessons/part-11/11-9.json'],
];

lessons.forEach(([id, rel]) => {
  try { enhance(id, 'C:/Projects/Learning/'+rel); }
  catch(e) { console.log('FAIL '+id+': '+e.message); }
});
