const fs = require('fs');

const enhancements = {

'3-3': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Persona Switch Drill', content: 'This 8-minute drill shows how dramatically a single persona instruction changes AI output.\n\n**Step 1 — Choose a topic you know something about** — a subject where you can judge the quality of different explanations.\n\n**Step 2 — Ask Claude the same question 4 times** with different persona instructions:\n1. No persona instruction — just ask the question\n2. "Explain this as if you are a university professor lecturing first-year students"\n3. "Explain this as a practitioner with 10 years of hands-on experience — skip theory, focus on what actually matters"\n4. "Explain this as a sceptic who is going to challenge every assumption"\n\n**Step 3 — Compare the 4 responses.** Note: tone, vocabulary level, what is included vs omitted, how confident the voice sounds.\n\n**Step 4 — Identify which version was most useful** for your specific purpose. For the same topic, the right persona depends on your audience and goal.\n\n**Step 5 — Save the most useful persona instruction** in your prompt library.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Role-Based Reviewer', content: 'The most powerful use of persona prompting is building a panel of expert reviewers for your work. This workshop creates a reusable reviewer prompt.\n\n**Step 1 — Choose a real document you\'ve written** (a report, plan, email, presentation, or analysis).\n\n**Step 2 — Ask Claude** to review it three times with three different expert personas:\n```\nFirst, review this document as a sharp senior executive who cares only about whether this is actionable and worth their time.\n\nThen, review it as a detail-oriented auditor looking for logical gaps, unsupported claims, and missing information.\n\nFinally, review it as a cynical devil\'s advocate whose job is to argue against every recommendation.\n```\n\n**Step 3 — Collect all three reviews.** What did each expert notice that the others missed?\n\n**Step 4 — Mandatory AI review:** Ask Claude: *"Based on the three reviews above, what are the 3 most important changes I should make to this document? Don\'t just list the issues — prioritise and give me a specific fix for each."*\n\n**Step 5 — Make at least 2 of the changes** before saving the final document.\n\n**Step 6 — Save this 3-persona review prompt** in your prompt library. You will reuse it every time you write something important.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Persona for Audience Adaptation', content: 'The same content often needs to reach very different audiences. This workshop builds an audience adapter.\n\n**Step 1 — Choose a piece of your work** that needs to be communicated to multiple audiences: a technical finding, a business update, a data analysis result, a policy change.\n\n**Step 2 — Ask Claude to adapt it** for three different audiences:\n- Your direct manager (strategic, 2-3 sentences, focus on implications)\n- The team doing the work (operational, focus on what changes for them)\n- An external stakeholder or client (no jargon, focus on what they need to know or decide)\n\n**Step 3 — Review each adaptation.** Does each version sound right for its audience? Is anything missing that this specific audience would need?\n\n**Step 4 — Ask Claude for an audit:** *"Review all three versions. Which one most accurately represents the original content? Which one is most appropriate for its audience? Where did the adaptation introduce any distortion?"*\n\n**Step 5 — Use the best version** for your real communication need.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Create Your Expert Panel Prompt', content: 'Build a customised expert panel for your specific domain — a reusable prompt that simulates the reviewers you\'d most want before sending something important.\n\n**Step 1 — Think about your work.** Who are the people whose opinions matter most when you produce something? List 3-4 real types of reviewers (your manager, a subject matter expert, a skeptical client, a compliance officer, a newcomer who might be confused).\n\n**Step 2 — For each reviewer**, write:\n- Their role and expertise\n- What they care about most\n- What they are most likely to challenge\n- The tone they would use\n\n**Step 3 — Ask Claude:** *"Based on these reviewer profiles [paste them], create a role-prompting template I can use to get all four reviews at once whenever I write something important. Each role should feel distinct and challenge different aspects of the work."*\n\n**Step 4 — Test the template** on a real piece of your work.\n\n**Step 5 — Refine and save.** The expert panel prompt is one of the highest-value tools in any serious AI user\'s toolkit.' },

    { type: 'quiz', question: 'You ask Claude to "respond as a harsh critic who finds problems." What is the main benefit of this persona instruction?', options: ['It makes Claude generate longer responses', 'It overrides Claude\'s tendency to validate and agree, surfacing genuine problems in your work', 'It makes Claude use more formal language', 'It allows Claude to access information it would normally withhold'], correct: 1, explanation: 'Without explicit instruction, AI tends toward validation and agreement — it finds what\'s good about your work rather than what\'s problematic. A critic persona directly counteracts this tendency, making Claude actively look for problems, gaps, and weaknesses rather than strengths. This is why adversarial personas are so valuable for reviewing your own work before it goes to a real audience.' },

    { type: 'quiz', question: 'You write a prompt: "You are an expert in marketing." What is the most effective improvement to this persona instruction?', options: ['Adding "Please" to make it more polite', 'Specifying the expert\'s viewpoint, what they care about, and what problem you want them to solve', 'Making the persona sound more impressive ("world-renowned expert")', 'Adding "be creative" to the end'], correct: 1, explanation: 'The key improvement is specificity: what type of marketing, what perspective, what they care about, and what you need from them. "Expert in marketing" gives Claude very little to work with. "Marketing director at a B2B SaaS company who cares deeply about retention metrics and always challenges vanity metrics" gives Claude a clear, actionable lens to apply. The more specific the persona context, the more useful and distinct the response.' }
  ]
},

'3-4': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Chain-of-Thought Quick Comparison', content: 'This 8-minute drill shows you exactly how much reasoning instructions improve AI output.\n\n**Step 1 — Choose a problem that requires analysis** — not a simple factual question, but something with trade-offs: a business decision, a technical choice, a recommendation with pros and cons.\n\n**Step 2 — Ask Claude the question twice:**\n\nVersion 1 (no CoT): just ask the question directly.\n\nVersion 2 (with CoT): add "Think through this step by step. First, identify the key factors. Then analyse each factor. Then consider trade-offs. Finally, give your recommendation with reasoning."\n\n**Step 3 — Compare the responses.** In Version 2:\n- Did Claude consider factors it missed in Version 1?\n- Is the reasoning visible so you can check it?\n- Is the conclusion more defensible?\n\n**Step 4 — Identify the specific reasoning step** that produced the most insight you wouldn\'t have gotten from Version 1.\n\n**Step 5 — Note for yourself:** For what types of questions should you always use chain-of-thought instructions?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Solve a Real Problem with Chain-of-Thought', content: 'Apply chain-of-thought prompting to a real, meaningful problem you\'re currently facing — and get better analysis than you would with a direct question.\n\n**Step 1 — Identify a real problem or decision** you are currently facing at work or in life. It should be complex enough that the answer isn\'t obvious.\n\n**Step 2 — Write a structured CoT prompt:**\n```\nI need help thinking through [problem].\n\nContext: [explain the situation, constraints, what matters]\n\nPlease reason through this in the following order:\n1. What are the key factors I need to consider?\n2. What do I know for certain vs what is uncertain?\n3. What are 2-3 realistic options?\n4. For each option, what are the main benefits and risks?\n5. What is your recommendation, and why?\n6. What would need to be true for a different option to be better?\n```\n\n**Step 3 — Run the prompt.** Read through Claude\'s reasoning step by step.\n\n**Step 4 — Challenge the reasoning:** At whichever step you disagree with, push back: "In step 3, you said [X]. I think that\'s wrong because [Y]. Re-reason from that point."\n\n**Step 5 — Mandatory final review:** Ask Claude: *"Review your own reasoning above. What assumptions are you making that I should check? Where could your reasoning be wrong?"*\n\n**Step 6 — Make a decision** based on the full reasoning. Did the CoT process change what you would have decided?' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Build a Reasoning Audit Prompt', content: 'Use chain-of-thought in reverse: make AI explain the reasoning behind an existing decision or claim, not just generate a new one.\n\n**Step 1 — Find a piece of work with a recommendation or conclusion**: a report, a plan, a memo, a piece of analysis with a conclusion.\n\n**Step 2 — Ask Claude to reverse-engineer the reasoning:**\n```\nHere is a conclusion: [paste the conclusion or recommendation]\n\nWork backwards from this conclusion:\n1. What assumptions must be true for this conclusion to be correct?\n2. What data or evidence would support each assumption?\n3. What would invalidate this conclusion?\n4. Is this a strong or weak conclusion? What would make it stronger?\n```\n\n**Step 3 — Review the reverse-engineered reasoning.** Did the analysis surface any assumptions you hadn\'t explicitly considered?\n\n**Step 4 — Improve the original work:** Based on the reverse-engineering, what would make the conclusion stronger or better defended?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build Your CoT Prompt Templates', content: 'Create a library of chain-of-thought templates for your most common analytical task types.\n\n**Step 1 — List the 3-4 types of analytical problems you face most often** at work: evaluating options, root-cause analysis, planning a project, writing a recommendation.\n\n**Step 2 — For each problem type**, design a specific CoT reasoning sequence — what steps should the AI reason through for this type of problem?\n\n**Step 3 — Ask Claude:** *"I want to create chain-of-thought prompt templates for these problem types: [list]. For each, write a reasoning framework — the specific steps AI should work through to produce the best analysis. Make each framework match what a senior practitioner in [your field] would actually think through."*\n\n**Step 4 — Test each template** on a real problem from that category.\n\n**Step 5 — Refine the templates** based on what the test revealed. Add them to your prompt library.' },

    { type: 'quiz', question: 'You ask Claude to recommend a project management tool. Without chain-of-thought, it says "Notion is the best choice." With chain-of-thought, it reasons through team size, integration needs, and budget before recommending Notion. What is the key advantage of the CoT version?', options: ['The CoT version is more likely to be correct because it considered more factors', 'The CoT version is always faster to read', 'The CoT version lets you identify exactly where you disagree with the reasoning and correct it', 'The CoT version sounds more impressive to share with others'], correct: 2, explanation: 'The key advantage of visible reasoning is debuggability — you can inspect each reasoning step and identify specifically where the logic diverges from your situation. If the CoT version says "assuming team size of 5-10 people" but your team is 50, you can correct that assumption and get a better recommendation. A direct answer gives you a conclusion with no visible reasoning to check or challenge.' },

    { type: 'quiz', question: 'You are using chain-of-thought to analyse a business risk. After seeing Claude\'s Step 3 (risk assessment), you think one risk is significantly understated. What should you do?', options: ['Accept Claude\'s assessment — it has processed more information than you have', 'Start a new conversation and ask the question again', 'Tell Claude specifically what you think is understated and why, and ask it to re-reason from that point', 'Ask Claude to "try harder" in its risk assessment'], correct: 2, explanation: 'Chain-of-thought is designed to be interactive — you can intervene at any step. If you disagree with a specific step, say so explicitly with your reasoning, and ask Claude to revise from that point forward. This is far more effective than starting over or giving vague feedback like "try harder." Your domain knowledge about specific risks is something Claude may not have; interactive correction is how you get it incorporated.' }
  ]
},

'3-5': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Few-Shot Format Drill', content: 'This 8-minute drill shows how dramatically examples change the format and quality of AI output.\n\n**Step 1 — Choose a type of content you regularly produce**: a report section, a status update, a brief, a recommendation, an email template.\n\n**Step 2 — Without examples**, ask Claude to produce one instance of this content. Save the result.\n\n**Step 3 — Now provide 2 examples** of the output format you actually want (use real examples from your work or write 2 brief samples). Then ask Claude to produce another instance "following the same style and format as these examples."\n\n**Step 4 — Compare the two outputs.** How different are they? Which better matches your actual style preferences?\n\n**Step 5 — Identify the specific formatting elements** that the few-shot version captured that the zero-shot version missed.\n\n**Step 6 — Note:** For any recurring content type where style consistency matters, few-shot examples are the fastest path to getting the format right.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build Your Few-Shot Content Templates', content: 'Create few-shot templates for your most common content types — so you never start from scratch on recurring formats.\n\n**Step 1 — Identify 3 types of content you produce regularly** where consistency and format matter: emails, reports, meeting notes, code comments, analysis sections, etc.\n\n**Step 2 — Find 2 real examples** of each that represent your ideal output. These can be things you\'ve written that you\'re proud of.\n\n**Step 3 — Build a template for each content type:**\n```\nHere are examples of [content type] that represent the style and format I want:\n\nExample 1:\n[your example]\n\nExample 2:\n[your example]\n\nNow write [content type] for: [new input]\n\nFollow the exact same structure, tone, and level of detail as the examples.\n```\n\n**Step 4 — Test each template** with a real new instance of that content type.\n\n**Step 5 — Mandatory review:** Ask Claude: *"Compare your output to my examples. Where did you deviate from the format or style? List specific differences."* Refine the template if needed.\n\n**Step 6 — Save all 3 templates** in your prompt library.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Examples for Classification Tasks', content: 'Few-shot examples are especially powerful for classification and categorisation tasks. This workshop demonstrates why.\n\n**Step 1 — Choose something from your work that you categorise regularly**: customer feedback, support tickets, expense types, content topics, priority levels — any classification task.\n\n**Step 2 — Without examples**, ask Claude to classify 5 items from your actual data. Note how it categorises them.\n\n**Step 3 — Now provide 3 labelled examples** that show exactly how you would classify items in your specific system:\n```\nHere are examples of how I classify [item type]:\n\n[Item 1]: Category A — because [brief reason]\n[Item 2]: Category B — because [brief reason]\n[Item 3]: Category C — because [brief reason]\n\nNow classify these new items using the same approach: [your 5 items]\n```\n\n**Step 4 — Compare the two sets of classifications.** How much did the examples change the results? Which set is more aligned with how you would actually classify them?\n\n**Step 5 — Write a one-sentence rule:** When should you always provide examples before asking Claude to classify?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build a Style Guide Through Examples', content: 'Instead of describing your writing style, show it. This workshop creates an example-based style guide.\n\n**Step 1 — Select 3-4 pieces of writing you\'ve produced** that best represent your preferred style: emails, reports, documentation, social media posts, etc.\n\n**Step 2 — Ask Claude to analyse your style** based on the examples:\n```\nHere are 3 examples of content I\'ve written. Analyse them and identify:\n1. My sentence length preference (short/medium/long/mixed)\n2. My tone (formal/professional/conversational/direct)\n3. My paragraph structure patterns\n4. What I never do (e.g., I never use buzzwords, I never write passive voice)\n5. Any distinctive stylistic choices\n\n[paste your examples]\n```\n\n**Step 3 — Review Claude\'s style analysis.** Is it accurate? Add anything it missed.\n\n**Step 4 — Create a style instruction block** you can paste into any prompt when you want Claude to write in your voice:\n```\nWrite in my voice, which is characterised by: [paste Claude\'s analysis, corrected]\n```\n\n**Step 5 — Test the style instruction** on a new piece of content. Does the output sound like you?' },

    { type: 'quiz', question: 'You want Claude to write status updates in the exact format your team uses. Which is the most effective approach?', options: ['Describe the format in words: "Write a status update with three sections: Progress, Blockers, and Next Steps"', 'Paste two real examples of status updates your team has approved, then ask Claude to follow the same format', 'Ask Claude to write a status update and then ask it to revise the format', 'Tell Claude the format is "professional and concise"'], correct: 1, explanation: 'Showing examples is far more effective than describing format in words. When you paste 2 real examples, Claude can match the exact header style, sentence length, level of detail, and formatting conventions that your team actually uses — details that are hard to capture in a description. "Professional and concise" (D) gives Claude almost nothing to work with.' },

    { type: 'quiz', question: 'You provide 3 few-shot examples of customer service emails in a warm, friendly tone. Claude\'s output is much more formal. What is the most likely cause?', options: ['Claude cannot match tone from examples', 'The examples were too short for Claude to learn from', 'Your instructions elsewhere in the prompt contradict the examples (e.g., "write professionally")', 'You need at least 5 examples for tone to transfer'], correct: 2, explanation: 'When examples and explicit instructions conflict, the result is unpredictable. If your prompt says "write professionally" (which Claude interprets as formal) but your examples are warm and friendly, Claude may follow the explicit instruction over the examples. Remove conflicting instructions, or make the style instruction consistent with the examples: "Write in the warm, conversational tone shown in these examples."' }
  ]
},

'3-6': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Structured Output Quick Drill', content: 'This drill produces structured output from unstructured input — one of the most immediately useful AI workflows.\n\n**Step 1 — Find unstructured text** you have at hand: a set of notes, an email thread, a meeting transcript, a web article, a list of feedback.\n\n**Step 2 — Extract a table** from it:\n```\nExtract all [tasks / decisions / people mentioned / dates / key points] from the following text and format them as a markdown table with columns: [Column1] | [Column2] | [Column3]\n\n[paste your text]\n```\n\n**Step 3 — Extract JSON** from the same text:\n```\nExtract the same information as structured JSON. Use this schema:\n{\n  "items": [\n    {\n      "field1": "",\n      "field2": "",\n      "field3": ""\n    }\n  ]\n}\n```\n\n**Step 4 — Compare:** Which format (table or JSON) is more useful for your specific use case?\n\n**Step 5 — Note the use case:** When in your actual work would extracting structured data from unstructured text save you the most time?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Data Extraction Pipeline', content: 'Create a reusable prompt that extracts structured data from a document type you work with regularly.\n\n**Step 1 — Identify a document type** you regularly receive and need to extract specific information from: invoices, reports, feedback surveys, meeting notes, job applications, contracts, emails.\n\n**Step 2 — Identify all the fields** you need to extract from this document type. Be specific.\n\n**Step 3 — Design your extraction schema.** For JSON:\n```\n{\n  "document_type": "[type]",\n  "extracted_at": "[timestamp]",\n  "data": {\n    "field1": "",\n    "field2": [],\n    "field3": {\n      "subfield1": "",\n      "subfield2": ""\n    }\n  },\n  "missing_fields": [],\n  "extraction_confidence": "high/medium/low"\n}\n```\n\n**Step 4 — Write your extraction prompt** using the schema above. Include: what to do if a field is missing ("leave blank and add to missing_fields") and what to do if information is ambiguous ("extract literally, flag in notes").\n\n**Step 5 — Test it on 3 real examples** of the document type.\n\n**Step 6 — Mandatory review:** Ask Claude: *"Review your own extractions. In which extraction are you least confident? What might you have missed or misinterpreted?"*\n\n**Step 7 — Save your extraction prompt** in your prompt library.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — From Raw Data to Report', content: 'This workshop takes raw structured data and turns it into a human-readable report using a two-step process.\n\n**Step 1 — Gather raw data** you have: survey results, metrics from a dashboard, financial figures, performance data — any numbers or structured records.\n\n**Step 2 — Step A (extract/organise):** Ask Claude to:\n```\nHere is raw data: [paste data]\n\nOrganise this into a structured summary with:\n- Total count and key totals\n- Top 3 findings by [metric]\n- Notable patterns or anomalies\n- Any missing or inconsistent data\n```\n\n**Step 3 — Step B (narrate):** Take the structured summary and ask:\n```\nConvert this structured data summary into a 3-paragraph executive briefing for [audience]. Focus on implications and what decisions the data should inform — not just description of the numbers.\n```\n\n**Step 4 — Review the final briefing.** Is it accurate? Does it draw the right conclusions?\n\n**Step 5 — Ask Claude:** *"What important insight from the data did you NOT include in the briefing? What might a data expert notice that a non-expert would miss?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Create a Structured Output Template Library', content: 'Build a collection of structured output templates for your most common data needs.\n\n**Step 1 — List 4-5 types of structured output you produce regularly** or wish you could produce more easily: project status reports, meeting notes in standard format, risk registers, content calendars, issue trackers.\n\n**Step 2 — For each type**, design an ideal JSON schema or table structure that would capture everything you need.\n\n**Step 3 — Ask Claude:** *"Help me design a complete JSON schema for a [type]. It should capture: [describe what you need]. Make it practical for someone who will paste raw text and get structured data out. Include a \'confidence\' field and a \'notes\' field for the model to flag uncertainty."*\n\n**Step 4 — Test each schema** with a real example of the raw input.\n\n**Step 5 — Save all schemas** in a "Structured Output Templates" section of your prompt library.' },

    { type: 'quiz', question: 'You want Claude to extract all action items from a meeting transcript as JSON. Which instruction produces the most reliable structured output?', options: ['Extract action items from this meeting transcript', 'Extract action items and return them as JSON', 'Extract action items as JSON using exactly this schema: {"action_items": [{"task": "", "owner": "", "deadline": "", "priority": "high/medium/low"}]}. If owner is not mentioned, use "Unassigned". If deadline is not mentioned, use null.', 'Extract action items, owners, and deadlines in a useful format'], correct: 2, explanation: 'Providing the exact schema with explicit field names, types, and fallback instructions (what to do when a field is missing) is the gold standard for structured output. Without a schema, Claude will invent its own structure which may not match what your downstream process expects. The more specific the schema and the more clearly you handle edge cases (missing fields, ambiguous values), the more reliable and consistent the output.' },

    { type: 'quiz', question: 'Claude extracts a table from your document but includes one row where it invented a value not present in the source. What is the best mitigation?', options: ['Always verify every cell manually', 'Add a "source_quote" field to your schema so Claude must cite the exact text it extracted each value from', 'Ask Claude to re-do the extraction', 'Accept that AI extraction will always have some errors'], correct: 1, explanation: 'Adding a "source_quote" field forces Claude to cite the exact source text for each extracted value. This makes hallucinations immediately visible — if a cell has no valid source quote, you know it was invented. It also makes verification fast: you can spot-check source quotes rather than verifying every value independently. This is the professional approach to AI data extraction for anything that will be acted upon.' }
  ]
},

'3-7': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Iterative Refinement Speed Drill', content: 'This drill demonstrates that the best AI outputs come from iteration, not from perfect first prompts.\n\n**Step 1 — Choose a real task** where you\'d use AI: drafting an email, writing a section of a report, creating a plan.\n\n**Step 2 — Write the simplest possible prompt** — just a sentence or two. Run it. Save the output.\n\n**Step 3 — Refine it once.** Identify the single biggest problem with the output and address only that. Run it again.\n\n**Step 4 — Refine it twice.** Identify the next biggest problem. Address only that. Run it again.\n\n**Step 5 — Compare outputs from rounds 1, 2, and 3.** How much did each iteration improve the result?\n\n**Step 6 — Note:** At which iteration did the output become good enough to use? For most tasks, 2-3 iterations gets you 80-90% of the way there. Beyond that, you may be better off editing the output directly rather than continuing to iterate the prompt.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Full Iterative Refinement Cycle on Real Work', content: 'Apply systematic iterative refinement to a real, important piece of work.\n\n**Step 1 — Identify a real deliverable** you need to produce: a report, a proposal, a plan, a document, an analysis.\n\n**Step 2 — Draft iteration 1.** Use a brief prompt — just describe what you need at a high level.\n\n**Step 3 — Structured feedback pass.** For Iteration 1\'s output, identify:\n- Content gaps: "This is missing [specific thing]"\n- Format problems: "The structure should be [how]"\n- Tone problems: "This is too [formal/casual/long/short]"\n- Accuracy problems: "This is wrong: [specific issue]"\n\n**Step 4 — Draft iteration 2.** Address all the feedback above in a single follow-up message.\n\n**Step 5 — Final polish pass.** Ask Claude: *"Read your own output. Find 3 specific improvements — not just grammar, but substance. Where is the reasoning weakest? Where is the writing vaguest? Where does this not quite do what was asked?"* Address at least 2.\n\n**Step 6 — Mandatory external review:** Show the final output to Claude one more time and ask: *"If you were the intended reader [describe the audience], what question would you ask that this document doesn\'t answer?"* Add the answer.\n\n**Step 7 — Save the final output.** This is a real deliverable you produced using structured iteration.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Prompting Debugging Technique', content: 'When iteration isn\'t working, you need to debug why. This workshop teaches prompt debugging.\n\n**Step 1 — Take a prompt that isn\'t giving you good results** — something you\'ve tried at least twice and the output keeps being wrong in the same way.\n\n**Step 2 — Ask Claude to diagnose the problem:**\n```\nI\'ve been asking you to [describe what you\'ve been asking for] but the output keeps [describe the problem]. Here is my prompt: [paste your prompt]\n\nDon\'t answer the original question. Instead, tell me: (1) What is ambiguous about my prompt? (2) What am I probably assuming that I haven\'t stated? (3) Rewrite my prompt to fix these issues.\n```\n\n**Step 3 — Run the rewritten prompt.** Is the output better?\n\n**Step 4 — Note the pattern:** What was the core issue with your original prompt? (Too vague? Missing context? Wrong format instruction? Conflicting requirements?)\n\n**Step 5 — Apply the fix type** to any similar prompts you\'ve been struggling with.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build an Iteration Checklist for Your Work', content: 'Create a standard refinement process you\'ll use every time for your most important AI outputs.\n\n**Step 1 — Identify your top 3 use cases** where you use AI for important outputs (something you\'d be embarrassed to get wrong).\n\n**Step 2 — For each use case**, design a 3-5 step review checklist — the specific things to check at each refinement round.\n\n**Step 3 — Ask Claude:** *"Help me create an iterative refinement workflow for [use case]. What should I check in iteration 1 vs iteration 2 vs final polish? What are the common failure modes for [use case] that I should specifically watch for?"*\n\n**Step 4 — Test your checklist** on the next real instance of each use case.\n\n**Step 5 — Save the checklists** in your prompt library alongside the prompts they apply to.' },

    { type: 'quiz', question: 'After 4 rounds of refinement, Claude\'s output is still not quite right. What is the most effective next step?', options: ['Keep iterating until it\'s perfect — AI will eventually get there', 'Switch to a different AI tool', 'Stop iterating and manually edit the AI\'s output — at some point, direct editing is faster than further prompting', 'Start over with a completely new approach'], correct: 2, explanation: 'There is a point of diminishing returns in prompt iteration where manual editing becomes faster and more precise than continued prompting. If after 3-4 iterations the output is 80-90% right, it\'s usually faster to edit the remaining 10-20% directly than to describe the remaining issues as a prompt and verify the new output. Recognising this threshold is a sign of prompt maturity.' },

    { type: 'quiz', question: 'Which feedback is most useful when iterating on an AI output?', options: ['"This isn\'t quite right, try again"', '"Make it better"', '"The second paragraph is too long and the conclusion doesn\'t address the main question. The conclusion should answer: what should the reader do next?"', '"I don\'t like the tone"'], correct: 2, explanation: 'Effective iteration feedback is specific: it identifies the exact location of the problem, describes what is wrong, and states what you want instead. Vague feedback ("try again", "make it better", "I don\'t like the tone") gives Claude nothing specific to act on and tends to produce random changes rather than targeted improvements. Think of it like reviewing code: "this function is wrong" is useless; "line 47: this condition should check > not >=" is actionable.' }
  ]
},

'3-8': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Prompt Template Quick Build', content: 'This 8-minute drill shows how a simple template with fill-in-the-blank placeholders eliminates repetitive prompting.\n\n**Step 1 — Identify a task you do with AI at least once a week.** Something where you always provide similar information but change specific details.\n\n**Step 2 — Write out the last 2-3 prompts you used** for this task. What stays the same? What changes?\n\n**Step 3 — Build a template** by converting the static parts to fixed text and the dynamic parts to placeholders:\n```\n[CONTEXT]: I work in [YOUR ROLE] at [COMPANY TYPE].\n[TASK]: Write a [DOCUMENT TYPE] for [AUDIENCE].\n[TOPIC]: The subject is: [TOPIC]\n[CONSTRAINTS]: [LENGTH / TONE / FORMAT requirements]\n[EXAMPLES]: [Optional: paste example if you have one]\n```\n\n**Step 4 — Test your template** on a real instance of the task. Fill in the brackets and run it.\n\n**Step 5 — Save the template.** Add it to your prompt library with a label.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Complete Prompt Library', content: 'This workshop produces a real, usable prompt library you will open and reference starting today.\n\n**Step 1 — List every AI task you do regularly.** Write at least 8-10 specific tasks, grouped by type: Writing, Research, Analysis, Planning, Communication.\n\n**Step 2 — For your top 5 most important tasks**, build a template for each.\n\n**Step 3 — Ask Claude to help meta-prompt each template:**\n```\nHere is a task I do regularly: [describe it]\nHere is my current prompt: [paste it]\n\nImprove this prompt by:\n1. Making the context instruction more specific\n2. Adding a clear output format specification\n3. Adding instructions for how to handle edge cases\n4. Adding a self-check instruction at the end (ask Claude to review its own output)\n5. Making the placeholders clearer and labelled\n```\n\n**Step 4 — Compile all 5 templates** into a single document structured as:\n```\n# Prompt Library\n\n## [Task Name]\n**When to use:** [one sentence]\n**Template:**\n[full prompt]\n**Notes:** [tips]\n```\n\n**Step 5 — Test every template** on a real task.\n\n**Step 6 — Mandatory quality check:** For each template, ask Claude: *"If you received this template filled in with a typical example, what would be ambiguous or unclear? What instructions are missing that would help you produce a better output?"* Improve each template.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Organise and Share Your Prompt Library', content: 'A prompt library is only valuable if you can find and use the right prompt when you need it.\n\n**Step 1 — Decide where to store your prompt library.** Options:\n- A Notion page (searchable, shareable)\n- A Google Doc (simple, accessible everywhere)\n- A Claude Project (prompts as instructions visible in every conversation)\n- A local Markdown file (fast to open, version-controllable)\n\n**Step 2 — Create your chosen storage location** and paste your library into it.\n\n**Step 3 — Add a quick-find header** at the top: a table of contents with jump links to each prompt category.\n\n**Step 4 — Test the retrieval:** Imagine you need a specific type of prompt in 30 seconds. Can you find it quickly?\n\n**Step 5 — Share one prompt** with a colleague who uses AI for similar work. Ask for their feedback — does the template work for them, or does it need adjustments?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build a Team Prompt Library', content: 'Scale your prompt work by creating shared templates your team can use — reducing inconsistency and getting everyone to the quality level of your best AI users.\n\n**Step 1 — Identify the 3 AI tasks your team does most often.** Things everyone does, where quality and consistency matter.\n\n**Step 2 — For each task**, gather examples of good and bad AI outputs your team has produced.\n\n**Step 3 — Build one "gold standard" template** per task — the prompt that reliably produces the quality you want.\n\n**Step 4 — Ask Claude:** *"I want to create a prompt template that will work for my whole team (not just me personally). Here is the task: [describe]. Here is my current template: [paste it]. What assumptions does this template make about the user that might not apply to others on my team? How should I modify it to be more universally usable?"*\n\n**Step 5 — Create a team document** with 3 templates and brief usage notes.\n\n**Step 6 — Share it with at least 2 colleagues** and get their feedback on whether the templates work for their specific situation.' },

    { type: 'quiz', question: 'You have a prompt template with the placeholder [AUDIENCE]. A colleague uses the template and writes "my team" in the placeholder. The output is not very good. What is the most likely issue?', options: ['The placeholder name is confusing', 'The placeholder is too vague — "my team" doesn\'t tell the AI anything specific about the audience', 'The template needs more placeholders', 'The AI doesn\'t understand workplace contexts'], correct: 1, explanation: '"My team" provides no actionable information — it doesn\'t tell Claude the audience\'s role, expertise level, what they care about, or how they will use the output. Good placeholder guidance would prompt the user to provide specifics: [AUDIENCE: describe their role, expertise level, and what decision or action they need to take after reading this]. The more specific the placeholder instruction, the better the output.' },

    { type: 'quiz', question: 'When is it NOT worth creating a prompt template?', options: ['For tasks you do more than once a week', 'For tasks where you always provide different context and the prompt has no repeating structure', 'For tasks involving sensitive information', 'For tasks where the output needs to be high quality'], correct: 1, explanation: 'Prompt templates deliver value when a task repeats with a consistent structure. If every instance of the task is completely different in context, audience, format, and constraints — nothing to templatise — a template adds overhead without benefit. Templates are best for tasks like "write a [type] for [audience] about [topic]" where the scaffold repeats but the content changes. For truly one-off tasks, write the prompt fresh.' }
  ]
},

'4-3': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop A — Terminal First Commands Drill', content: 'This 8-minute drill gets you comfortable in the terminal by running real commands — not a tutorial.\n\n**Step 1 — Open PowerShell** (Windows: search "PowerShell" in Start menu).\n\n**Step 2 — Find out where you are:**\n```powershell\nGet-Location\n# or shorthand:\npwd\n```\n\n**Step 3 — List what\'s here:**\n```powershell\nGet-ChildItem\n# or shorthand:\nls\n```\n\n**Step 4 — Navigate to your Desktop:**\n```powershell\ncd ~/Desktop\n```\nRun `ls` again. Do you see your desktop files?\n\n**Step 5 — Create a test folder:**\n```powershell\nmkdir ai-experiments\ncd ai-experiments\npwd\n```\n\n**Step 6 — Ask Claude.ai:** *"I just opened PowerShell for the first time. What are the 5 commands I will use most often? Give me one-line explanations and a real example of each."*\n\n**Step 7 — Clean up (optional):**\n```powershell\ncd ..\nRemove-Item ai-experiments\n```' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Use AI to Guide a Real Terminal Task', content: 'AI is your terminal co-pilot. This workshop shows the pattern: describe what you want, get the command, run it, report back.\n\n**Step 1 — Identify a real task** you would actually do in a terminal: installing a program, finding files, checking what\'s running, setting up a project folder.\n\n**Step 2 — Open Claude.ai** and ask (in your own words): *"I want to [describe your task] using PowerShell on Windows 11. Give me the exact commands, what each one does, and what the output will look like so I know it worked."*\n\n**Step 3 — Run the commands one at a time.** For each command:\n- Read Claude\'s explanation before running it\n- Run it\n- If the output doesn\'t match what Claude predicted, paste the actual output back and ask why\n\n**Step 4 — If you get an error**, paste the full error message to Claude and ask: "I got this error. What does it mean and how do I fix it?"\n\n**Step 5 — Complete your real task.** Note: AI + terminal is far more powerful than either alone. You don\'t need to memorise commands — you need to know how to describe what you want.' },

    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop C — File Navigation Challenge', content: 'This workshop builds fluency with the file system via terminal — a skill that pays off every time you use Claude Code.\n\n**Step 1 — Open PowerShell** and navigate to your Documents folder:\n```powershell\ncd ~/Documents\n```\n\n**Step 2 — Explore the structure:**\n```powershell\nls                      # see files and folders\nls -Name               # just the names\nls *.pdf               # only PDF files\n```\n\n**Step 3 — Find a specific file** you\'re looking for:\n```powershell\nGet-ChildItem -Recurse -Filter "*.txt"   # all txt files, in all subfolders\n```\n\n**Step 4 — Create a project structure:**\n```powershell\nmkdir my-first-project\ncd my-first-project\nmkdir src docs tests\nls\n```\n\n**Step 5 — Ask Claude:** *"Here is the folder structure I just created: [paste `ls` output]. I\'m going to build [describe your project]. What other folders or files should I create? Give me the exact PowerShell commands."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build a Terminal Command Reference Card', content: 'Create a personal reference card for terminal commands you actually use.\n\n**Step 1 — Ask Claude:** *"Create a PowerShell command reference card for a beginner who is setting up their first development environment on Windows. Include: navigation, file operations, checking what\'s installed, installing packages with winget, and basic git commands. Format it as a table: Command | What it does | Example output."*\n\n**Step 2 — Review the reference card.** Remove any commands that aren\'t relevant to your work. Add any that are.\n\n**Step 3 — Test every command** in the card to confirm they work on your system.\n\n**Step 4 — Save the reference card** in a format you can quickly access: a text file on your Desktop, a note in your phone, a pinned tab.\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review this reference card. What important commands are missing for someone setting up a [your specific development context]? What commands on the card might cause problems if used incorrectly?"*' },

    { type: 'quiz', question: 'You run a command in PowerShell and get an error that says "the term \'npm\' is not recognized." What should you do first?', options: ['Restart PowerShell and try again', 'Check if Node.js is installed — npm comes with Node.js, and if Node isn\'t installed, npm won\'t be recognised', 'Install PowerShell again', 'Use Command Prompt instead of PowerShell'], correct: 1, explanation: 'The error "term is not recognized" in PowerShell means the command doesn\'t exist in your system\'s PATH — it\'s not installed or not accessible. npm is part of Node.js, so this error means Node.js isn\'t installed. The fix is to install Node.js from nodejs.org. PowerShell and CMD are not the issue — it\'s a missing software installation.' },

    { type: 'quiz', question: 'You are about to run a command you found online. Before running it, what should you always do?', options: ['Run it first, then check if anything bad happened', 'Understand what the command does — ask Claude or check the documentation — especially if it has destructive flags like -rf or --force', 'Copy it exactly as written without modification', 'Only run it if the source website looks official'], correct: 1, explanation: 'Never run a terminal command you don\'t understand, especially commands with flags like -rf (recursive force delete), --force, or DROP in database commands. These can cause irreversible data loss. Before running any unfamiliar command, paste it into Claude and ask "What does this command do? Is it safe to run? Are there any risks?" This takes 30 seconds and can save hours of recovery work.' }
  ]
},

'4-4': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop A — Essential Commands Speed Test', content: 'This 8-minute drill verifies you can use the most important terminal commands fluently.\n\n**Step 1 — Open PowerShell.** Time yourself on each task below. Aim for under 30 seconds per task.\n\n**Task 1:** Find your current directory and list its contents.\n\n**Task 2:** Create a folder called `workshop-test` on your Desktop and navigate into it.\n\n**Task 3:** Create a file called `notes.txt` inside the folder:\n```powershell\nnew-item notes.txt\n```\n\n**Task 4:** Show the contents of the folder including hidden files:\n```powershell\nls -Force\n```\n\n**Task 5:** Check what version of Python (or Node.js) is installed:\n```powershell\npython --version\nnode --version\n```\n\n**Task 6:** Navigate back to your home directory in one command.\n\n**Task 7:** Delete the test folder:\n```powershell\nRemove-Item ~/Desktop/workshop-test -Recurse\n```\n\n**Step 2 — Which task took longest?** That\'s the command to practice more.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — AI-Assisted Setup Task', content: 'Use AI to help you complete a real terminal setup task — installing or configuring something you actually need.\n\n**Step 1 — Choose a real setup task** you\'ve been putting off: installing a development tool, setting up a project folder, configuring git, installing a package manager.\n\n**Step 2 — Ask Claude:** *"Help me [describe your setup task] on Windows 11 using PowerShell. Give me the complete steps in order, the exact commands, what each command does, and how to verify it worked. Tell me what to do if I get an error."*\n\n**Step 3 — Follow Claude\'s steps one at a time.** Don\'t run everything at once — run each command, check the output, then move to the next.\n\n**Step 4 — When you hit an error** (you probably will), paste the exact error text back to Claude. Ask: "I got this error: [paste error]. What caused it and how do I fix it?"\n\n**Step 5 — Verify the installation worked** using the verification command Claude gave you.\n\n**Step 6 — Document what you did.** Write a short note: what you installed, the command that worked, and how to verify it. Future you will thank you.' },

    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop C — Git Basics in the Terminal', content: 'Git is the version control system used by nearly every software project. Even non-coders use it. This workshop gets you started.\n\n**Step 1 — Check if git is installed:**\n```powershell\ngit --version\n```\nIf not installed: visit git-scm.com and install.\n\n**Step 2 — Configure git** (one-time setup):\n```powershell\ngit config --global user.name "Your Name"\ngit config --global user.email "your.email@example.com"\n```\n\n**Step 3 — Create a test repository:**\n```powershell\nmkdir git-test\ncd git-test\ngit init\n```\n\n**Step 4 — Make your first commit:**\n```powershell\nnew-item README.txt\n"Hello from git" | Out-File README.txt\ngit add README.txt\ngit commit -m "My first commit"\n```\n\n**Step 5 — View the history:**\n```powershell\ngit log\ngit status\n```\n\n**Step 6 — Ask Claude:** *"I just made my first git commit. Explain what git status and git log show me. What are the 5 git commands I should learn next, and what does each do?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build a Shell Script for a Repeated Task', content: 'A shell script is a file of commands that run automatically. This workshop creates your first one.\n\n**Step 1 — Identify a sequence of terminal commands** you run together repeatedly: setting up a project, starting a development server, doing a backup, running tests.\n\n**Step 2 — Ask Claude:** *"I want to create a PowerShell script that does: [describe the sequence of commands]. Write the complete script, explain each line, and tell me how to run it."*\n\n**Step 3 — Review the script** Claude provides. Do you understand what each line does? If not, ask Claude to explain specific lines.\n\n**Step 4 — Save the script:**\n```powershell\nnew-item my-setup.ps1\n# paste Claude\'s script content into the file\n```\n\n**Step 5 — Run the script:**\n```powershell\n.\\my-setup.ps1\n```\n\n**Step 6 — If it fails**, paste the error to Claude. Ask for the fix.\n\n**Step 7 — Add the script to a folder in your PATH** so you can run it from anywhere.' },

    { type: 'quiz', question: 'You run `git commit -m "fixes"` and then realise you made a typo in a file. What is the safest approach to fix it?', options: ['Run git commit --amend to change the last commit', 'Fix the file, then run git add and git commit with a new message like "fix typo from previous commit"', 'Delete the git repository and start over', 'The commit is permanent — you cannot change it'], correct: 1, explanation: 'The safest fix is to make a new commit: fix the file, stage the change with git add, and commit with a descriptive message. Git commit --amend (A) can work but rewrites history, which causes problems if others have already pulled the original commit. Never amend published commits. Creating a correction commit keeps history intact and is standard practice.' },

    { type: 'quiz', question: 'What does `git status` tell you that `git log` does not?', options: ['git status shows the full commit history; git log shows only the latest commit', 'git status shows the current state of files (staged, modified, untracked); git log shows the history of past commits', 'git status shows remote repository information; git log shows local changes', 'They show the same information in different formats'], correct: 1, explanation: 'git status answers "what is happening right now?" — it shows which files have changed since the last commit, which changes are staged for the next commit, and which files are new/untracked. git log answers "what happened in the past?" — it shows the history of previous commits with messages and timestamps. Both are essential; use status constantly (before every add/commit) and log when you need to understand history.' }
  ]
},

'4-5': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Code Reading Drill', content: 'This 8-minute drill builds your ability to read code without running it — an essential skill for working with AI-generated code.\n\n**Step 1 — Ask Claude** to write a short program (15-20 lines) in Python or JavaScript that does something simple: calculate a tip, convert temperatures, count words in text.\n\n**Step 2 — Before running it**, read through it line by line and write:\n- What does line 1 do?\n- What does the function do overall?\n- What will the output be?\n\n**Step 3 — Ask Claude** to explain each line in plain English, as if you\'ve never seen code before.\n\n**Step 4 — Compare your guesses** to Claude\'s explanations. What did you understand correctly? What surprised you?\n\n**Step 5 — Change one thing**: Ask Claude, "If I change [specific line] to [something different], what will happen?" Try to predict the answer before Claude responds.\n\n**Step 6 — Reflect:** Code reading is a skill that improves with practice. The goal isn\'t to write code — it\'s to understand it well enough to verify that AI-generated code does what you intended.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Ask AI to Build You Something Real', content: 'Use AI to build a small, genuinely useful program — no coding knowledge required. You\'ll describe what you want and guide the AI through the build.\n\n**Step 1 — Choose a small automation idea** — something you do manually that a program could do: renaming a batch of files, converting a CSV to a different format, calculating something repeatedly, generating a formatted report from data.\n\n**Step 2 — Ask Claude:** *"I want to build a Python script that does: [describe your task in plain English]. I am not a programmer. Please: (1) write the complete script, (2) explain what each section does, (3) tell me exactly how to run it, (4) tell me what to do if I get an error."*\n\n**Step 3 — Save the script** Claude gives you to a file: `my-tool.py`.\n\n**Step 4 — Run the script** following Claude\'s instructions.\n\n**Step 5 — If it fails**, paste the full error to Claude and ask for the fix.\n\n**Step 6 — Mandatory code review:** Ask Claude: *"Review this code you just wrote. Find 3 potential problems: places where it could fail, produce wrong output, or could be improved. Then fix each one."*\n\n**Step 7 — Use the finished tool** for its intended purpose at least once.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Code Concepts in Plain English', content: 'This workshop builds your mental model of how code works — essential for guiding AI code generation.\n\n**Step 1 — Ask Claude to explain each concept** in one paragraph, using an analogy from real life:\n- Variables\n- Functions\n- Loops\n- Conditions (if/else)\n- Lists/arrays\n\n**Step 2 — For each concept**, ask Claude to show a minimal example in Python (3-5 lines). Read each example and confirm you understand how the explanation maps to the code.\n\n**Step 3 — Ask Claude to show how these concepts combine** in a small 20-line program.\n\n**Step 4 — Test your understanding:** Cover up the explanations and try to describe what each line does in the combined example, in your own words.\n\n**Step 5 — Ask:** *"A common problem people have when asking AI to write code is that they don\'t describe what they want precisely enough. What information should I always give AI when asking it to write a program? Give me a template."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build a Program Specification', content: 'The most important skill for non-programmers working with AI code is writing a clear specification — a description of what you want the program to do. This workshop builds that skill.\n\n**Step 1 — Choose any small program idea** from your work or life.\n\n**Step 2 — Write a specification** using this template:\n```\nProgram name: [name]\nWhat it does: [one sentence]\n\nInputs (what the user provides):\n- [input 1, type, example value]\n- [input 2, type, example value]\n\nOutputs (what it produces):\n- [output 1, format, example]\n\nEdge cases (what should happen when):\n- If input is empty: [behaviour]\n- If input is wrong type: [behaviour]\n- If no results found: [behaviour]\n\nExample run:\nUser enters: [example input]\nProgram outputs: [example output]\n```\n\n**Step 3 — Ask Claude to review your spec:** *"Review this program specification. What is ambiguous? What edge cases have I missed? What would cause a programmer to implement this incorrectly?"*\n\n**Step 4 — Improve the spec** based on Claude\'s feedback.\n\n**Step 5 — Ask Claude to build the program** using your improved spec. Compare how much better the code is when given a precise specification vs a vague description.' },

    { type: 'quiz', question: 'Claude writes a 50-line Python script for you. Before running it, what is the most important check?', options: ['Verify the code compiles without errors by running it', 'Read through the code and confirm it does what you intended — look for obvious logic errors or misunderstood requirements', 'Count the number of lines to make sure it\'s complete', 'Check that the variable names are clear'], correct: 1, explanation: 'Before running any AI-generated code, read through it and verify it does what you intended. AI often makes subtle logical mistakes — handling edge cases incorrectly, misinterpreting requirements, or implementing the right idea in the wrong order. Catching these before running is faster than debugging after. Ask: "Does this code actually solve my specific problem, or does it solve a slightly different problem?"' },

    { type: 'quiz', question: 'What does a programming variable do?', options: ['It checks if a condition is true or false', 'It repeats a block of code multiple times', 'It stores a piece of information with a name so you can use it later', 'It defines the overall structure of a program'], correct: 2, explanation: 'A variable is a named storage location for a value. Like a labelled box: `age = 25` puts the number 25 in a box labelled "age", and you can retrieve it later just by writing "age". Variables make code readable and flexible — instead of writing the number 25 everywhere, you write "age" and can change the value in one place. If/else checks conditions (A), loops repeat code (B), and functions define reusable procedures.' }
  ]
},

'4-6': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BUILD', title: 'Workshop A — Add a Page to Your HTML File', content: 'This drill extends the HTML file you created in the lesson — turning it into a real two-page site.\n\n**Step 1 — Open your index.html** from the lesson in a text editor (Notepad or VS Code).\n\n**Step 2 — Add a new page.** Create a second file called `about.html` in the same folder with this structure:\n```html\n<!DOCTYPE html>\n<html>\n<head>\n    <title>About — My First Site</title>\n</head>\n<body>\n    <h1>About This Site</h1>\n    <p>Write a sentence about yourself or this project here.</p>\n    <a href="index.html">Back to Home</a>\n</body>\n</html>\n```\n\n**Step 3 — Link the pages together.** In index.html, add a link to about.html:\n```html\n<a href="about.html">About</a>\n```\n\n**Step 4 — Test it.** Open index.html in a browser. Click your new link. Does it navigate to about.html?\n\n**Step 5 — Ask Claude:** *"I have an index.html and about.html that link to each other. What are the next 3 things I should add to make this look like a real website?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — AI-Built Web Page for a Real Use Case', content: 'Use AI to build a real HTML page you will actually use — not a practice exercise.\n\n**Step 1 — Choose a real purpose** for a web page: a personal portfolio, a project landing page, a cheat sheet, an event invitation, a simple dashboard.\n\n**Step 2 — Describe it to Claude:**\n```\nI want to create a single HTML page (no frameworks, just plain HTML and inline CSS) for: [describe your use case]\n\nIt should include:\n- [list the sections you want]\n- [any specific content]\n- [any styling preferences — colours, fonts, layout]\n\nMake it look professional. Include all the HTML in one complete file I can save and open in a browser.\n```\n\n**Step 3 — Save the HTML** Claude gives you to a file and open it in a browser.\n\n**Step 4 — Request targeted improvements:**\n- "The header looks too plain — make it have a coloured background"\n- "Add a contact section at the bottom"\n- "Make it work better on mobile"\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review this HTML you just wrote. Find 3 specific problems: accessibility issues, layout problems on small screens, or missing elements that a professional web developer would add."* Fix at least 2 issues.\n\n**Step 6 — This page is yours.** Keep it and show it to someone.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — HTML Debugging with AI', content: 'When HTML breaks, knowing how to get AI to fix it is more valuable than knowing every HTML tag.\n\n**Step 1 — Intentionally break your HTML** by removing a closing tag (remove `</p>` or `</div>`) or by making a typo in a link (`href` → `hrf`).\n\n**Step 2 — Open the broken file in a browser.** How does it look? Does the browser show an error or just silently break the layout?\n\n**Step 3 — Paste the broken HTML to Claude** and ask: *"This HTML isn\'t rendering correctly. Find all the errors and fix them. Explain what each error was and why it caused the problem it did."*\n\n**Step 4 — Compare** Claude\'s fixed version to your original. Did Claude find the error you introduced? Did it find any other issues?\n\n**Step 5 — Use browser DevTools:** Press F12 in your browser. Click the Elements tab. This shows you the actual HTML the browser is rendering — different from what you wrote if there are errors.\n\n**Step 6 — Learn the rule:** Right-click any element on any webpage → Inspect Element. You can see the HTML of any website. This is how web developers learn — by reading real HTML from real sites.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Add CSS Styling to Your Site', content: 'Your HTML site works — now make it look good. CSS controls appearance: colours, fonts, layout, spacing.\n\n**Step 1 — Open index.html** in a text editor.\n\n**Step 2 — Ask Claude to add professional styling:**\n```\nI have this HTML file: [paste it]\n\nAdd CSS styling to make it look professional. Requirements:\n- A clean, modern font (use Google Fonts or system fonts)\n- A colour scheme with a primary and secondary colour\n- Proper spacing and margins\n- The links should look like buttons, not plain text\n- It should look good on both desktop and mobile\n\nAdd all CSS inside a <style> tag in the <head>. Give me the complete updated file.\n```\n\n**Step 3 — Save and open** the updated file. Does it look how you wanted?\n\n**Step 4 — Make one specific change** yourself: find the colour code in the CSS (like `#3498db`) and change it to a different colour. See the effect immediately by refreshing the browser.\n\n**Step 5 — Share your finished site** with someone — even just as a screenshot. You built a real webpage.' },

    { type: 'quiz', question: 'You open your HTML file in a browser and the page looks completely blank. Claude suggests checking for unclosed tags. What does this mean?', options: ['A file was not saved properly', 'A tag that was opened with <tag> was never closed with </tag>, causing the browser to not know where the element ends', 'The file extension is wrong', 'The browser doesn\'t support this HTML version'], correct: 1, explanation: 'HTML uses paired tags: <p> opens and </p> closes. If you open a tag and never close it, the browser often treats everything that follows as being inside that element — which can make content invisible, unformatted, or displaced. For example, forgetting to close a <style> tag causes the browser to interpret all your page content as CSS. Always check that every opening tag has a matching closing tag.' },

    { type: 'quiz', question: 'What is the difference between HTML and CSS?', options: ['HTML is for websites, CSS is for apps', 'HTML defines the content and structure (what is on the page); CSS defines the appearance (how it looks)', 'HTML is older and CSS replaced it', 'They are two names for the same technology'], correct: 1, explanation: 'HTML (HyperText Markup Language) defines structure and content — headings, paragraphs, links, images, lists. CSS (Cascading Style Sheets) controls visual presentation — colours, fonts, spacing, layout, animations. They work together: HTML is the skeleton, CSS is the skin and clothing. You can change a page\'s entire visual design by changing only CSS, without touching the HTML content.' }
  ]
}

};

function enhance(id, filePath) {
  const raw = fs.readFileSync(filePath, 'utf8');
  const lesson = JSON.parse(raw);
  const enh = enhancements[id];
  if (!enh) { console.log('SKIP '+id+' — no enhancement defined'); return; }

  let successIdx = -1;
  for (let i = lesson.sections.length - 1; i >= 0; i--) {
    if (lesson.sections[i].type === 'callout' && lesson.sections[i].variant === 'success') {
      successIdx = i; break;
    }
  }
  const insertAt = successIdx >= 0 ? successIdx : lesson.sections.length;
  lesson.sections.splice(insertAt, 0, ...enh.sections);
  lesson.estimatedMinutes += enh.addMinutes;
  fs.writeFileSync(filePath, JSON.stringify(lesson, null, 2));
  const ws = lesson.sections.filter(s=>s.type==='workshop').length;
  const qz = lesson.sections.filter(s=>s.type==='quiz').length;
  console.log('OK '+id+' | workshops:'+ws+' quizzes:'+qz+' mins:'+lesson.estimatedMinutes);
}

const lessons = [
  ['3-3','data/lessons/part-03/3-3.json'],
  ['3-4','data/lessons/part-03/3-4.json'],
  ['3-5','data/lessons/part-03/3-5.json'],
  ['3-6','data/lessons/part-03/3-6.json'],
  ['3-7','data/lessons/part-03/3-7.json'],
  ['3-8','data/lessons/part-03/3-8.json'],
  ['4-3','data/lessons/part-04/4-3.json'],
  ['4-4','data/lessons/part-04/4-4.json'],
  ['4-5','data/lessons/part-04/4-5.json'],
  ['4-6','data/lessons/part-04/4-6.json'],
];

lessons.forEach(([id, rel]) => {
  try { enhance(id, 'C:/Projects/Learning/'+rel); }
  catch(e) { console.log('FAIL '+id+': '+e.message); }
});
