const fs = require('fs');

const enhancements = {

'15-2': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Perplexity vs Claude Research Drill', content: 'Run the same research question through both tools and compare.\n\n**Step 1 — Choose a research question** you actually need answered: a technical comparison, a current events question, or a market research question.\n\n**Step 2 — Run in Perplexity first.** Note: sources cited, confidence level, recency of information.\n\n**Step 3 — Run the same question in Claude.** Note: depth of analysis, knowledge cutoff limitations, no source citations.\n\n**Step 4 — Compare the outputs:**\n| Dimension | Perplexity | Claude |\n|---|---|---|\n| Source quality | | |\n| Recency | | |\n| Depth of analysis | | |\n| Accuracy (verifiable claims) | | |\n\n**Step 5 — Ask Claude:** "For research tasks like [your question], when should I use Perplexity vs Claude vs both together?"' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Multi-Source Research on a Real Topic', content: 'Conduct thorough research on a topic you actually need to know about.\n\n**Step 1 — Choose a real research topic** from your work: a technology decision, a competitor analysis, a policy question.\n\n**Step 2 — Layer the research tools:**\n- Start with Perplexity for current, sourced information\n- Then Claude for deep analysis and synthesis\n- Then ask Claude to identify gaps: "What important aspects of this topic did neither of us cover adequately?"\n\n**Step 3 — Build a research brief** as you go:\n```\n## [Topic]\n### Key Facts (with sources)\n### Analysis & Implications\n### Gaps & Uncertainties\n### Recommended Actions\n```\n\n**Step 4 — Verify 3 specific claims** from your research by checking primary sources.\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review this research brief. What claims should I be most skeptical of? What would a domain expert challenge?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Source Verification Workflow', content: 'Build rigorous source verification habits into your AI research.\n\n**Step 1 — Take any Perplexity research result** with 5+ sources.\n\n**Step 2 — Verify each source:**\n- Does the source actually say what Perplexity claims it says?\n- Is the source authoritative (academic journal, official report, expert)?  \n- Is it recent enough to be relevant?\n- Does it have a potential bias or conflict of interest?\n\n**Step 3 — Rate each source (1-5)** for credibility and relevance.\n\n**Step 4 — Ask Claude:** "I found that [source X] doesn\'t actually support the claim Perplexity attributed to it. What does this tell me about AI research tools? How should I use them differently?"' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Research Template Library', content: 'Build a library of research prompt templates for your most common research types.\n\n**Step 1 — Identify your 3 most common research types:** technology evaluation, competitive analysis, policy/regulatory research, market research, academic literature review.\n\n**Step 2 — For each type**, create a research template:\n```\n# Technology Evaluation Template\n\n## Perplexity queries:\n1. "[Technology] current adoption and use cases 2025"\n2. "[Technology] limitations and failure cases"\n3. "[Technology] vs [alternative] comparison"\n\n## Claude synthesis prompt:\n"Based on this research about [technology]: [paste Perplexity results]\nProvide: executive summary, key trade-offs, recommendation for [your context], top 3 risks."\n\n## Verification checklist:\n- [ ] Cross-check vendor claims with independent sources\n- [ ] Check recency (is this still current?)\n- [ ] Identify who benefits from this narrative\n```\n\n**Step 3 — Test each template** on a real research question.\n\n**Step 4 — Save to your prompt library** and share with your team.' },

    { type: 'quiz', question: 'Perplexity cites 8 sources for a claim about market size. You check 3 of them and find they all cite the same original report. What is the problem?', options: ['No problem — multiple citations increase credibility', 'Citation laundering: 8 sources appear to corroborate the claim but they all trace to a single original source — the actual evidence base is just one study, not eight', 'The market size is wrong', 'Perplexity is duplicating sources incorrectly'], correct: 1, explanation: 'When multiple sources all reference the same original study, this creates false confidence. Eight citations that all say "as reported by Market Research Firm X" is really one data point. Evaluate the original source: how was the study conducted, who funded it, what is the sample size and methodology? A single market research report (especially one funded by industry) is much weaker evidence than eight independent studies reaching the same conclusion.' },

    { type: 'quiz', question: 'Claude\'s training data has a cutoff in mid-2025 and it\'s now June 2026. You ask Claude about the latest AI models. What is the risk and how do you mitigate it?', options: ['No risk — Claude knows it should be humble about recent events', 'Claude may confidently describe models from before its cutoff as "the latest" without knowing about more recent releases — use Perplexity for current AI news, then Claude for analysis', 'Claude automatically updates its knowledge via the internet', 'Ask Claude to only discuss models it is certain about'], correct: 1, explanation: 'Knowledge cutoff is a real limitation. Claude doesn\'t always know what it doesn\'t know — it may describe a 2024 model as "state of the art" without realising newer models were released in 2025-2026. For rapidly evolving fields (AI models, software frameworks, regulations), always supplement Claude\'s analysis with Perplexity or direct source research for anything requiring current information.' }
  ]
},

'15-3': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — AI Web Search Tools Comparison', content: 'Test 3 AI web search tools on the same query.\n\n**Step 1 — Choose a research question** with a factual answer that can be verified.\n\n**Step 2 — Run the same question** through:\n- Perplexity (perplexity.ai)\n- Claude with web search enabled (if available)\n- Bing Copilot or another AI search tool\n\n**Step 3 — Compare results:**\n- Which found the most relevant sources?\n- Which had the most accurate synthesis?\n- Which cited sources most reliably?\n- Which had the freshest information?\n\n**Step 4 — Identify the winner** for your use case and explain why.\n\n**Step 5 — Ask Claude:** "For different types of web research tasks, which AI search tool performs best? Give specific examples."' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Web Crawling for Research', content: 'Use AI to systematically crawl and extract information from multiple web pages.\n\n**Step 1 — Identify a research task** that requires information from 5-10 specific URLs: comparing product specs, collecting pricing, reviewing documentation.\n\n**Step 2 — Ask Claude Code** (with Browser MCP if available) to extract structured data:\n```\nVisit each of these URLs and extract [specific data]:\n[List 5-10 URLs]\n\nFor each page, extract:\n- [Field 1]: [where to find it]\n- [Field 2]: [where to find it]\n\nFormat as a comparison table.\n```\n\n**Step 3 — Verify a sample** of the extracted data against the actual pages.\n\n**Step 4 — Save the extracted data** in a structured format (CSV or JSON).\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review the extracted data. Which extractions are most likely to be inaccurate or missing important context?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Research Credibility Assessment', content: 'Build a systematic approach to evaluating the credibility of AI-found web sources.\n\n**Step 1 — Ask Claude:** "Create a 10-point credibility checklist for evaluating web sources found by AI search tools. Include: author credentials, publication date, site reputation, potential bias, and methodology."\n\n**Step 2 — Apply the checklist** to 5 sources from a recent Perplexity research session.\n\n**Step 3 — Score each source (0-10)** on the credibility checklist.\n\n**Step 4 — Identify the pattern:** Were low-credibility sources driving specific claims in the research? Would removing them change the conclusions?\n\n**Step 5 — Update your research workflow** to automatically flag low-credibility sources.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build a Research Dashboard', content: 'Create a personal research tracking dashboard.\n\n**Step 1 — Ask Claude Code** to design a simple research tracking system:\n```\nCreate a Markdown-based research tracking system:\n1. research-index.md: list of all research topics with status and date\n2. Template for each research topic: question, sources found, key findings, verification status, confidence level\n3. A summary generator that reads all research files and produces a weekly digest\n\nKeep it simple — no database, just markdown files.\n```\n\n**Step 2 — Set up the system** and add your 3 most recent research topics.\n\n**Step 3 — Generate a weekly digest** of your research activity.\n\n**Step 4 — Ask Claude:** "Is this research tracking system appropriate for my research volume and complexity? What would make it more useful?"' },

    { type: 'quiz', question: 'You use AI web search to research a competitor\'s product and find a very positive review on a reputable tech blog. Before including this in your analysis, what should you check?', options: ['Nothing — reputable tech blogs are always reliable', 'Whether the review was sponsored or the blogger has a financial relationship with the company — even reputable outlets publish sponsored content that may not be disclosed prominently', 'Whether the blog has more than 100,000 readers', 'Whether the product is still available'], correct: 1, explanation: 'Sponsored content on tech blogs is common and not always prominently disclosed. Check: look for "sponsored," "partner," or "paid promotion" labels, check the blog\'s disclosure policy, look for unusual positivity or absence of critical feedback, and search for independent reviews of the same product. AI search tools don\'t filter for sponsored content, so a positive review on a "reputable" site might still be a paid placement.' },

    { type: 'quiz', question: 'AI web search returns results from 2022 about a rapidly evolving technology. How should you handle this research?', options: ['Use the 2022 information — it\'s probably still accurate', 'Flag all 2022 findings as potentially outdated and search specifically for recent sources: add "2025" or "2026" to your queries, and look for version-specific documentation', 'Discard the search and use Claude\'s knowledge instead', 'Use the 2022 results only for background context, not current recommendations'], correct: 3, explanation: 'For rapidly evolving technologies, older sources serve as context, not current guidance. A 2022 article about a JavaScript framework might describe an API that was completely changed in 2024. Workflow: use older sources to understand the history and foundational concepts, then explicitly search for recent sources ("after:2025" in search queries) for current best practices, APIs, and recommendations. Be explicit with Claude when passing research: "This source is from 2022 — the current state may differ."' }
  ]
},

'15-4': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Document Extraction Drill', content: 'Extract structured information from a complex document.\n\n**Step 1 — Find a dense document** relevant to your work: a research paper, a technical specification, a lengthy report.\n\n**Step 2 — Upload to Claude** and ask for structured extraction:\n```\nExtract the following from this document:\n1. Main thesis or conclusion (1-2 sentences)\n2. Key findings (bullet points, with page/section reference)\n3. Methodology (how was this research/analysis conducted?)\n4. Data sources used\n5. Limitations acknowledged by the authors\n6. Recommendations made\n7. What this document does NOT address that I might expect it to\n```\n\n**Step 3 — Verify 3 specific extractions** against the original document.\n\n**Step 4 — Ask Claude:** "What did you struggle to extract from this document? What information was ambiguous or missing?"' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Multi-Document Synthesis', content: 'Synthesise information across multiple documents.\n\n**Step 1 — Gather 3-5 documents** on the same topic (research papers, reports, articles).\n\n**Step 2 — Process each document** with Claude, extracting key points in a consistent format.\n\n**Step 3 — Ask Claude to synthesise across documents:**\n```\nI have extracted key points from [N] documents on [topic]:\n\nDocument 1: [paste extraction]\nDocument 2: [paste extraction]\n...\n\nSynthesise these sources:\n1. What do all documents agree on? (consensus findings)\n2. Where do they disagree? (conflicting findings)\n3. What does each source add that others don\'t cover?\n4. What is the overall weight of evidence for the key claims?\n5. What questions do these documents collectively fail to answer?\n```\n\n**Step 4 — Mandatory review:** Ask Claude: *"In your synthesis, which conclusions are most supported by the evidence? Which are most speculative?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — PDF Limitation Awareness', content: 'Understand when AI PDF processing fails and how to detect it.\n\n**Step 1 — Test AI PDF extraction** with a challenging document:\n- A scanned PDF (image-based, not text)\n- A document with complex tables or charts\n- A document with footnotes or endnotes\n- A multi-column academic paper\n\n**Step 2 — For each type**, evaluate:\n- Did the extraction get the tables correctly?\n- Were footnotes included or lost?\n- Did multi-column text get scrambled?\n- Were charts and figures described or ignored?\n\n**Step 3 — Ask Claude:** "What types of PDF content are most likely to be misextracted? How do I verify extraction accuracy for these challenging types?"\n\n**Step 4 — Develop your verification protocol** for each document type you commonly work with.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Document Analysis Pipeline', content: 'Build a repeatable document analysis pipeline.\n\n**Step 1 — Ask Claude Code** to create a document analysis pipeline script:\n```\nWrite a Python script that creates a document analysis pipeline:\n1. Accepts a folder of PDFs as input\n2. For each PDF:\n   a. Extract text (using PyPDF2 or pdfplumber)\n   b. Send to Anthropic API for structured analysis\n   c. Save the structured output as a JSON file\n3. After all PDFs: generate a synthesis report combining key findings\n4. Create an index file listing all documents and their key themes\n\nHandle errors gracefully: skip unreadable PDFs, log failures.\n```\n\n**Step 2 — Test on a folder of documents** from a real research project.\n\n**Step 3 — Verify the output quality** against one document you\'ve read manually.\n\n**Step 4 — Mandatory review:** Ask Claude: *"What types of content in these documents would the pipeline extract incorrectly? What manual review is still needed?"*' },

    { type: 'quiz', question: 'You upload a 50-page PDF to Claude and ask about a specific statistic. Claude gives you a number that seems wrong. What is the most likely cause?', options: ['Claude made up the number', 'PDF extraction may have misread numbers (especially from tables or charts), or Claude confused similar statistics from different sections — verify directly in the document', 'The PDF is encrypted', 'Claude cannot process PDFs correctly'], correct: 1, explanation: 'PDF number extraction errors are common: tables format numbers in ways that confuse parsers, footnote references get merged with numbers, and similar statistics in close proximity get confused. Always verify specific numbers from PDF extraction against the original document. For critical statistics, note the page number Claude references and check it directly. Never cite a number from AI document processing without verifying it in the source.' },

    { type: 'quiz', question: 'You need to extract data from 100 research PDFs. What is the most important quality check to implement in your pipeline?', options: ['Verify all 100 documents manually', 'Randomly sample 10% of outputs and verify them against the source PDFs — this gives statistical confidence without requiring 100% manual review', 'Only process documents under 10 pages', 'Run each document twice and compare outputs'], correct: 1, explanation: 'Statistical sampling provides quality assurance at scale. Randomly check 10-15% of outputs against source documents. If your sample shows 95%+ accuracy, you can use the full batch with confidence. If you find systematic errors (e.g., all table data is wrong), you can fix the pipeline and reprocess before using the data. This is standard quality assurance practice for any automated data processing pipeline.' }
  ]
},

'15-5': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Research Synthesis Drill', content: 'Practice synthesising research from multiple sources into a coherent picture.\n\n**Step 1 — Gather raw research** on a topic you\'re studying: paste in 3-5 search results, article excerpts, or document extractions.\n\n**Step 2 — Ask Claude to synthesise:**\n```\nHere is my raw research on [topic]:\n[paste research]\n\nSynthesise this into:\n1. The 3 most important insights (well-supported by multiple sources)\n2. Areas of uncertainty or disagreement between sources\n3. The single most actionable takeaway\n4. What I still need to research to have a complete picture\n```\n\n**Step 3 — Review the synthesis.** Is anything wrong or missing?\n\n**Step 4 — Ask Claude:** "Which of the 3 insights is most uncertain? What would it take to become more confident in it?"' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Personal Knowledge Management with AI', content: 'Build a system for storing and retrieving research over time.\n\n**Step 1 — Ask Claude Code to design a knowledge management system:**\n```\nDesign a simple, file-based personal knowledge system:\n1. Store research notes as markdown files in organized folders\n2. Each note has: topic, date, sources, key insights, confidence level, tags\n3. Search across all notes using grep/ripgrep\n4. Generate a topic summary by combining all notes on a topic\n5. Weekly: Claude reads all new notes and identifies connections between topics\n\nKeep it simple — no database, no special software needed.\n```\n\n**Step 2 — Set up the system** and add 5 recent research topics.\n\n**Step 3 — Test the topic summary feature.** Is it useful?\n\n**Step 4 — Commit to maintaining it** for 30 days, then evaluate.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Contradiction Detection', content: 'Use AI to identify contradictions in your research.\n\n**Step 1 — Compile research** on a topic where you suspect different sources might disagree.\n\n**Step 2 — Ask Claude to actively find contradictions:**\n```\nReview this research collection for contradictions:\n[paste research]\n\nIdentify:\n1. Direct contradictions: sources that make opposite claims\n2. Subtle contradictions: sources that use different definitions for the same term\n3. False agreements: sources that appear to agree but are actually measuring different things\n4. Missing context: claims that are true in some contexts but not in others\n```\n\n**Step 3 — Investigate each contradiction.** Which source is more credible? Are they measuring different things?\n\n**Step 4 — Update your synthesis** to accurately reflect the uncertainty.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Research to Action Plan', content: 'Convert research findings into a concrete action plan.\n\n**Step 1 — Take a completed research brief** from your recent work.\n\n**Step 2 — Ask Claude:**\n```\nBased on this research [paste it], generate an action plan:\n\n1. Decision: What decision does this research inform?\n2. Recommendation: What does the evidence suggest I should do?\n3. Confidence level: How confident are you? (High/Medium/Low) and why?\n4. Key uncertainties: What could change this recommendation?\n5. Actions: Specific steps I can take this week\n6. Monitoring: How will I know if the recommended action is working?\n```\n\n**Step 3 — Evaluate the action plan.** Does it correctly reflect your research? Is the confidence calibration right?\n\n**Step 4 — Execute the first action.** Did having the research-backed action plan make you more decisive?' },

    { type: 'quiz', question: 'You have research from 10 sources that all agree on a conclusion. Should you trust this consensus?', options: ['Yes — unanimous agreement across 10 sources is strong evidence', 'Check if the sources are truly independent — if they all cite the same study or share a common funding source, the apparent consensus may be manufactured rather than genuine', 'Only trust it if 7+ of the sources are peer-reviewed', 'Trust it for decisions but not for published claims'], correct: 1, explanation: 'Apparent consensus can be misleading when sources aren\'t independent. Common patterns: all sources citing one landmark study (making it look like 10 studies agree when it\'s really 1 study cited 10 times), industry-funded research dominating a topic, or a narrative that became "common knowledge" based on weak original evidence. True consensus requires independent replication by groups with different methods and no shared funding.' },

    { type: 'quiz', question: 'After research synthesis, Claude says "the evidence strongly suggests X." What does this actually mean in practice?', options: ['X is definitely true', 'Claude assessed the research it was given as pointing toward X — this is a statement about the evidence provided, not a guarantee of X being true', 'X is true with 95% probability', 'You should act on X without further verification'], correct: 1, explanation: '"Strongly suggests" reflects Claude\'s assessment of the evidence provided, not an objective truth claim. Limitations: the evidence Claude saw may be incomplete (not all research on the topic), Claude may have weighted sources incorrectly, and "strongly suggests" in AI language doesn\'t map to a precise probability. For decisions with significant consequences, treat "strongly suggests" as a starting point for further verification, not a conclusion.' }
  ]
},

'15-6': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Report Structure Design', content: 'Design the structure of a research report before writing it.\n\n**Step 1 — Ask Claude:** "I need to write a research report on [your topic] for [your audience: executives, technical peers, general readers]. What is the optimal structure? How long should each section be? What should the executive summary contain?"\n\n**Step 2 — Review the proposed structure.** Does it match how your audience thinks about this topic?\n\n**Step 3 — Ask Claude to design the data visualisation plan:**\n"For each section of this report, what data should be visualised? What type of chart or table would communicate each finding most effectively?"\n\n**Step 4 — Compare your planned structure to a strong example:** Ask Claude to describe the structure of a well-regarded report in your field.\n\n**Step 5 — Finalise your structure** and start with the executive summary.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Draft a Full Research Report', content: 'Write a complete research report with AI assistance.\n\n**Step 1 — Choose a real research topic** you need to report on.\n\n**Step 2 — Feed your research** to Claude and ask it to draft section by section:\n```\nWrite the [Executive Summary / Introduction / Findings / Conclusion] of a research report on [topic].\n\nAudience: [who will read this]\nKey findings to cover: [list them from your research]\nTone: [formal/professional/accessible]\nLength: [target word count for this section]\n\nBase the content on this research: [paste your research notes]\n```\n\n**Step 3 — Review each section carefully** before accepting it — you are the researcher, not the AI.\n\n**Step 4 — Edit for accuracy:** Any fact that came from your research should be verifiable. Any claim you can\'t source should be either sourced or removed.\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review this draft report. What claims are not well-supported? What important nuance did the draft miss?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Report Editing with AI', content: 'Use AI to improve the quality of your draft report.\n\n**Step 1 — Take the draft from Workshop B.**\n\n**Step 2 — Run three separate editing passes with Claude:**\n\n**Pass 1 — Clarity:** "Edit this report section for clarity. Identify any sentences that are unnecessarily complex, use jargon without definition, or could be misunderstood by a non-expert reader."\n\n**Pass 2 — Logic:** "Review the logical flow of this report. Does each paragraph follow from the previous? Are the conclusions supported by the evidence presented? Flag any logical leaps."\n\n**Pass 3 — Completeness:** "Review this report for completeness. What important questions would a reader have that this report doesn\'t answer? What\'s missing?"\n\n**Step 3 — Apply the improvements** from all three passes.\n\n**Step 4 — Ask a human reader** to review one section. What do they find unclear or missing that the AI didn\'t catch?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Report Template Library', content: 'Build a library of report templates for your most common report types.\n\n**Step 1 — Identify your 3 most common report types:** executive briefings, technical specifications, project status reports, competitive analyses.\n\n**Step 2 — For each type**, ask Claude to create a template:\n```\nCreate a template for a [report type] that I can reuse. Include:\n- Document structure with section headings\n- Guidance on what to include in each section\n- Word count targets for each section\n- Formatting standards (headers, tables, bullet points)\n- A cover page template\n- Example executive summary for this report type\n```\n\n**Step 3 — Test each template** by filling in one section with real content.\n\n**Step 4 — Save to your Claude Projects** or a shared folder so the templates are always available.\n\n**Step 5 — Share with colleagues** who write similar reports — standardised templates improve team communication.' },

    { type: 'quiz', question: 'Claude drafts an executive summary that is factually accurate but buries the most important finding in the third paragraph. What should you do?', options: ['Accept it — the finding is there even if not prominent', 'Restructure the executive summary: lead with the most critical finding, use the "inverted pyramid" approach — most important information first', 'Ask Claude to make it longer so the finding appears more times', 'Add bold formatting to the buried finding'], correct: 1, explanation: 'AI drafts often produce well-structured, logically ordered content that buries the lead. Executives and busy readers form opinions based on the first two sentences. The inverted pyramid rule: start with the most important finding/recommendation, then provide supporting evidence, then background context. Ask Claude: "Restructure this executive summary so the most important finding is in the first two sentences." Then verify the restructuring hasn\'t lost accuracy.' },

    { type: 'quiz', question: 'You write a research report with AI assistance. A colleague points out that one of your main conclusions is contradicted by a recent paper they know about. What is the best response?', options: ['Defend your conclusion — your research supported it', 'Thank them, obtain the paper, evaluate it honestly, and update your report if the new evidence changes your conclusion — this is how good research works', 'Note the disagreement in a footnote without changing your conclusion', 'Ask Claude to refute the colleague\'s paper'], correct: 1, explanation: 'Good research is self-correcting. When a colleague identifies a contradictory source: obtain it, evaluate its quality and relevance, and honestly assess whether it changes your conclusion. If it does, update your report — that\'s intellectual integrity. If it doesn\'t (the study is lower quality, measures something different, etc.), document why in your report: "One study (Author, 2024) suggests X, but we assessed this study as [reason it doesn\'t change the conclusion]." The worst response is to suppress or ignore contradictory evidence.' }
  ]
},

'15-7': {
  addMinutes: 25,
  sections: [
    { type: 'workshop', tag: 'BUILD', title: 'Workshop A — Sprint Planning', content: 'Plan your full research sprint before starting.\n\n**Step 1 — Define your research question** precisely. Ask Claude to help you sharpen it:\n"My research question is: [draft question]. Help me make this more precise. What are the boundaries? What exactly counts as an answer?"\n\n**Step 2 — Create a research plan:**\n```\n## Research Sprint Plan\n\n**Question**: [precise version]\n**Time budget**: [hours available]\n**Audience**: [who needs this research]\n**Deliverable**: [what format — report, brief, recommendation]\n\n**Phase 1 — Background** ([X] minutes)\n- [Tools to use]\n- [Questions to answer]\n\n**Phase 2 — Deep Research** ([X] minutes)\n- [Tools to use]\n- [Key sources to find]\n\n**Phase 3 — Synthesis** ([X] minutes)\n- [Output to produce]\n\n**Phase 4 — Writing** ([X] minutes)\n```\n\n**Step 3 — Ask Claude to review the plan:** "Is this research plan appropriate for the question? What important angles am I missing?"' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Execute the Research Sprint', content: 'Run a complete research sprint using all the tools from Part 15.\n\n**Step 1 — Execute Phase 1** (background research): use Perplexity for current information, Claude for conceptual framework.\n\n**Step 2 — Execute Phase 2** (deep research): find and process primary sources, extract key data.\n\n**Step 3 — Execute Phase 3** (synthesis): combine findings, identify consensus and gaps, build the evidence picture.\n\n**Step 4 — Execute Phase 4** (writing): draft the deliverable using the report writing skills from Lesson 15-6.\n\n**Step 5 — Mandatory end-of-sprint review:** Ask Claude: *"Review my research sprint output [paste the deliverable]. What are the 3 weakest points? What would a domain expert challenge?"*\n\n**Step 6 — Fix the weakest points** before finalising.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Research Quality Audit', content: 'Audit the quality of your sprint research.\n\n**Step 1 — Take your completed research sprint deliverable.**\n\n**Step 2 — Run this quality checklist:**\n- [ ] Every major claim has a credible source\n- [ ] Sources are recent enough for the topic\n- [ ] I\'ve checked for contradictory evidence\n- [ ] The methodology of cited research is sound\n- [ ] I\'ve disclosed limitations and uncertainties\n- [ ] The conclusion follows from the evidence\n- [ ] I\'ve separated facts from interpretations\n\n**Step 3 — For any unchecked box**, address the gap before finalising.\n\n**Step 4 — Assign a confidence level:** Overall, how confident are you in your research? (High/Medium/Low) Communicate this appropriately in the deliverable.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Research Sprint Retrospective', content: 'Conduct a retrospective on your research sprint to improve future sprints.\n\n**Step 1 — Answer these questions honestly:**\n- What worked well in the research sprint?\n- What took longer than planned and why?\n- Where did AI tools help most?\n- Where did AI tools produce inaccurate or misleading information?\n- What would you do differently next time?\n\n**Step 2 — Ask Claude:** *"Review how I used AI tools in this research sprint [describe your process]. What could I have done more efficiently? Where did I use AI where manual research would have been better?"*\n\n**Step 3 — Update your research template** based on the retrospective.\n\n**Step 4 — Schedule your next research sprint.** What question needs answering in your work this week?' },

    { type: 'quiz', question: 'You complete a research sprint in 3 hours but are not confident in the conclusions. What should you do?', options: ['Publish the findings anyway — you did the research', 'Be transparent about uncertainty: add a confidence level to your deliverable, list the specific questions you couldn\'t fully answer, and recommend further research before major decisions', 'Extend the sprint until you are confident', 'Have AI generate more supporting evidence for your conclusions'], correct: 1, explanation: 'Uncertainty in research is normal and honest. The wrong response: suppress the uncertainty or artificially inflate confidence. The right response: communicate it. "Based on available evidence, we conclude X with medium confidence. The main uncertainties are Y and Z. Before a major decision, we recommend verifying W." This is more valuable than false certainty — it tells decision-makers what they can and cannot rely on.' },

    { type: 'quiz', question: 'In your research sprint, you find one very strong source that contradicts your hypothesis. What is the intellectually honest response?', options: ['Ignore it — one source shouldn\'t override your hypothesis', 'Engage with it seriously: evaluate its quality, determine whether it changes your hypothesis, and if so, update your hypothesis — this is how research should work', 'Mention it briefly in limitations but continue with your original hypothesis', 'Find other sources that support your hypothesis to balance it out'], correct: 1, explanation: 'A single strong contradictory source deserves serious engagement, not dismissal. Evaluate: is the source high quality (peer-reviewed, strong methodology, reputable authors)? If yes, it should change your hypothesis or at minimum significantly increase your uncertainty. If no (poor methodology, biased source), document why you\'re not weighting it heavily. Selectively ignoring strong contradictory evidence to preserve your hypothesis is confirmation bias — the opposite of good research.' }
  ]
},

'16-1': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — AI Writing Workflow Audit', content: 'Map your current writing workflow and identify AI improvement opportunities.\n\n**Step 1 — List every type of writing** you do regularly: emails, reports, documentation, proposals, presentations, social posts.\n\n**Step 2 — For each type**, estimate:\n- Time spent per instance\n- Time spent per week total\n- Your satisfaction with the quality (1-5)\n- How formulaic vs creative it is (1=completely formulaic, 5=highly creative)\n\n**Step 3 — Ask Claude:** "For these writing types [list them], which benefit most from AI assistance? Which require mostly human judgement? For each, what specific AI help would be most valuable?"\n\n**Step 4 — Calculate the highest-value AI writing target:** high time × formulaic × low satisfaction = best automation candidate.\n\n**Step 5 — Identify your #1 writing pain point** to address with AI this week.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build Your Writing Voice Guide', content: 'Create a writing style guide that helps AI match your voice.\n\n**Step 1 — Gather 5 examples** of your best writing (emails, reports, anything). These represent your voice.\n\n**Step 2 — Ask Claude to analyse your style:**\n"Analyse these 5 writing samples. Describe my writing style: sentence length, vocabulary level, use of hedging language, formality level, how I structure arguments, distinctive phrases I use, and what I consistently avoid."\n\n**Step 3 — Review the analysis.** Does it capture your actual voice? What did Claude miss?\n\n**Step 4 — Create a "Writing Voice Guide"** based on the analysis:\n```\n# [Your Name] Writing Style Guide\n\n## Voice characteristics\n- Tone: [e.g., direct but friendly, formal but not stuffy]\n- Sentence length: [e.g., prefer short sentences, max 20 words]\n- Vocabulary: [e.g., avoid jargon, use plain language]\n\n## What I always do\n- [e.g., lead with the key point]\n\n## What I never do\n- [e.g., passive voice, filler phrases like "in order to"]\n```\n\n**Step 5 — Add this guide to your Claude Projects** so every writing session starts with your style.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — AI Writing Anti-Patterns', content: 'Identify and eliminate common AI writing problems from your output.\n\n**Step 1 — Ask Claude:** "List the most recognisable signs of AI-generated writing. What phrases, patterns, and structures make text sound like it was written by an AI? Why do these patterns emerge?"\n\n**Step 2 — Check a sample of your recent AI-assisted writing** for these patterns.\n\n**Step 3 — Common AI writing anti-patterns to eliminate:**\n- "In today\'s fast-paced world..."\n- "It\'s important to note that..."\n- Excessive use of em dashes and colons\n- Lists for everything (even when prose would be better)\n- Hedging every statement\n- Generic examples instead of specific ones\n\n**Step 4 — For each anti-pattern found**, ask Claude to rewrite the passage without that pattern.\n\n**Step 5 — Build an editing checklist** specific to the AI patterns you personally overuse.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Develop a Full AI Writing Workflow', content: 'Build an end-to-end writing workflow for your primary writing type.\n\n**Step 1 — Choose your most frequent document type.**\n\n**Step 2 — Design the workflow:**\n- **Pre-writing:** What context/outline do I give AI before drafting?\n- **Drafting:** What prompt generates the best first draft?\n- **Review:** What editing passes do I run? What do I check manually?\n- **Finalisation:** What final human review happens before sending?\n\n**Step 3 — Ask Claude to help design the prompts for each stage.**\n\n**Step 4 — Test the complete workflow** on a real document you need to write.\n\n**Step 5 — Evaluate:** Did this workflow save time while maintaining or improving quality? What would you change?' },

    { type: 'quiz', question: 'You use Claude to draft all your emails. A colleague comments that your recent emails "don\'t sound like you anymore." What is the problem and fix?', options: ['Your colleague is wrong — AI-assisted writing is still your writing', 'Your emails have lost your voice — you\'re accepting AI drafts without editing them to match your natural style; fix by developing a style guide and editing every draft before sending', 'You should write all emails manually going forward', 'Use a different AI model that matches your style better'], correct: 1, explanation: 'When AI drafts replace rather than assist your writing, voice gets lost. The fix: (1) build a style guide (Workshop B), (2) treat every AI draft as a starting point, not a final product, (3) always edit for your actual voice and specific relationship with the reader, (4) add personal references or details the AI couldn\'t know. The goal: AI handles structure and first draft, you bring the voice and specific context.' },

    { type: 'quiz', question: 'You ask Claude to write a formal business proposal. It produces professional-sounding text but you\'re not sure the logic is sound. What is the critical review step?', options: ['Check for grammar and spelling', 'Read for logical coherence: does each claim follow from evidence? Does the proposal make a compelling case? Would a skeptical reader be persuaded? The prose can be polished while the argument is weak', 'Have Claude check the logic itself', 'Submit it — if Claude made it formal, the logic is sound'], correct: 1, explanation: 'AI excels at producing professional-sounding, well-structured text. It does not guarantee logical soundness. A proposal can be grammatically perfect with beautiful transitions while making logically weak arguments or missing key business considerations. Your review must focus on: Is the problem statement accurate? Are the claims supported? Is the proposed solution actually feasible? Would our client be persuaded? Run the content review separately from the prose review.' }
  ]
},

'16-2': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Document Type Analysis', content: 'Understand the distinctive requirements of each business document type.\n\n**Step 1 — Ask Claude:** "Compare these document types for a business professional: report, proposal, briefing, white paper, case study. For each: purpose, typical audience, structure, and what makes an excellent vs mediocre example."\n\n**Step 2 — Match your upcoming documents** to the right type:\n| Upcoming document | Correct type | Why |\n|---|---|---|\n| [Your doc] | | |\n\n**Step 3 — For your highest-priority upcoming document**, ask Claude to describe the ideal structure and key success criteria.\n\n**Step 4 — Find one excellent example** of that document type (ask Claude for examples, or search your organisation\'s past documents). Analyse what makes it excellent.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Write a Real Business Proposal', content: 'Write a real business proposal with AI assistance.\n\n**Step 1 — Identify a real proposal you need to write** (or a practice one if none is pending).\n\n**Step 2 — Gather your content inputs:** What problem are you solving? What is your solution? What is the cost/benefit? Who are the decision-makers?\n\n**Step 3 — Ask Claude to draft section by section:**\n```\nDraft the [Executive Summary] for a proposal:\n- Problem: [describe it]\n- Solution: [your proposal]\n- Business case: [cost, benefit, ROI]\n- Ask: [what you need approved]\n- Audience: [decision-maker roles]\n\nThis must be 1 page maximum. Lead with the business case, not the technical details.\n```\n\n**Step 4 — Review each section.** Is every claim true? Is the business case honest?\n\n**Step 5 — Mandatory review:** Ask a colleague to read the executive summary. What questions do they have after reading it? Fill those gaps.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Data Storytelling', content: 'Learn to use AI to turn data into compelling business narratives.\n\n**Step 1 — Take a real dataset or set of metrics** from your work.\n\n**Step 2 — Ask Claude:** "Here is my data: [paste data or key numbers]. What is the most important story this data tells? What narrative would resonate with [your audience]?"\n\n**Step 3 — Review the story Claude identifies.** Is it the right one for your context? What nuance does it miss?\n\n**Step 4 — Ask Claude to write the data narrative** for your document:\n"Write a 3-paragraph data narrative for a business report based on this analysis [paste Claude\'s story analysis]. Use specific numbers. Start with the bottom-line finding."\n\n**Step 5 — Check every number** in the narrative against your actual data.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Document Review Workflow', content: 'Build a systematic review workflow for high-stakes business documents.\n\n**Step 1 — Ask Claude to design a review workflow** for business proposals:\n```\nDesign a review workflow for a business proposal before it goes to senior leadership. Include:\n1. Accuracy review: fact-checking all claims\n2. Logic review: checking that conclusions follow from evidence\n3. Audience review: is the language and detail level right for decision-makers?\n4. Risk review: what objections will they raise?\n5. Final check: is the ask clear and actionable?\n\nCreate a checklist for each stage.\n```\n\n**Step 2 — Apply the workflow** to a document you\'re preparing.\n\n**Step 3 — For each checklist item**, address any gaps found.\n\n**Step 4 — Have a colleague review** using the checklist — does it help them give more useful feedback?' },

    { type: 'quiz', question: 'An AI-drafted business report uses the phrase "significant increase" repeatedly. What is the problem and fix?', options: ['No problem — "significant" is professional business language', 'Vague language: "significant" means different things to different readers. Replace with specific numbers: "37% increase," "£2.3M improvement," "3× faster" — quantify every claim you can', 'Replace with "notable increase" for more professional language', 'Define "significant" in the glossary'], correct: 1, explanation: 'Vague qualifiers ("significant," "substantial," "major," "considerable") are AI writing defaults that reduce credibility. Decision-makers need specific numbers to evaluate claims. "Significant increase in customer retention" tells a decision-maker nothing — they can\'t evaluate whether this is worth the investment. "Customer retention improved from 71% to 84% (13 percentage points) in Q3" tells them exactly what happened. Always replace vague qualifiers with specific measurements.' },

    { type: 'quiz', question: 'You\'re writing a proposal to senior leadership who are skeptical about the proposed initiative. How should you structure the proposal?', options: ['Lead with all the benefits to build enthusiasm before mentioning concerns', 'Acknowledge the main objections early and address them directly — skeptical readers who feel their concerns are not addressed will dismiss the rest of the proposal', 'Keep it short to avoid giving them time to object', 'Lead with technical details to demonstrate credibility first'], correct: 1, explanation: 'Skeptical readers read defensively — they\'re looking for gaps and objections. If you don\'t address their main concerns early, they stop reading with the concern unresolved. Structure for skeptical audiences: (1) acknowledge the key concern upfront, (2) address it with evidence, (3) then make your case. "We know cost is the primary concern. Here\'s the ROI case." This demonstrates you understand their perspective and builds trust before making your ask.' }
  ]
},

'16-3': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Data Analysis Without Code Drill', content: 'Analyse a dataset without writing any code.\n\n**Step 1 — Take a spreadsheet or CSV** you actually need to analyse. If you don\'t have one, ask Claude to generate a sample dataset of 50 rows.\n\n**Step 2 — Paste a sample** (first 20 rows) into Claude and ask:\n```\nAnalyse this dataset:\n[paste data]\n\n1. Describe what this dataset contains and what each column represents\n2. What are the most interesting patterns or trends?\n3. Are there any anomalies or outliers I should investigate?\n4. What are the top 3 business questions this data can answer?\n5. What analysis would I need to do to answer each question?\n```\n\n**Step 3 — Pick the most important question** and ask Claude to answer it using the data.\n\n**Step 4 — Verify Claude\'s analysis** against the raw numbers.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Deep Data Analysis on a Real Dataset', content: 'Conduct a thorough data analysis on a real business dataset.\n\n**Step 1 — Choose a real dataset** with at least 100 rows: sales data, customer data, operational metrics, survey results.\n\n**Step 2 — Paste representative samples** and ask Claude for comprehensive analysis:\n```\nConduct a thorough analysis of this business data:\n[paste sample]\n\nProvide:\n1. Summary statistics for key numeric columns\n2. Trend analysis: what is changing over time?\n3. Segmentation: what groups or patterns exist in the data?\n4. Correlation analysis: what variables seem related?\n5. Recommendations: what business decisions does this data support?\n\nBe specific — use the actual numbers from the data.\n```\n\n**Step 3 — Ask follow-up questions** on the most interesting finding.\n\n**Step 4 — Mandatory review:** Ask Claude: *"What analysis did you skip or approximate? What would a professional data analyst do differently with this dataset?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Chart and Visualisation Recommendations', content: 'Use AI to decide how to visualise your data most effectively.\n\n**Step 1 — Take your analysis from Workshop B** and ask Claude:\n"For each insight from the analysis, what is the most effective chart type? For each recommendation: chart type, what goes on each axis, what the chart should show, and what annotation would be most helpful."\n\n**Step 2 — Create the recommended charts** in Excel, Google Sheets, or another tool.\n\n**Step 3 — Ask Claude to review your charts:** "Review these charts [describe them]. Are they the most effective way to communicate each insight? What would make each chart clearer?"\n\n**Step 4 — Identify the one chart** that most clearly communicates the key finding. This is your "hero chart" for any presentations.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Data Analysis to Business Decision', content: 'Convert your data analysis into a concrete business recommendation.\n\n**Step 1 — Take your completed analysis.**\n\n**Step 2 — Ask Claude:**\n```\nBased on this data analysis [paste it], write a business recommendation memo:\n\n- To: [decision-maker role]\n- From: [your role]\n- Subject: [what decision this informs]\n\nInclude:\n1. Bottom line up front: the recommended action\n2. Data evidence: 3 specific data points that support it\n3. Business impact: what happens if we act vs don\'t act\n4. Confidence level: how strong is the evidence?\n5. Next step: one concrete action to approve\n```\n\n**Step 3 — Review the memo.** Is every data point verifiable? Is the recommendation genuinely supported by the data?\n\n**Step 4 — Send the memo** (or prepare it for your next meeting).' },

    { type: 'quiz', question: 'You paste 500 rows of data to Claude and ask for analysis. Claude says "based on this data, X." How confident should you be in this finding?', options: ['Fully confident — Claude can analyse data perfectly', 'Verify the key findings: Claude may misread column headers, make arithmetic errors, or miss important context about what the data represents. Spot-check 3 claims against the raw data', 'Only confident if Claude also shows its calculations', 'Confident only if the finding seems intuitive to you'], correct: 1, explanation: 'AI data analysis has real failure modes: misidentifying column relationships, making arithmetic errors on large numbers, missing context about what values mean (is 0 a missing value or a real zero?), and confusing units. For any analysis that informs a decision, verify: pick 3 specific claims Claude made, check them manually against the raw data. If they\'re right, your confidence in the rest increases. If any are wrong, review the full analysis more carefully.' },

    { type: 'quiz', question: 'Claude analyses your sales data and says "customers in Region A have significantly higher lifetime value." What follow-up question is most important?', options: ['How much higher is "significantly"?', 'All of: what is "significantly" in numbers, how many customers are in each region (sample size matters), are there confounding factors (product mix, demographics), and is the difference recent or historical?', 'What AI model was used for the analysis?', 'Whether this is consistent with last year\'s data'], correct: 1, explanation: 'A meaningful finding requires several validations: (1) quantify it — "Region A customers are worth £4,200 vs £2,800 average, a 50% difference" is meaningful; (2) check sample size — 5 customers in Region A is not a reliable finding; (3) check for confounders — maybe Region A only sells premium products; (4) check trend — is this a new pattern or consistent? Without these, "significantly higher lifetime value" could be a statistical artifact rather than a business insight.' }
  ]
},

'16-4': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Presentation Structure Design', content: 'Design a presentation structure with AI before creating any slides.\n\n**Step 1 — Define your presentation context:**\n- Audience: who will be in the room and what do they care about?\n- Goal: what decision or action do you want them to take?\n- Time: how long do you have?\n- Format: live presentation, video, self-guided deck?\n\n**Step 2 — Ask Claude:**\n```\nDesign a presentation structure for this scenario:\nAudience: [describe them]\nGoal: get them to [specific action]\nTime: [minutes]\nContext: [relevant background]\n\nFor each slide: title, main point (one sentence), supporting evidence needed.\n```\n\n**Step 3 — Review the structure.** Is the narrative arc compelling? Does it build to the ask?\n\n**Step 4 — Apply the "one main point per slide" rule:** Does each slide have exactly one clear takeaway?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — AI-Assisted Slide Creation', content: 'Create presentation content using AI assistance.\n\n**Step 1 — For each slide in your structure**, ask Claude to draft the content:\n```\nWrite the content for this slide:\nTitle: [slide title]\nMain point: [the one thing this slide must communicate]\nEvidence: [data or examples to support it]\nAudience: [who is in the room]\n\nProvide: headline (10 words max), 3 bullet points (8 words each max), and one strong statistic or quote if available.\n```\n\n**Step 2 — Review each slide\'s content** — is it clear and accurate?\n\n**Step 3 — Ask Claude to review the flow:** "Review these slide titles in sequence: [list them]. Does the presentation flow logically? Does each slide set up the next?"\n\n**Step 4 — Build one section of slides** in your presentation tool using the AI-drafted content.\n\n**Step 5 — Mandatory review:** Ask Claude: *"What objections will my audience have at each slide? What\'s missing?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Speaker Notes with AI', content: 'Use AI to write speaker notes that make you sound prepared.\n\n**Step 1 — For each slide**, ask Claude to write speaker notes:\n```\nWrite speaker notes for this slide:\nSlide content: [paste content]\nTransition from: [previous slide\'s topic]\nTransition to: [next slide\'s topic]\nKey points to emphasise verbally: [anything not on the slide]\nTime allocation: [how long to spend here]\n```\n\n**Step 2 — Review the notes.** Do they sound like you? Edit for your natural speaking style.\n\n**Step 3 — Add personal elements** Claude couldn\'t know: a specific example from your experience, a reference to something the audience knows.\n\n**Step 4 — Practice the presentation** with the notes once. What do you need to explain that the notes don\'t cover?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Q&A Preparation', content: 'Prepare for difficult questions with AI assistance.\n\n**Step 1 — Ask Claude** to anticipate questions:\n```\nI\'m presenting [topic] to [audience]. Based on this presentation [summarise it], generate:\n1. The 5 most likely questions they will ask\n2. The 3 most challenging questions a skeptic would ask\n3. Any "gotcha" questions someone who wants to derail the proposal might raise\n\nFor each question, provide a concise, honest answer.\n```\n\n**Step 2 — Review the questions.** Any surprises? Any you can\'t answer well?\n\n**Step 3 — Prepare honest answers** for the difficult questions — don\'t try to deflect them.\n\n**Step 4 — Practice answering** the top 3 hardest questions out loud. The act of saying the answer aloud reveals gaps that reading doesn\'t.' },

    { type: 'quiz', question: 'Claude generates 15 bullet points for one slide about your product\'s features. What should you do before using this content?', options: ['Use all 15 — more information is better', 'Select 3 maximum: one slide with 15 bullets communicates nothing because nothing stands out — choose the 3 most important to your audience and put the rest in the appendix or speaker notes', 'Turn them into a table instead', 'Use a smaller font to fit them all'], correct: 1, explanation: 'The rule of 3 (or fewer) applies to slide bullets: when everything is emphasised, nothing is. 15 bullets on a slide means the audience reads the slide instead of listening to you, gets overwhelmed, and remembers nothing specific. Pick the 3 most important points for your audience\'s goals. The other 12 belong in: speaker notes (for your reference), an appendix slide (for if you\'re asked), or a leave-behind document.' },

    { type: 'quiz', question: 'Your AI-drafted presentation slides look polished but don\'t feel personal. What is the most important thing to add?', options: ['More data and statistics', 'Specific, personal examples: a customer story, a project you worked on, a moment where you saw the problem firsthand — AI cannot generate these, and they\'re what audiences remember', 'Better graphics and visuals', 'More confident language'], correct: 1, explanation: 'What audiences remember is stories and specific examples, not frameworks and statistics. AI drafts are generic by design — they produce content that works for any presenter. The personal elements that make a presentation memorable: "I saw this fail firsthand when [specific example]," "One of our customers told me [specific story]," "When I ran this analysis, I was surprised to find [specific finding]." These come from you, not from AI, and they\'re the most persuasive content in any presentation.' }
  ]
},

'16-5': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Email Template Audit', content: 'Audit your current email templates and identify improvement opportunities.\n\n**Step 1 — List the 5 types of emails** you write most frequently.\n\n**Step 2 — Find or recreate an example** of each type from your sent folder.\n\n**Step 3 — Ask Claude to review each:**\n"Review this email [paste it] for: clarity, appropriate tone for the relationship, whether the ask is clear, length (is it too long?), and any phrases that could be misinterpreted."\n\n**Step 4 — For the weakest email type**, ask Claude to write an improved template:\n"Rewrite this email to be more [clear/concise/direct/warm]. Keep [specific elements that work]. Fix [specific problems identified]."\n\n**Step 5 — Compare the original and improved versions.** What changed and why?' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Communication Template Library', content: 'Create a personalised template library for your most frequent communications.\n\n**Step 1 — Design templates for your top 5 communication types:**\n- Status update to stakeholders\n- Meeting request (external)\n- Follow-up after no response\n- Delivering bad news\n- Requesting feedback or input\n\n**Step 2 — For each template**, ask Claude:\n```\nCreate a template for [email type]. The template should:\n- Have [PLACEHOLDERS] for variable content\n- Match this tone: [your typical tone]\n- Be [X] sentences maximum\n- Lead with [key information type]\n- Include a clear, specific call to action\n```\n\n**Step 3 — Test each template** by filling in real content for an email you need to send.\n\n**Step 4 — Save templates** where you can access them quickly (Notion, Claude Project, text snippets tool).' },

    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop C — Communication Tone Calibration', content: 'Practice matching AI-generated communications to the right tone for different relationships.\n\n**Step 1 — Ask Claude to write the same message** in 4 different tones:\n- Formal (to a new external client)\n- Professional (to a colleague)\n- Warm-professional (to a long-term collaborator)\n- Direct (to your own team)\n\nMessage: "The project deadline has moved from Friday to Wednesday and we need your review input by Tuesday EOD."\n\n**Step 2 — Read all 4 versions.** Can you feel the tone difference?\n\n**Step 3 — For your most important relationship type**, define the exact tone you want:\n- What words or phrases characterise it?\n- What does it avoid?\n- What is the typical opening and closing?\n\n**Step 4 — Add your tone definition** to your personal style guide from Lesson 16-1.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Sensitive Communication Drafts', content: 'Use AI to help draft communications that require particular care.\n\n**Step 1 — Identify a sensitive communication** you need to write: delivering criticism, explaining a mistake, declining a request, communicating a delay.\n\n**Step 2 — Ask Claude to draft it:**\n```\nDraft a [email/message] that:\n- Delivers this message: [what you need to communicate]\n- To: [recipient and your relationship with them]\n- Maintaining: [the relationship/professional standing]\n- Tone: honest but [kind/professional/direct]\n- Length: [maximum sentences]\n\nAvoid: blame, vagueness about the problem, and false optimism.\n```\n\n**Step 3 — Review carefully.** Does it say what needs to be said? Does it do so in a way that preserves the relationship?\n\n**Step 4 — Edit for your voice** and specific relationship context.\n\n**Step 5 — Mandatory check:** Before sending, read it from the recipient\'s perspective. How might they interpret it?' },

    { type: 'quiz', question: 'You use AI to draft a message telling a team member their work needs significant revision. The AI draft is polite but vague. What is the problem?', options: ['The tone is too harsh — soften it further', 'Vagueness is unkind: a person who receives vague criticism can\'t improve because they don\'t know what specifically to change — be specific about what needs to change and why', 'The message should be delivered in person, not in writing', 'The AI correctly softened the message'], correct: 1, explanation: 'Vague feedback ("the work needs improvement") is unhelpful and unkind — the recipient is left guessing. Specific feedback ("the executive summary needs to lead with the financial case rather than the technical background, and the timeline in Section 3 is inconsistent with the constraints we discussed") allows the person to act. AI drafts often default to vagueness to avoid conflict. Your edit should add the specific detail: what exactly needs to change and why.' },

    { type: 'quiz', question: 'You save 30 minutes per week using email templates. After 2 months, a colleague says your emails "feel impersonal lately." What\'s happening?', options: ['Templates always feel impersonal — stop using them', 'You\'ve been using templates without personalising them — add specific personal context (reference their situation, their name in the body, something specific to them) to maintain warmth', 'Shorten the templates to reduce the "template feel"', 'Use a different tone in templates'], correct: 1, explanation: 'Templates become a problem when used as-is rather than as starting points. A good template provides structure; a bad template provides the whole message. Personal emails reference the recipient\'s specific situation: "I know you\'ve been dealing with the Q3 audit..." Templates should have clear [PLACEHOLDER] points for personalisation. If you\'re sending templates without filling in the personal parts, recipients will notice — personal references are what make communication feel human.' }
  ]
},

'16-6': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Meeting Workflow Audit', content: 'Audit your current meeting workflow to identify AI improvement opportunities.\n\n**Step 1 — Count your meetings last week:**\n- How many total meetings?\n- How many had clear agendas beforehand?\n- How many had action items captured and sent after?\n- How many resulted in concrete decisions?\n\n**Step 2 — Ask Claude:** "What percentage of meeting time is typically wasted in poorly run meetings? What are the highest-impact improvements to make meetings effective?"\n\n**Step 3 — Identify your worst meeting habit** (no agenda, no notes, no follow-up, unclear decision-making).\n\n**Step 4 — Design one AI-assisted improvement** for that habit and implement it this week.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — AI Meeting Preparation System', content: 'Build a system for AI-assisted meeting preparation.\n\n**Step 1 — Create a meeting prep template:**\n```markdown\n# Meeting Prep: [Meeting Title] — [Date]\n\n## Context\n[What is this meeting about? What decisions need to be made?]\n\n## My objectives\n[What do I need to achieve or communicate in this meeting?]\n\n## Key questions to ask\n[Questions I need answered]\n\n## Potential objections to my positions\n[What pushback might I face?]\n\n## Pre-read materials\n[Documents to review]\n```\n\n**Step 2 — Ask Claude to help fill in the template** for an upcoming meeting:\n"Help me prepare for this meeting: [describe the meeting]. Based on the context, what are the key questions I should ask? What objections might I face? What should I have reviewed beforehand?"\n\n**Step 3 — Use the prep document** before your next meeting. Did it improve your participation?\n\n**Step 4 — Refine the template** based on what was most useful.' },

    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop C — Meeting Notes and Action Items', content: 'Build an AI-powered meeting notes and follow-up system.\n\n**Step 1 — After your next meeting**, write brief rough notes: what was discussed, what was decided, what actions were taken.\n\n**Step 2 — Ask Claude to process your rough notes:**\n```\nProcess these meeting notes into a clean summary:\n[paste rough notes]\n\nStructure as:\n## Decisions Made\n[List each decision]\n\n## Action Items\n| Action | Owner | Due Date |\n|---|---|---|\n\n## Open Questions\n[Items not resolved]\n\n## Key Discussion Points\n[1-2 sentence summary of each major topic]\n```\n\n**Step 3 — Review the structured output.** Did Claude capture everything correctly?\n\n**Step 4 — Send the meeting summary** to attendees within 2 hours of the meeting.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Meeting Efficiency Improvement', content: 'Improve the meetings you run using AI-assisted design.\n\n**Step 1 — Choose a recurring meeting** you run that could be more effective.\n\n**Step 2 — Ask Claude:**\n"Help me improve this recurring meeting: [describe it — purpose, attendees, typical agenda, typical duration]. What format would make it more efficient? What should be eliminated? Could some of this be done asynchronously instead?"\n\n**Step 3 — Design an improved meeting format** based on Claude\'s suggestions:\n- New agenda structure\n- Time allocations per topic\n- Pre-reading to assign\n- Decision-making process\n- How action items will be tracked\n\n**Step 4 — Run the improved format** for the next 3 instances.\n\n**Step 5 — Evaluate:** Did the meeting get shorter? Were decisions made more efficiently? Did attendees feel it was more productive?' },

    { type: 'quiz', question: 'You use AI to generate meeting agendas. A colleague complains that your agendas are too detailed and leave no room for organic discussion. What is the right balance?', options: ['Always use detailed agendas — they improve efficiency', 'Agenda detail should match the meeting type: decision meetings need detailed structure; brainstorming and relationship meetings need space for unplanned conversation', 'Never use detailed agendas — they constrain valuable discussion', 'Ask your colleagues what level of detail they prefer and vary by person'], correct: 1, explanation: 'Meeting design depends on purpose. Decision meetings need clear agenda items, time allocations, and pre-distributed materials — organic discussion on a decision can go in circles without structure. Brainstorming meetings need prompts and freedom, not tight structure. Relationship meetings (check-ins, 1:1s) need topics but should allow the conversation to follow what\'s important that day. AI generates detailed agendas by default — you must edit for the actual meeting type.' },

    { type: 'quiz', question: 'Your AI-generated meeting summary assigns an action item "Review the proposal" to "the team." Why is this problematic and how do you fix it?', options: ['No problem — the team knows who they are', 'Collective ownership means no individual ownership — the action will likely not happen. Fix: assign every action item to a specific named individual with a specific deadline', 'Add "URGENT" to the action item description', 'Send a follow-up email to the team asking who will take ownership'], correct: 1, explanation: '"The team" as an action owner is one of the most common causes of action items not getting done. Without a named individual responsible, everyone assumes someone else will do it. Fix: after AI generates action items, review each one and assign a specific person. Also set a specific deadline — "by end of week" is better than nothing, but "by Thursday 5pm" is better still. Action items with owner + deadline are significantly more likely to be completed.' }
  ]
},

'16-7': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — SOP Quality Assessment', content: 'Assess the quality of your current process documentation.\n\n**Step 1 — Find an existing SOP or process document** from your work (or a process that exists in people\'s heads but not on paper).\n\n**Step 2 — Ask Claude to evaluate it:**\n"Review this process documentation [paste it] and assess: (1) Could someone new follow this without asking questions? (2) What steps are missing or unclear? (3) What decision points exist but aren\'t documented? (4) What is assumed knowledge that isn\'t stated?"\n\n**Step 3 — Score the SOP** on a 1-10 usability scale. What would it take to get to 10?\n\n**Step 4 — Ask Claude:** "What makes an excellent SOP vs a mediocre one? Give me specific examples of what good documentation looks like."' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Document a Process with AI', content: 'Create a complete SOP for a process you know well.\n\n**Step 1 — Choose a process you perform** that should be documented: an onboarding step, a recurring operational task, a technical procedure.\n\n**Step 2 — Describe the process to Claude** in rough terms:\n"Help me document this process as an SOP: [describe it roughly]. Ask me any clarifying questions you need before writing the documentation."\n\n**Step 3 — Answer Claude\'s questions** — they reveal gaps in your description.\n\n**Step 4 — Have Claude draft the SOP:**\n```\nWrite an SOP for [process name]:\n- Purpose: why this process exists\n- When to use this SOP\n- Prerequisites: what must be true before starting\n- Steps: numbered, actionable (start each with a verb)\n- Decision points: what to do if [condition]\n- Common mistakes: what goes wrong and how to avoid it\n- Output: what the finished state looks like\n```\n\n**Step 5 — Test the SOP** by following it yourself as if you\'d never done this before. What\'s missing?' },

    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop C — SOP Testing and Validation', content: 'Validate your SOP by having someone else follow it.\n\n**Step 1 — Give your SOP** to a colleague who has NOT done this process before.\n\n**Step 2 — Ask them to follow the SOP exactly** without asking you for help (unless they\'re completely stuck). Observe silently or have them flag where they\'re confused.\n\n**Step 3 — Note every point of confusion** or question they have.\n\n**Step 4 — Ask Claude** to help fix each identified gap:\n"The SOP tester got stuck at this step: [describe the step and what confused them]. How should I clarify this step?"\n\n**Step 5 — Revise the SOP** with all the identified fixes.\n\n**Step 6 — Consider:** This testing process applies to any documentation. An SOP that one person can follow without questions is good; one that two people can follow without questions is excellent.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build a Process Documentation Library', content: 'Create a systematic approach to documenting all your key processes.\n\n**Step 1 — Identify your knowledge bus factor:** Which processes exist only in your head? What would happen if you were unavailable for 2 weeks?\n\n**Step 2 — Prioritise processes to document:**\n| Process | Risk if undocumented | Time to document | Priority |\n|---|---|---|---|\n| [Process] | [impact] | [hours] | |\n\n**Step 3 — Create a documentation roadmap:** Commit to documenting 2 processes per week using the SOP template from Workshop B.\n\n**Step 4 — Ask Claude Code** to create a process documentation system:\n"Create a simple markdown-based process documentation system with: templates, an index file, and a review schedule. Processes should be findable by category and by when they were last reviewed."\n\n**Step 5 — Start with the highest-risk process** today.' },

    { type: 'quiz', question: 'Your SOP has 20 steps and a colleague who follows it makes an error at step 15 every time. What does this pattern reveal?', options: ['The colleague needs better training', 'Step 15 has a documentation problem — it\'s unclear, missing a decision point, or assumes knowledge the follower doesn\'t have. Fix the step, not the person', 'The process is too complex to document', 'The colleague is not carefully reading the SOP'], correct: 1, explanation: 'Repeated errors at the same step are a documentation signal, not a people signal. A step that consistently causes errors is a step that needs clarification. Ask: What decision does the follower need to make at step 15 that isn\'t documented? What prerequisite knowledge does the step assume? What does the correct output of step 15 look like? Fix the documentation, test with another follower. If the error stops, the documentation was the root cause.' },

    { type: 'quiz', question: 'You document a process using AI assistance. Six months later, the process has changed but the SOP hasn\'t been updated. What is the risk?', options: ['Documentation is only aspirational — outdated SOPs are fine', 'New team members following the outdated SOP will perform the process incorrectly, potentially causing errors or rework; stale documentation is often worse than no documentation', 'The risk is low if the process changed only slightly', 'Only a risk if auditors review your documentation'], correct: 1, explanation: 'Outdated documentation is a real operational risk. New team members treat SOPs as authoritative — if an SOP says "submit to system A" but the process now uses system B, they\'ll submit to the wrong system confidently. Outdated documentation can be worse than no documentation (no documentation: people ask; outdated documentation: people follow the wrong instructions). Fix: establish a documentation review schedule (quarterly for frequently-used processes) and update SOPs whenever the underlying process changes.' }
  ]
}

};

function enhance(id, filePath) {
  const raw = fs.readFileSync(filePath, 'utf8');
  const lesson = JSON.parse(raw);
  const enh = enhancements[id];
  if (!enh) { console.log('SKIP '+id); return; }
  let successIdx = -1;
  for (let i = lesson.sections.length - 1; i >= 0; i--) {
    if (lesson.sections[i].type === 'callout' && lesson.sections[i].variant === 'success') {
      successIdx = i; break;
    }
  }
  const insertAt = successIdx >= 0 ? successIdx : lesson.sections.length;
  lesson.sections.splice(insertAt, 0, ...enh.sections);
  lesson.estimatedMinutes += enh.addMinutes;
  fs.writeFileSync(filePath, JSON.stringify(lesson, null, 2));
  const ws = lesson.sections.filter(s=>s.type==='workshop').length;
  const qz = lesson.sections.filter(s=>s.type==='quiz').length;
  console.log('OK '+id+' | ws:'+ws+' qz:'+qz+' mins:'+lesson.estimatedMinutes);
}

const lessons = [
  ['15-2','data/lessons/part-15/15-2.json'],
  ['15-3','data/lessons/part-15/15-3.json'],
  ['15-4','data/lessons/part-15/15-4.json'],
  ['15-5','data/lessons/part-15/15-5.json'],
  ['15-6','data/lessons/part-15/15-6.json'],
  ['15-7','data/lessons/part-15/15-7.json'],
  ['16-1','data/lessons/part-16/16-1.json'],
  ['16-2','data/lessons/part-16/16-2.json'],
  ['16-3','data/lessons/part-16/16-3.json'],
  ['16-4','data/lessons/part-16/16-4.json'],
  ['16-5','data/lessons/part-16/16-5.json'],
  ['16-6','data/lessons/part-16/16-6.json'],
  ['16-7','data/lessons/part-16/16-7.json'],
];

lessons.forEach(([id, rel]) => {
  try { enhance(id, 'C:/Projects/Learning/'+rel); }
  catch(e) { console.log('FAIL '+id+': '+e.message); }
});
