const fs = require('fs');

const enhancements = {

'5-1': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — VS Code First Impressions Drill', content: 'This 8-minute drill gets you oriented in VS Code before diving into details.\n\n**Step 1 — Open VS Code** (if not installed: code.visualstudio.com). Notice the Welcome tab.\n\n**Step 2 — Identify the 5 zones** of the VS Code interface by hovering over each icon in the Activity Bar (left side):\n- Explorer (files)\n- Search\n- Source Control (git)\n- Run & Debug\n- Extensions\n\n**Step 3 — Open the Command Palette** (Ctrl+Shift+P). Type "theme" and switch to a different colour theme. This shows you can customise anything.\n\n**Step 4 — Open a new file** (Ctrl+N). Type a few lines of anything. Notice how VS Code auto-detects file type when you save it with a .txt, .py, or .js extension.\n\n**Step 5 — Ask Claude.ai:** *"I just opened VS Code for the first time. What are the 5 things I should set up or learn in my first hour? Be specific to my goal of [your learning goal]."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Configure VS Code for Your Workflow', content: 'VS Code works best when configured for your specific work. This workshop personalises it.\n\n**Step 1 — Open VS Code settings** (Ctrl+,). Browse through the categories.\n\n**Step 2 — Configure the 5 most impactful settings:**\n- Font size: set to a comfortable reading size (14-16)\n- Auto save: enable "After Delay"\n- Word wrap: enable "On"\n- Tab size: set to your preference (2 or 4)\n- Theme: browse and select a theme you find comfortable\n\n**Step 3 — Install 3 essential extensions** via the Extensions panel (Ctrl+Shift+X):\n- "Prettier" — automatic code formatting\n- "GitLens" — enhanced git features\n- One language-specific extension for the language you\'re learning\n\n**Step 4 — Ask Claude:** *"I\'m setting up VS Code for [describe your goals]. What extensions and settings would you recommend specifically for my use case? Give me the exact extension names and the specific settings to change."*\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review the VS Code setup you just recommended. What are 3 settings or extensions you didn\'t mention that a professional developer in [your context] would consider essential?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — VS Code vs Other Editors', content: 'Understanding why VS Code is dominant helps you understand what it\'s optimised for.\n\n**Step 1 — Ask Claude:** *"Compare VS Code to these alternatives: Notepad++, Sublime Text, Cursor, and JetBrains IDEs. For each, tell me: (1) what type of user it\'s designed for, (2) its main advantage over VS Code, (3) when I would choose it over VS Code."*\n\n**Step 2 — Read the comparison.** Which alternative sounds most interesting for your use case?\n\n**Step 3 — Look up Cursor** (cursor.sh) — it\'s a VS Code fork built for AI-first development. Ask Claude: "How is Cursor different from VS Code? Would it be better than VS Code for someone learning to work with AI on code?"\n\n**Step 4 — Make an informed decision:** For your specific goals, is VS Code the right editor? Write one sentence explaining your choice.\n\n**Step 5 — Note:** The skills you learn in VS Code transfer almost directly to Cursor — they share 95% of the same interface and keyboard shortcuts.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Set Up a VS Code Workspace for a Real Project', content: 'A VS Code Workspace keeps your project organised and saves your editor settings.\n\n**Step 1 — Create a real project folder** for something you\'re working on: a learning project, a scripts folder, a writing project.\n\n**Step 2 — Open VS Code and open the folder** (File → Open Folder, or `code .` from the terminal inside the folder).\n\n**Step 3 — Save it as a Workspace** (File → Save Workspace As). Name it after your project.\n\n**Step 4 — Ask Claude:** *"I\'m setting up a VS Code workspace for [describe your project]. What folder structure should I create? What files should I add to get started? Give me the exact commands to run in the terminal."*\n\n**Step 5 — Create the folder structure** Claude recommends.\n\n**Step 6 — Open the workspace next time** by double-clicking the .code-workspace file. VS Code will restore your open files and settings.' },

    { type: 'quiz', question: 'What is the main reason VS Code became the most popular code editor, despite many alternatives existing?', options: ['It was the first code editor ever made', 'It\'s free, open source, highly extensible through extensions, and has excellent AI integration support', 'It\'s made by Apple, which ensures quality', 'It can only be used for web development, making it specialised'], correct: 1, explanation: 'VS Code dominates because of its combination of: being free and open-source, a vast extension ecosystem (50,000+ extensions for any language or workflow), great performance, excellent git integration built-in, and being the first major editor to deeply integrate AI coding assistance (GitHub Copilot). Its extensibility means it adapts to virtually any development workflow.' },

    { type: 'quiz', question: 'You open VS Code and cannot find the Command Palette. What keyboard shortcut opens it?', options: ['Ctrl+P', 'Ctrl+Shift+P', 'Alt+F4', 'F1 or Ctrl+Shift+P both work'], correct: 3, explanation: 'The Command Palette opens with Ctrl+Shift+P (or F1). It\'s the single most important keyboard shortcut in VS Code — it gives access to every command VS Code can execute, without needing to find it in menus. Ctrl+P (without Shift) opens the file picker (Go to File), which is also extremely useful. Memorise both.' }
  ]
},

'5-2': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BUILD', title: 'Workshop A — Install and Verify VS Code', content: 'If you haven\'t installed VS Code yet, this drill guides you through it. If you have, you\'ll verify the installation is complete.\n\n**Step 1 — Download VS Code** from code.visualstudio.com. Choose the installer for your operating system.\n\n**Step 2 — During installation**, ensure these options are checked:\n- "Add to PATH" (allows running `code .` from terminal)\n- "Register Code as an editor for supported file types"\n- "Add Open with Code action to file/directory context menu"\n\n**Step 3 — Verify the installation:**\n```powershell\ncode --version\n```\nYou should see a version number like `1.x.x`. If not, VS Code wasn\'t added to PATH.\n\n**Step 4 — Test the `code .` shortcut:**\n```powershell\nmkdir test-workspace\ncd test-workspace\ncode .\n```\nVS Code should open with the test-workspace folder loaded.\n\n**Step 5 — If `code .` doesn\'t work**, ask Claude: *"VS Code is installed but `code .` doesn\'t work in PowerShell. How do I fix this on Windows?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Install Python and Node.js Alongside VS Code', content: 'VS Code alone is just an editor. To run code, you need interpreters. This workshop sets up both Python and Node.js.\n\n**Step 1 — Check what\'s already installed:**\n```powershell\npython --version\nnode --version\nnpm --version\n```\n\n**Step 2 — Install Python** (if not installed): python.org → Download Python 3.x. During installation, CHECK "Add Python to PATH".\n\n**Step 3 — Install Node.js** (if not installed): nodejs.org → Download LTS version. The installer also installs npm.\n\n**Step 4 — Verify both:**\n```powershell\npython --version\nnode --version\n```\n\n**Step 5 — In VS Code**, open the Command Palette (Ctrl+Shift+P) and type "Python: Select Interpreter". Select your installed Python version.\n\n**Step 6 — Ask Claude:** *"I\'ve installed VS Code, Python, and Node.js. What are the first 3 things I should verify to make sure everything is configured correctly for [your learning goal]?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — VS Code Extensions for AI Development', content: 'The right extensions turn VS Code into an AI-powered development environment.\n\n**Step 1 — Open the Extensions panel** (Ctrl+Shift+X).\n\n**Step 2 — Install these AI-specific extensions:**\n- "GitHub Copilot" — AI code completion (free tier available)\n- "Continue" (continue.dev) — open-source AI assistant, works with Claude\n- "Codeium" — free AI completion alternative\n\n**Step 3 — Configure Continue** to use Claude: After installing, open its settings and add your Anthropic API key (or use the free tier).\n\n**Step 4 — Test AI assistance:** Open a Python file, start typing a function, and see if AI suggests a completion.\n\n**Step 5 — Ask Claude:** *"I\'ve installed AI extensions in VS Code. What are the most effective ways to use AI code assistance — not just tab-complete, but for bigger tasks like explaining code, generating tests, and refactoring?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Write and Run Your First Program in VS Code', content: 'End-to-end: write a real program, run it, see the output — all inside VS Code.\n\n**Step 1 — Open VS Code** and open a project folder.\n\n**Step 2 — Create a new Python file**: Right-click in Explorer → New File → `hello.py`.\n\n**Step 3 — Ask Claude:** *"Write me a Python script that does something useful in about 20 lines: [describe something you want — a calculator, a to-do list, a file organiser, a text formatter]. Include comments explaining each part."*\n\n**Step 4 — Paste the code** into hello.py.\n\n**Step 5 — Run it** using the VS Code terminal (Ctrl+` to open):\n```powershell\npython hello.py\n```\n\n**Step 6 — If there are errors**, paste them back to Claude. Ask for the fix.\n\n**Step 7 — Mandatory code review:** Ask Claude: *"Review this code you just wrote. What are 3 improvements you would make to make it more robust, readable, or useful?"* Apply at least one improvement.' },

    { type: 'quiz', question: 'After installing VS Code, you run `code .` in PowerShell and get "command not found." What is the most likely cause?', options: ['VS Code needs to be restarted', 'The "Add to PATH" option was not checked during installation, so the shell doesn\'t know where to find the code command', 'PowerShell doesn\'t support VS Code commands', 'You need to install a VS Code extension first'], correct: 1, explanation: '"Add to PATH" adds VS Code to the list of locations Windows checks when you type a command. If you skipped this option, PowerShell can\'t find the `code` command. The fix: reinstall VS Code with "Add to PATH" checked, or manually add VS Code to your system PATH (Settings → System → Advanced system settings → Environment Variables).' },

    { type: 'quiz', question: 'You want to run a Python file you just wrote in VS Code. Which approach runs the code?', options: ['Double-click the .py file in Explorer', 'Open the integrated terminal (Ctrl+`) and run `python filename.py`', 'Press Ctrl+S to save and it automatically runs', 'Click File → Run'], correct: 1, explanation: 'The standard way to run a Python file in VS Code is through the integrated terminal: Ctrl+` opens the terminal, then `python filename.py` runs the file. You can also press F5 (Run and Debug) or use the Run button that appears when a Python extension is installed. Double-clicking a .py file usually opens it in the editor, not runs it.' }
  ]
},

'5-3': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Interface Navigation Drill', content: 'This 8-minute drill builds interface fluency through timed challenges.\n\n**Step 1 — Close all open tabs and panels** in VS Code. Start fresh.\n\n**Step 2 — Time yourself on each challenge (aim for under 10 seconds):**\n\n- Open the Explorer panel without using the mouse\n- Open the Command Palette\n- Open the integrated terminal\n- Open the Extensions panel\n- Switch between two open files using the keyboard only\n- Go to line 50 in the current file\n- Find all occurrences of the word "function" in the current file\n- Open the Settings page\n\n**Step 3 — For any challenge that took more than 15 seconds**, look up the keyboard shortcut and practice it 3 times.\n\n**Step 4 — Ask Claude:** *"Give me the 10 VS Code keyboard shortcuts that the most productive developers use every day. For each, explain when you\'d use it and what it does. Format as a table: Shortcut | Action | When to use it."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Customise Your VS Code Layout', content: 'A personalised layout reduces friction and makes you faster. This workshop sets yours up.\n\n**Step 1 — Configure the Activity Bar:** Right-click the Activity Bar (the leftmost icon column). Hide any panel you won\'t use regularly.\n\n**Step 2 — Configure the Status Bar:** The bar at the bottom shows useful info. Click on different elements to see what they control.\n\n**Step 3 — Set up Split Editor:** Open two files. Click View → Split Editor Right. Arrange them side-by-side — useful when reading reference code while writing.\n\n**Step 4 — Configure Minimap:** Open a long file. The minimap (right side) shows a bird\'s-eye view. Go to Settings and search "minimap" — enable or disable based on your preference.\n\n**Step 5 — Save your setup as a Profile:** File → Profiles → Create Profile. Name it for your use case. Profiles save your extensions and settings so you can restore them on a new machine.\n\n**Step 6 — Ask Claude:** *"I use VS Code for [your work type]. What layout settings and workspace configuration would a power user in my position have? Give me 5 specific things to change from defaults."*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Breadcrumbs, Outline and Navigation', content: 'VS Code has powerful navigation features that most beginners never discover. This workshop covers them.\n\n**Step 1 — Open a code file** (any .py, .js, .html file — create one if needed).\n\n**Step 2 — Enable Breadcrumbs** (View → Breadcrumbs). Notice the path shown at the top of the editor. Click any part of the breadcrumb to navigate.\n\n**Step 3 — Open the Outline Panel:** Explorer → Outline. This shows the structure of your file: functions, classes, variables. Click any item to jump to it.\n\n**Step 4 — Use Go to Definition:** Hover over a function name. Press F12. VS Code jumps to where that function is defined — even in another file.\n\n**Step 5 — Use Find All References:** Right-click a variable name → Find All References. VS Code shows every place that variable is used.\n\n**Step 6 — Ask Claude:** *"What are the most useful VS Code navigation features for working with AI-generated code? I often get code spread across multiple files and need to understand how pieces connect."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Multi-Cursor and Selection Power', content: 'Multi-cursor editing is the feature that makes VS Code users dramatically faster than Notepad users.\n\n**Step 1 — Create a file** with these test lines:\n```\nfirst_name = "Alice"\nfirst_name = "Bob"\nfirst_name = "Charlie"\n```\n\n**Step 2 — Practice multi-cursor:** Click the first `first_name`. Hold Alt and click the other two. You now have 3 cursors. Type `user_name` — it replaces all 3 at once.\n\n**Step 3 — Practice Select All Occurrences:** Select the word `user_name`. Press Ctrl+Shift+L. Every occurrence is selected. Type a replacement.\n\n**Step 4 — Practice box selection:** Hold Shift+Alt and drag vertically. This selects a column of text.\n\n**Step 5 — Ask Claude to give you a practice file:**\n```\nGenerate a Python file with 20 lines that has deliberate inconsistencies — some variables named with camelCase and some with snake_case, some with wrong spacing. I want to practice multi-cursor editing to fix them all at once.\n```\n\n**Step 6 — Fix all the inconsistencies** using multi-cursor, Select All Occurrences, and Find/Replace. Aim to do it with fewer than 10 keystrokes.' },

    { type: 'quiz', question: 'You are reading a function in VS Code and want to jump to where a variable was originally defined. What is the keyboard shortcut?', options: ['Ctrl+G', 'F12 (Go to Definition)', 'Ctrl+F (Find)', 'Ctrl+Home'], correct: 1, explanation: 'F12 (Go to Definition) jumps from where a symbol (variable, function, class) is used to where it\'s defined. This is essential when reading AI-generated code that spans multiple files. Ctrl+G goes to a specific line number. Ctrl+F opens Find. These navigation shortcuts are what separate fast VS Code users from slow ones.' },

    { type: 'quiz', question: 'You need to rename a variable from `oldName` to `newName` everywhere it appears in your file. What is the correct VS Code approach?', options: ['Find & Replace (Ctrl+H) — manually type each replacement', 'Select the variable name and press F2 (Rename Symbol) — VS Code renames it everywhere including definitions and references', 'Use multi-cursor to select each instance manually', 'Delete the file and ask AI to rewrite it with the correct name'], correct: 1, explanation: 'F2 (Rename Symbol) is the correct approach — it\'s a semantic rename that understands code. It renames the definition and all references, even across multiple files, and doesn\'t accidentally rename different things that happen to share the same string. Find & Replace (A) would rename everything with that text, including in strings and comments where you might not want it.' }
  ]
},

'5-4': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BUILD', title: 'Workshop A — Open and Explore a Real Project', content: 'This drill practices the most common VS Code opening workflow.\n\n**Step 1 — Choose an existing folder** from your machine — your Documents folder, a code project, or create a new one with some files in it.\n\n**Step 2 — Open it in VS Code** three different ways:\n- Drag the folder onto the VS Code icon\n- File → Open Folder\n- Terminal: `cd [your folder path]` then `code .`\n\n**Step 3 — In Explorer**, expand the folder tree. Notice the different file icons for different file types.\n\n**Step 4 — Open multiple files** and navigate between them using Ctrl+Tab.\n\n**Step 5 — Explore the Find in Files feature:** Ctrl+Shift+F. Search for any word that appears in your files. Notice how VS Code searches across all files in the folder.\n\n**Step 6 — Ask Claude:** *"I just opened a folder in VS Code. What are the first things I should do to orient myself in an unfamiliar project? Give me a 5-step exploration process."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Set Up a VS Code Project from Scratch', content: 'Most real projects require a standard folder structure. This workshop creates one using VS Code and Claude.\n\n**Step 1 — Decide on a project** you\'ll actually work on: a Python script collection, a simple website, a data analysis project, a writing project.\n\n**Step 2 — Ask Claude:** *"I\'m starting a [describe your project] project. What folder structure should I create? Give me the exact folder and file names, and tell me what each is for."*\n\n**Step 3 — Create the structure** using VS Code\'s Explorer panel (right-click → New Folder, New File).\n\n**Step 4 — Add a README file:** Create `README.md` in the root. Ask Claude: *"Write a brief README for a [your project] project. Include: what it does, how to set it up, and how to use it."*\n\n**Step 5 — Save as a Workspace** (File → Save Workspace As) so you can return to this exact setup.\n\n**Step 6 — Commit to git:**\n```powershell\ngit init\ngit add .\ngit commit -m "Initial project structure"\n```' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Workspace Settings and .vscode Folder', content: 'VS Code allows per-project settings that override global settings — useful when different projects need different configurations.\n\n**Step 1 — Open a project folder** in VS Code.\n\n**Step 2 — Open workspace settings:** Ctrl+Shift+P → "Open Workspace Settings (JSON)". This creates a `.vscode/settings.json` file.\n\n**Step 3 — Add a project-specific setting:**\n```json\n{\n    "editor.tabSize": 4,\n    "python.defaultInterpreterPath": "./venv/bin/python",\n    "files.exclude": {\n        "**/__pycache__": true,\n        "**/.pytest_cache": true\n    }\n}\n```\n\n**Step 4 — Ask Claude:** *"I\'m working on a [type of project]. What should go in my .vscode/settings.json to make VS Code work best for this project? Also, what should go in a .vscode/extensions.json to recommend extensions to teammates?"*\n\n**Step 5 — Create a .vscode/extensions.json** with Claude\'s recommendations. This means teammates who open the project get prompted to install the same extensions.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Multi-Root Workspace', content: 'A Multi-Root Workspace lets you work on multiple related folders simultaneously — common when building a project with separate frontend and backend codebases.\n\n**Step 1 — Create two related folders:**\n```powershell\nmkdir my-project\ncd my-project\nmkdir frontend\nmkdir backend\n```\n\n**Step 2 — In VS Code**, open the `my-project` folder. Then add the subfolders: File → Add Folder to Workspace → select `frontend`, then add `backend`.\n\n**Step 3 — Save as Multi-Root Workspace:** File → Save Workspace As. Name it `my-project.code-workspace`.\n\n**Step 4 — Notice** that Explorer now shows both folders. You can navigate between them seamlessly.\n\n**Step 5 — Add workspace-specific settings** to the .code-workspace file:\n```json\n{\n    "folders": [\n        { "path": "frontend" },\n        { "path": "backend" }\n    ],\n    "settings": {\n        "editor.fontSize": 14\n    }\n}\n```\n\n**Step 6 — Ask Claude:** *"I have a multi-root VS Code workspace with frontend and backend folders. What tasks, launch configurations, and settings should I add to make development easier?"*' },

    { type: 'quiz', question: 'What is the fastest way to open a folder in VS Code when you are already in that folder in your terminal?', options: ['Type `vscode .` in the terminal', 'Type `code .` in the terminal', 'Use File → Open Folder in VS Code', 'Drag the folder onto the VS Code taskbar icon'], correct: 1, explanation: '`code .` is the standard CLI shortcut to open the current directory in VS Code. The dot means "current directory". This requires VS Code to have been added to PATH during installation. It\'s the fastest workflow: navigate to your project folder in the terminal, then `code .` to open it in VS Code without leaving the terminal.' },

    { type: 'quiz', question: 'You have a .vscode/settings.json in your project that sets `"editor.tabSize": 2`. Your global VS Code settings have `"editor.tabSize": 4`. Which setting applies when you work in this project?', options: ['The global setting — it overrides workspace settings', 'The workspace setting — workspace settings override global settings for that project', 'Both apply — the larger number wins', 'VS Code asks you to choose each time you open the project'], correct: 1, explanation: 'VS Code uses a settings hierarchy: workspace settings override global (user) settings for that specific project. This is intentional — different projects have different conventions (Python typically uses 4-space indentation; JavaScript/JSON often use 2 spaces). You can maintain consistent global defaults while allowing project-specific overrides without breaking other projects.' }
  ]
},

'5-5': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BUILD', title: 'Workshop A — File Operations Speed Drill', content: 'Fluency with file operations in VS Code saves time every session. This drill builds that speed.\n\n**Step 1 — Open a project folder** in VS Code.\n\n**Step 2 — Practice each operation using only keyboard shortcuts:**\n- Create a new file: Ctrl+N (then save with Ctrl+S and name it)\n- Rename a file: Click it in Explorer, press F2\n- Duplicate a file: Right-click in Explorer → Copy, then Paste\n- Delete a file: Select it in Explorer, press Delete\n- Open a file by name: Ctrl+P → start typing the filename\n\n**Step 3 — Create this file structure** using VS Code Explorer (no terminal):\n```\nproject/\n  src/\n    main.py\n    utils.py\n  tests/\n    test_main.py\n  docs/\n    notes.md\n  README.md\n```\n\n**Step 4 — Time yourself:** How long did the full structure creation take?\n\n**Step 5 — Ask Claude:** *"What VS Code keyboard shortcuts for file operations should I memorise in my first week? Give me a ranked list from most to least important."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — AI-Organised Project File Setup', content: 'Use AI to design and create the right file structure for a real project you\'re working on.\n\n**Step 1 — Describe your project** to Claude: what you\'re building, what language or tools you\'re using, what the main components are.\n\n**Step 2 — Ask Claude:** *"Design the complete file structure for my project: [description]. Include: all folders and files with their purposes, which files to create first, and what basic content each key file should have to start."*\n\n**Step 3 — Create the structure** in VS Code exactly as Claude describes.\n\n**Step 4 — Ask Claude to populate the starter files:** For each key file (README, main entry point, config), ask Claude to write the initial content.\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review this project structure you just designed. What\'s missing? What would a senior developer say is wrong with this organisation? What would you add after seeing similar projects?"*\n\n**Step 6 — Commit the structure** to git as the "Initial structure" commit.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — .gitignore — What Not to Track', content: 'The .gitignore file tells git which files to ignore. This is a critical skill for keeping your repository clean.\n\n**Step 1 — Ask Claude:** *"I\'m working on a [Python / Node.js / HTML] project. Create a comprehensive .gitignore file for my project type. For each section, explain what you\'re ignoring and why."*\n\n**Step 2 — Create `.gitignore`** in your project root and paste Claude\'s content.\n\n**Step 3 — Understand the key categories** Claude included:\n- Dependencies (node_modules/, venv/) — huge, recreatable\n- Build artifacts (.pyc, dist/) — generated from source\n- Environment files (.env) — contain secrets\n- IDE files (.vscode/*, .idea/) — personal settings\n- OS files (.DS_Store, Thumbs.db) — system junk\n\n**Step 4 — Test it:** Run `git status`. Files matching .gitignore patterns should not appear as untracked.\n\n**Step 5 — Add a critical rule:** Never commit .env files. Ask Claude why this matters and what happens if you accidentally do.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — File Templates and Snippets', content: 'VS Code snippets let you type a short keyword and expand it into a full code template — saving repetitive typing.\n\n**Step 1 — Open Snippets:** Ctrl+Shift+P → "Configure User Snippets" → select your language (Python, JavaScript, etc.).\n\n**Step 2 — Ask Claude to write snippets for you:**\n```\nCreate VS Code user snippets for Python that give me:\n1. A function with a docstring template (trigger: func)\n2. A class template with __init__ (trigger: cls)\n3. A try/except block (trigger: try)\n4. A main guard (trigger: main)\n\nFormat them as valid VS Code snippet JSON.\n```\n\n**Step 3 — Paste the snippets** into your snippets file.\n\n**Step 4 — Test each snippet:** Open a Python file, type the trigger word, press Tab. The full template should expand.\n\n**Step 5 — Create one custom snippet** for something specific to your work: a standard file header, a common pattern you write, a template for a recurring task.' },

    { type: 'quiz', question: 'You accidentally delete a file in VS Code Explorer. How do you recover it?', options: ['The file is permanently gone — always use a backup', 'Press Ctrl+Z (Undo) in VS Code — deleting a file from Explorer can be undone', 'Check the Recycle Bin — deleted files go there', 'Both B and C are valid recovery approaches'], correct: 3, explanation: 'Both approaches can work. VS Code Explorer deletion sends files to the Recycle Bin (on Windows) — so you can recover from there. Ctrl+Z in VS Code may also undo the deletion for recently deleted files. The safest habit is to use git — if you\'ve committed the file, it\'s always recoverable from git history regardless of what you do in the file system.' },

    { type: 'quiz', question: 'What is the purpose of a .gitignore file?', options: ['It lists files that git will automatically commit', 'It specifies files and folders that git should not track, such as dependencies, build output, and secrets', 'It controls which branch git defaults to', 'It lists team members who are allowed to push to the repository'], correct: 1, explanation: '.gitignore tells git "do not track these files." Without it, git would want to commit your entire node_modules directory (potentially gigabytes), compiled output that changes on every build, and secret files like .env that contain API keys. A good .gitignore keeps your repository small, clean, and secure.' }
  ]
},

'5-6': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Command Palette Exploration Drill', content: 'The Command Palette is VS Code\'s most powerful feature. This drill explores it systematically.\n\n**Step 1 — Open the Command Palette** (Ctrl+Shift+P).\n\n**Step 2 — Try these searches** and note what each does:\n- "format" — find formatting commands\n- "git" — see all git commands available\n- "theme" — change colour theme\n- "json" — format JSON\n- "terminal" — terminal-related commands\n- "fold" — code folding commands\n- "markdown" — markdown preview and tools\n\n**Step 3 — Find the keyboard shortcut** for any command you use often: hover over it in the Command Palette — the shortcut shows on the right.\n\n**Step 4 — Use Ctrl+P** (not Ctrl+Shift+P). This is the "Go to File" palette — type any filename to jump to it instantly.\n\n**Step 5 — Use Ctrl+G** (Go to Line). Type a line number to jump there.\n\n**Step 6 — Ask Claude:** *"What are the 10 most productive things I can do from the VS Code Command Palette that most people don\'t know about?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build a Personalised Task Runner', content: 'VS Code Tasks let you run commands (like running tests, building, formatting) with a keyboard shortcut. This workshop sets yours up.\n\n**Step 1 — Ask Claude:** *"I want to set up VS Code Tasks for a [Python / Node.js] project. I need tasks for: running the main script, running tests, and formatting code. Create the tasks.json file for my .vscode folder."*\n\n**Step 2 — Create `.vscode/tasks.json`** and paste Claude\'s content.\n\n**Step 3 — Run a task:** Ctrl+Shift+P → "Tasks: Run Task" → select your task.\n\n**Step 4 — Set a keyboard shortcut** for your most common task: Ctrl+Shift+P → "Open Keyboard Shortcuts" → search for "Run Task" → add your shortcut.\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review the tasks.json you created. What could go wrong when I run these tasks? What environment assumptions are you making that might not be true on my machine?"* Fix any identified issues.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Search and Replace Across Project', content: 'The global search in VS Code (Ctrl+Shift+F) is one of the most powerful tools in the editor.\n\n**Step 1 — Open Find in Files** (Ctrl+Shift+F).\n\n**Step 2 — Practice these powerful search features:**\n\n**Basic search:** Search for a common word that appears in multiple files. Notice the results panel.\n\n**Regex search:** Click the .* button to enable regex. Search for `def \\w+\\(` to find all function definitions in Python.\n\n**Replace across files:** Find a function name, switch to Replace mode (expand the left panel), and replace it across all files at once.\n\n**Include/Exclude:** Use the "Files to Include" box to search only in `*.py` files or exclude `node_modules`.\n\n**Step 3 — Practical use:** Search your project for any hardcoded value (like a URL or configuration value) that should be in a config file.\n\n**Step 4 — Ask Claude:** *"What are the most useful regex patterns for searching code? Give me 5 patterns with what they find and when they\'re useful."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Command Palette Power Workflows', content: 'This workshop builds a set of Command Palette workflows for your most common tasks.\n\n**Step 1 — List your top 5 VS Code tasks** — things you do frequently in your coding sessions.\n\n**Step 2 — For each task**, find the Command Palette command and its keyboard shortcut.\n\n**Step 3 — Set up keyboard shortcuts** for any frequent tasks that don\'t have one: Ctrl+Shift+P → "Open Keyboard Shortcuts (JSON)" → add custom bindings.\n\n**Step 4 — Ask Claude:** *"I use VS Code for [your workflow]. What keyboard shortcuts should I customise or add? Give me the exact JSON to add to keybindings.json for these shortcuts: [your top tasks]."*\n\n**Step 5 — Create a "keyboard shortcuts" cheatsheet** — a text file in your project listing your custom shortcuts and what they do. Print it or keep it visible until the shortcuts become muscle memory.' },

    { type: 'quiz', question: 'You want to run a shell command from inside VS Code without leaving the editor. What is the fastest approach?', options: ['Exit VS Code, run the command, and reopen VS Code', 'Open the Command Palette and type the shell command directly', 'Press Ctrl+` to open the integrated terminal, then run the command', 'Use File → Execute Command'], correct: 2, explanation: 'Ctrl+` (backtick) opens VS Code\'s integrated terminal — a full terminal that runs inside VS Code. You can run any shell command here without leaving the editor, and it automatically opens in your project\'s root folder. This is the core workflow for running Python scripts, npm commands, git operations, and any other CLI task while keeping your code visible.' },

    { type: 'quiz', question: 'You open the Command Palette and type "format". You see "Format Document" but no keyboard shortcut shown next to it. What does this mean?', options: ['The command is not available for your file type', 'No keyboard shortcut is currently assigned to this command — you can assign one by clicking the gear icon', 'You need to install a formatting extension first', 'The shortcut is hidden — you need to hover to see it'], correct: 1, explanation: 'When no keyboard shortcut appears next to a command in the Command Palette, it means none is currently assigned. You can assign one: hover over the command and click the gear icon that appears, or go to File → Preferences → Keyboard Shortcuts. Many useful commands have no default shortcut — assigning your own to the commands you use frequently is a significant productivity improvement.' }
  ]
},

'5-7': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop A — Integrated Terminal Drill', content: 'VS Code\'s integrated terminal is where you spend a lot of time. This drill builds fluency.\n\n**Step 1 — Open the integrated terminal** (Ctrl+`).\n\n**Step 2 — Practice these terminal operations:**\n- Open a second terminal: click the + icon in the terminal panel\n- Switch between terminals: click the terminal names in the dropdown\n- Split the terminal: click the split icon — two terminals side-by-side\n- Kill a terminal: click the trash icon\n\n**Step 3 — Configure your terminal:**\n- Click the dropdown arrow next to + → Select Default Profile → choose PowerShell or Git Bash\n- Right-click the terminal area → Font Size → increase to a comfortable size\n\n**Step 4 — Terminal useful shortcuts:**\n- Ctrl+C: stop a running process\n- Ctrl+L or `clear`: clear the terminal screen\n- Up arrow: recall previous commands\n- Tab: autocomplete file/command names\n\n**Step 5 — Ask Claude:** *"What are the 5 most time-saving terminal techniques for someone using PowerShell in VS Code for [your work type]?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Run a Real Project in the Terminal', content: 'Use the integrated terminal to run a complete project workflow from start to finish.\n\n**Step 1 — Open your project** in VS Code.\n\n**Step 2 — Run these project commands** from the integrated terminal (adapting to your project type):\n\nFor Python:\n```powershell\npython --version\npython main.py\n```\n\nFor Node.js:\n```powershell\nnode --version\nnpm install\nnode index.js\n```\n\nFor any project:\n```powershell\ngit status\ngit log --oneline\n```\n\n**Step 3 — If you encounter an error**, paste it directly to Claude from the terminal. Ask: "I got this error while running [command] in VS Code\'s integrated terminal: [paste error]. What does it mean and how do I fix it?"\n\n**Step 4 — Install a dependency** from the terminal (Python example):\n```powershell\npip install requests\n```\n\n**Step 5 — Verify the dependency works** by writing a 3-line Python script that imports it.' },

    { type: 'workshop', tag: 'TERMINAL', title: 'Workshop C — Terminal Profiles and Customisation', content: 'Set up your terminal to be faster and more informative.\n\n**Step 1 — Check what shells are available:**\n```powershell\n# In PowerShell:\nGet-Command -Name pwsh, bash, zsh 2>$null\n```\n\n**Step 2 — Install Windows Terminal** (if on Windows): it\'s a better terminal than the default cmd. Install from Microsoft Store.\n\n**Step 3 — Configure VS Code terminal settings:**\nOpen Settings (Ctrl+,) → search "terminal" → configure:\n- `terminal.integrated.fontSize`: set to a comfortable size\n- `terminal.integrated.cursorBlinking`: enable\n- `terminal.integrated.defaultProfile.windows`: set to PowerShell\n\n**Step 4 — Install Oh My Posh** (optional but impactful): It adds a theme to your PowerShell prompt that shows git branch, Python environment, and other useful context. Ask Claude: "How do I install Oh My Posh for PowerShell to improve my terminal experience?"\n\n**Step 5 — Test your improved terminal** by navigating into a git repository and noticing the branch name shown in your prompt.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Terminal Automation Script', content: 'Automate your project startup with a script that runs from the VS Code terminal.\n\n**Step 1 — Identify your project startup sequence** — the commands you run at the start of every work session: activating a virtual environment, starting a server, running initial checks.\n\n**Step 2 — Ask Claude:** *"Create a PowerShell/bash script called `start.ps1` (or `start.sh`) that automates my project startup. The script should: [describe your startup sequence]. After each step, it should print a confirmation message so I know it succeeded."*\n\n**Step 3 — Create and test the script** from the VS Code terminal.\n\n**Step 4 — Add it to your VS Code Task:**\nIn .vscode/tasks.json, add a task that runs your startup script:\n```json\n{\n    "label": "Start Project",\n    "type": "shell",\n    "command": ".\\\\start.ps1",\n    "group": "build"\n}\n```\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review this startup script. What could cause it to fail on a different machine or after a system update? What should I add to make it more robust?"*' },

    { type: 'quiz', question: 'You\'re running a Python server in VS Code\'s terminal and it\'s stuck — it won\'t accept new commands. How do you stop it?', options: ['Close VS Code and reopen it', 'Press Ctrl+C — this sends an interrupt signal to stop the running process', 'Close the terminal tab — this kills the process', 'Press Ctrl+Z'], correct: 1, explanation: 'Ctrl+C sends an interrupt signal (SIGINT) to the running process, which is the standard way to stop servers, scripts, or any running terminal program gracefully. Most well-written programs handle this by cleaning up and shutting down. Ctrl+Z suspends the process (it continues running in the background). Closing the terminal tab (C) does also kill the process but is less clean.' },

    { type: 'quiz', question: 'You have three terminals open in VS Code running different things: one running your server, one for git commands, and one for running tests. How do you switch between them?', options: ['You can only have one terminal open at a time', 'Click the terminal names in the terminal dropdown panel', 'Press Ctrl+Tab', 'Type `switch` in any terminal'], correct: 1, explanation: 'VS Code\'s integrated terminal panel shows multiple terminals as separate tabs or entries in a dropdown. Click the name/number of the terminal you want to switch to. You can also use the dropdown arrow next to the terminal panel header to see all active terminals. Keeping multiple terminals open (server, git, tests) is a standard professional workflow — you don\'t need to stop and restart between tasks.' }
  ]
},

'5-8': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Extension Discovery Drill', content: 'The Extensions marketplace has 50,000+ extensions. This drill teaches you to find the right ones.\n\n**Step 1 — Open the Extensions panel** (Ctrl+Shift+X).\n\n**Step 2 — Browse the categories:**\n- "@popular" in the search — most installed extensions\n- "@trending" — what\'s gaining popularity\n- "@installed" — what you have now\n\n**Step 3 — Search for your use case:**\n- Type "Python" — see all Python-related extensions. Note the install count and rating.\n- Type "AI" — see AI assistance extensions\n- Type your specific tool (Docker, AWS, etc.)\n\n**Step 4 — Read before installing:** Click on 2-3 extensions you\'re considering. Read the description page — does it solve your actual problem?\n\n**Step 5 — Check the extension\'s GitHub:** Most extensions link to their GitHub. Check: last updated (within 6 months is good), open issues, stars.\n\n**Step 6 — Ask Claude:** *"What are the must-have VS Code extensions for [your specific development work]? For each, tell me why it\'s worth installing and what problem it solves."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — AI Extension Setup and Workflow', content: 'Set up an AI coding assistant in VS Code — and learn how to use it effectively, not just as autocomplete.\n\n**Step 1 — Install an AI extension.** Options (in order of recommendation):\n- GitHub Copilot — best quality, free tier available\n- Continue (continue.dev) — open source, works with Claude API\n- Codeium — completely free tier\n\n**Step 2 — Configure the extension** with your API key or account login.\n\n**Step 3 — Learn the 5 most powerful uses** (ask Claude if your chosen extension doesn\'t document these well):\n- Inline completion: start typing and Tab to accept\n- Ask about selected code: select code → right-click → Ask AI\n- Generate a function from a comment describing it\n- Generate tests for an existing function\n- Explain what a file does\n\n**Step 4 — Mandatory review:** For any AI-generated code in VS Code, always run: *"Review this code. Find 3 problems a code reviewer would catch."* This is the most important habit.\n\n**Step 5 — Measure the impact:** Time a coding task with AI assistance. How much faster was it?' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Extension Conflicts and Management', content: 'Too many extensions slow VS Code and can cause conflicts. This workshop teaches extension hygiene.\n\n**Step 1 — Check your current extensions:** Ctrl+Shift+X → @installed. List everything you have.\n\n**Step 2 — Identify and remove duplicates:** Common duplicates — two language servers for the same language, multiple formatters for the same file type.\n\n**Step 3 — Check extension impact on startup:**\nCtrl+Shift+P → "Developer: Show Running Extensions" — this shows which extensions are loaded and their activation time.\n\n**Step 4 — Disable slow extensions:** Extensions with > 500ms activation time are worth disabling if you don\'t use them constantly.\n\n**Step 5 — Use Extension Profiles:** Create a "Minimal" profile with only essential extensions. Use it when VS Code feels slow. Create a "Full" profile for intensive coding sessions.\n\n**Step 6 — Ask Claude:** *"I have these VS Code extensions installed: [list]. Which ones might conflict with each other? Which ones are redundant? Which should I prioritise keeping?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build an Extensions Recommendations File', content: 'Create a .vscode/extensions.json that recommends your essential extensions to anyone who opens your project.\n\n**Step 1 — Identify 5-7 extensions** that are essential for working on your project.\n\n**Step 2 — Find each extension\'s ID:** In the Extensions panel, click on each extension → copy the extension ID shown under the name.\n\n**Step 3 — Create `.vscode/extensions.json`:**\n```json\n{\n    "recommendations": [\n        "ms-python.python",\n        "ms-python.vscode-pylance",\n        "esbenp.prettier-vscode",\n        "dbaeumer.vscode-eslint"\n    ]\n}\n```\n\n**Step 4 — Test it:** Close and reopen VS Code on this folder. You should see a notification: "This workspace has extension recommendations."\n\n**Step 5 — Add a comment in README.md** explaining that opening this project in VS Code will prompt to install recommended extensions.\n\n**Step 6 — Ask Claude:** *"Should I also add any unwanted extensions to \'unwantedRecommendations\'? When is that useful?"*' },

    { type: 'quiz', question: 'You install a VS Code extension and your editor slows down significantly. What should you do first?', options: ['Reinstall VS Code completely', 'Disable the new extension and check if performance improves — if so, report the issue to the extension author or find an alternative', 'Increase your computer\'s RAM', 'Switch to a different code editor'], correct: 1, explanation: 'Disable the suspected extension first (Extensions panel → click the gear on the extension → Disable) and check if VS Code returns to normal speed. If it does, the extension is the cause. You can then decide to: keep it disabled, look for an alternative, or report the performance issue on the extension\'s GitHub. Use "Developer: Show Running Extensions" to measure activation times before and after.' },

    { type: 'quiz', question: 'Two VS Code extensions both claim to format Python code. What problem might this cause?', options: ['They will each format the code twice, making it slower', 'They may format code differently and conflict — when you save, one formatter\'s changes may be immediately overwritten by the other', 'It\'s not a problem — they will merge their formatting changes', 'VS Code will ask you which formatter to use each time'], correct: 1, explanation: 'Having two formatters for the same file type often causes a conflict where each formatter undoes the other\'s changes, resulting in unstable formatting or no formatting. The fix: keep one formatter, disable or uninstall the other, and set your preferred formatter explicitly in settings.json: `"[python]": {"editor.defaultFormatter": "ms-python.black-formatter"}`.' }
  ]
},

'5-9': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Settings Exploration Drill', content: 'This 8-minute drill explores VS Code settings so you know what you can customise.\n\n**Step 1 — Open Settings** (Ctrl+,).\n\n**Step 2 — Explore each major category** (left sidebar) and read 2-3 settings in each:\n- Text Editor: font, cursor, formatting\n- Workbench: appearance, sidebar layout\n- Extensions: each installed extension has settings here\n- Terminal: terminal appearance and behaviour\n\n**Step 3 — Find a setting you want to change** (font size, tab size, auto save). Change it and see the immediate effect.\n\n**Step 4 — Open Settings (JSON):** Ctrl+Shift+P → "Open User Settings (JSON)". This is the raw JSON behind the UI.\n\n**Step 5 — Add one JSON setting** that\'s not available in the UI (ask Claude: "Give me 5 VS Code settings that are only configurable via JSON, not the UI").\n\n**Step 6 — Note the difference:** UI settings = discoverable. JSON settings = more powerful and portable.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Build Your Ideal Settings.json', content: 'Create a settings.json that configures VS Code exactly how you want it — for your work, your eyes, your workflow.\n\n**Step 1 — Ask Claude:**\n```\nCreate a VS Code settings.json for a developer who:\n- Works with [your language(s)]\n- Values [readability / performance / minimal distractions / etc.]\n- Uses [your AI extension]\n- Common pain points: [any settings you\'ve disliked]\n\nExplain each setting in a comment above it. Make it production-ready.\n```\n\n**Step 2 — Review every setting** in the output. Remove anything you don\'t want.\n\n**Step 3 — Apply the settings:** Ctrl+Shift+P → "Open User Settings (JSON)" → replace with Claude\'s output (keeping any custom settings you already have).\n\n**Step 4 — Test by opening files** of each type you work with. Does everything look and behave correctly?\n\n**Step 5 — Mandatory review:** Ask Claude: *"Review this settings.json. What settings might conflict with each other? What settings might cause unexpected behaviour for [your use case]?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Sync Settings Across Machines', content: 'VS Code Settings Sync lets your configuration follow you to any machine.\n\n**Step 1 — Enable Settings Sync:** Click the person icon (bottom-left) → Turn on Settings Sync.\n\n**Step 2 — Choose what to sync:**\n- Settings\n- Keyboard Shortcuts\n- Extensions\n- Snippets\n- UI State\n\n**Step 3 — Sign in** with a Microsoft or GitHub account.\n\n**Step 4 — Verify sync:** If you have access to a second machine (or can check via the VS Code web version), verify your settings appear there.\n\n**Step 5 — Alternative: Manual sync** using a dotfiles repository. Ask Claude: "What is a dotfiles repository and how do developers use it to sync VS Code settings across machines without using the built-in sync feature?"\n\n**Step 6 — Decide your sync strategy:** Built-in sync is easiest. Dotfiles gives more control and works across all tools, not just VS Code.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Configure Language-Specific Settings', content: 'Different file types can have different settings in VS Code — for example, Python might use 4-space indentation while JavaScript uses 2.\n\n**Step 1 — Open your settings.json** (Ctrl+Shift+P → "Open User Settings JSON").\n\n**Step 2 — Add language-specific overrides:**\n```json\n{\n    "[python]": {\n        "editor.tabSize": 4,\n        "editor.defaultFormatter": "ms-python.black-formatter",\n        "editor.formatOnSave": true\n    },\n    "[javascript]": {\n        "editor.tabSize": 2,\n        "editor.defaultFormatter": "esbenp.prettier-vscode",\n        "editor.formatOnSave": true\n    },\n    "[json]": {\n        "editor.tabSize": 2,\n        "editor.formatOnSave": true\n    }\n}\n```\n\n**Step 3 — Test:** Open a .py file, add some messy indentation, save. Does it auto-format? Open a .js file — does it format differently?\n\n**Step 4 — Ask Claude:** *"What language-specific settings should I configure for [your language]? Include formatter choice, linter settings, and any special behaviour that differs from VS Code defaults."*' },

    { type: 'quiz', question: 'You change a VS Code setting in the UI but nothing changes in your project. You suspect there is a workspace settings.json that is overriding your user settings. How do you check?', options: ['Restart VS Code — settings sometimes require a restart', 'Open .vscode/settings.json in your project and check if the same setting is defined there — workspace settings override user settings', 'Reinstall VS Code with fresh settings', 'Disable all extensions and try again'], correct: 1, explanation: 'VS Code settings have a hierarchy: user settings (global) < workspace settings (.vscode/settings.json) < folder settings. Workspace settings override user settings for that project. If you change a setting globally but it doesn\'t take effect in a project, check if .vscode/settings.json has the same setting overriding it.' },

    { type: 'quiz', question: 'You want to enable "Format on Save" for JavaScript files only, not for Python files. How do you configure this in settings.json?', options: ['You cannot apply Format on Save to specific file types — it\'s an all-or-nothing setting', 'Use language-specific settings: "[javascript]": {"editor.formatOnSave": true} while leaving Python without that setting', 'Install a JavaScript-specific extension that adds Format on Save', 'Add formatOnSave to your .eslintrc file instead'], correct: 1, explanation: 'VS Code supports language-specific settings using the `"[languageid]"` key in settings.json. This lets you have formatOnSave for JavaScript but not Python (or vice versa), different tab sizes per language, different formatters per language, and any other setting that varies by file type. This is essential for polyglot developers who work across multiple languages with different conventions.' }
  ]
},

'5-10': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Keyboard Shortcuts Speed Test', content: 'Keyboard shortcuts compound over time — each one you learn saves seconds, hundreds of times a day.\n\n**Step 1 — Open a code or text file** in VS Code.\n\n**Step 2 — Time yourself on each task using only keyboard (no mouse):**\n\n| Task | Shortcut | Your time |\n|---|---|---|\n| Go to line 20 | Ctrl+G → 20 → Enter | |\n| Find the word "function" | Ctrl+F → type | |\n| Select the current line | Ctrl+L | |\n| Duplicate current line | Shift+Alt+Down | |\n| Delete current line | Ctrl+Shift+K | |\n| Move line up | Alt+Up | |\n| Comment out current line | Ctrl+/ | |\n| Open terminal | Ctrl+` | |\n| Format the document | Shift+Alt+F | |\n| Save file | Ctrl+S | |\n\n**Step 3 — For any shortcut taking > 5 seconds**, practice it 10 times until it\'s automatic.\n\n**Step 4 — Print the VS Code keyboard shortcut reference card** (Ctrl+Shift+P → "Open Default Keyboard Shortcuts" → PDF). Pick 3 new shortcuts to learn this week.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Custom Keyboard Shortcut Setup', content: 'Assign shortcuts to commands you use constantly but have no default binding.\n\n**Step 1 — Identify your top 5 actions** that require mouse clicks (and you do them > 5 times per session).\n\n**Step 2 — Open Keyboard Shortcuts:** Ctrl+Shift+P → "Open Keyboard Shortcuts" (the searchable UI).\n\n**Step 3 — For each action**, search for the command name, click the pencil icon, and press your desired shortcut combination.\n\n**Step 4 — Ask Claude for suggestions:**\n```\nI use VS Code for [your work]. I want custom keyboard shortcuts for:\n[list your top actions]\n\nSuggest shortcut combinations that:\n- Don\'t conflict with built-in VS Code shortcuts\n- Are ergonomic (easy to press)\n- Follow conventions developers use (Ctrl+Shift+letter for major actions)\n```\n\n**Step 5 — Export your shortcuts:** Ctrl+Shift+P → "Open Keyboard Shortcuts (JSON)" → copy and save somewhere safe (cloud, dotfiles repo).\n\n**Step 6 — Commit to 2 weeks:** Only use the keyboard, no mouse, for the shortcuts you just set up. Muscle memory takes about 2 weeks of consistent use.' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Refactoring Shortcuts', content: 'These shortcuts are specifically for editing and refactoring code efficiently — the keystrokes that separate fast coders from slow ones.\n\n**Step 1 — Create a Python file** with some test code:\n```python\ndef calculate_total(price, quantity, tax_rate):\n    subtotal = price * quantity\n    tax = subtotal * tax_rate\n    total = subtotal + tax\n    return total\n\nresult = calculate_total(10.99, 3, 0.08)\nprint(result)\n```\n\n**Step 2 — Practice these refactoring shortcuts:**\n- Rename symbol: click `calculate_total`, press F2, type new name → rename propagates everywhere\n- Extract selection: select `subtotal * tax_rate`, Ctrl+Shift+P → "Extract Variable"\n- Format document: Shift+Alt+F\n- Go to definition: click `calculate_total` in the last line, press F12\n- Peek definition: Alt+F12 (shows definition without leaving current file)\n\n**Step 3 — Use multi-cursor editing:** Hold Alt and click to add cursors. Add cursors at the beginning of lines 2-4 simultaneously.\n\n**Step 4 — Ask Claude:** *"What are the most powerful VS Code refactoring shortcuts for Python development? Give me 5 I should add to my muscle memory."*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build a Shortcuts Cheat Sheet for Your Use Case', content: 'Create a personalised keyboard shortcuts reference for your specific workflow.\n\n**Step 1 — Ask Claude:**\n```\nCreate a keyboard shortcuts cheat sheet for a VS Code user who:\n- Works primarily in [your language]\n- Uses [your extensions, e.g., GitHub Copilot]\n- Main tasks: [writing code / reviewing AI code / editing documents]\n\nFormat as a table: Action | Shortcut | Notes\nGroup by: Navigation, Editing, Git, Terminal, Extensions\nInclude only shortcuts I should learn in my first month.\n```\n\n**Step 2 — Review and personalise** the cheat sheet. Add your custom shortcuts. Remove any that don\'t apply.\n\n**Step 3 — Test every shortcut** on the list — confirm they all work on your VS Code install.\n\n**Step 4 — Save the cheat sheet** as a Markdown file in your project or in your notes app.\n\n**Step 5 — Share with a colleague** who also uses VS Code. Getting them to use the same shortcuts means you can help each other.' },

    { type: 'quiz', question: 'You want to comment out 10 lines of code at once. What is the fastest VS Code approach?', options: ['Type // at the beginning of each line manually', 'Select all 10 lines with Shift+Click, then press Ctrl+/ to toggle comments on all selected lines', 'Use Find & Replace to add // to each line', 'Ask the AI assistant to comment the code for you'], correct: 1, explanation: 'Ctrl+/ toggles comments on the current line or all selected lines. Select the 10 lines (click the start, Shift+click the end), then Ctrl+/ — all 10 lines are commented simultaneously. The same shortcut with the lines still selected will uncomment them. This works for line comments in any language VS Code knows (// for JS/Python/C#, # for Python, -- for SQL, etc.).' },

    { type: 'quiz', question: 'What does pressing Alt+Up/Down do in VS Code?', options: ['Scrolls the editor viewport up or down', 'Moves the currently selected line(s) up or down in the file', 'Navigates between files in the editor tabs', 'Increases or decreases text size'], correct: 1, explanation: 'Alt+Up/Down moves the current line (or selected lines) up or down in the file — it\'s a physical line reorder. This is much faster than cut-paste when you want to reorder code. It works on single lines or multi-line selections. An equivalent operation with Shift+Alt+Down duplicates the current line below — useful for creating similar code structures quickly.' }
  ]
},

'5-11': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BROWSER', title: 'Workshop A — Split Editor and File Comparison Drill', content: 'This 8-minute drill builds fluency with VS Code\'s multi-file view.\n\n**Step 1 — Open two related files** (or create two text files with different content).\n\n**Step 2 — Split the editor:** Ctrl+\\ (backslash) splits the current file to the right. Now you see the same file in two panes.\n\n**Step 3 — Move a file to the other pane:** Drag a tab from one pane to the other.\n\n**Step 4 — Compare two files:** Ctrl+Shift+P → "Compare Active File with..." → select the second file. VS Code shows a diff view with changes highlighted.\n\n**Step 5 — Work in both panes:** Write code in one pane while referencing another file in the other. This is the real workflow: reference documentation on the left, write code on the right.\n\n**Step 6 — Ask Claude:** *"I often need to look at documentation or example code while writing my own. What VS Code layout and workflow would you recommend for this pattern?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Reference-While-Building Workflow', content: 'Build a real piece of code while referencing an example or documentation in a split view — the most common advanced VS Code workflow.\n\n**Step 1 — Identify a real task:** Something you\'re building where you\'ll reference example code, a tutorial, or a documentation file.\n\n**Step 2 — Set up your split view:**\n- Left pane: open the reference file (example code, docs, notes)\n- Right pane: open a new file where you\'ll write your code\n\n**Step 3 — Ask Claude to help you start:**\n```\nI want to build [describe what you\'re building]. I have these examples/docs as reference: [describe what\'s in your left pane]. \n\nGive me a skeleton structure for my implementation that I can fill in, looking at the reference as I go.\n```\n\n**Step 4 — Work with the split view:** Reference the left pane to understand patterns, write your implementation in the right pane.\n\n**Step 5 — Mandatory review:** Once your implementation is complete, ask Claude: *"Compare my implementation to the reference code. Find 3 differences where I diverged from the pattern — are these intentional improvements or mistakes?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — Tab Groups and Layouts', content: 'VS Code supports complex multi-pane layouts that match your workflow.\n\n**Step 1 — Create a 3-pane layout:**\n- Main file: your code (centre)\n- Left: file explorer\n- Bottom: integrated terminal\n\n**Step 2 — Move the panel to the right:** Ctrl+Shift+P → "View: Move Panel Right". Now terminal is on the right instead of bottom.\n\n**Step 3 — Create Tab Groups:** Right-click a tab → "New Tab Group to the Right". You can have independent tab groups with different files open.\n\n**Step 4 — Use Ctrl+1, Ctrl+2** to switch focus between editor panes without the mouse.\n\n**Step 5 — Try the Zen Mode:** Ctrl+Shift+P → "View: Toggle Zen Mode". Full screen, no distractions. Useful for reading and understanding complex code.\n\n**Step 6 — Find your preferred layout** for your most common task and write it down. Recreate it at the start of each work session.' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — Build a VS Code Workflow for AI Code Review', content: 'Set up a specific VS Code layout optimised for reviewing AI-generated code.\n\n**Step 1 — The AI code review layout:**\n- Left pane: the AI-generated code file\n- Right pane: a review notes file (create review.md)\n- Bottom: terminal for running/testing the code\n\n**Step 2 — Create review.md** as a template:\n```markdown\n# Code Review Notes\n\n## Correctness Issues\n- [ ] \n\n## Security Concerns  \n- [ ] \n\n## Performance Problems\n- [ ] \n\n## Missing Error Handling\n- [ ] \n\n## Questions for AI\n- [ ] \n```\n\n**Step 3 — Read the AI-generated code** line by line in the left pane. Write notes in the right pane.\n\n**Step 4 — Run the code** in the bottom terminal and note any runtime errors.\n\n**Step 5 — Ask Claude to review it too:** Paste the code and your notes and ask: *"Here is AI-generated code [paste] and my initial review notes [paste]. What did I miss? What are the 3 most important issues I should address first?"*' },

    { type: 'quiz', question: 'You have 15 files open as tabs in VS Code and it\'s getting hard to navigate. What are two good strategies?', options: ['Close VS Code and reopen with fewer files', 'Use Ctrl+P to jump to files by name, and organise related files into tab groups', 'Open a new VS Code window for each group of files', 'Switch to a simpler editor with fewer features'], correct: 1, explanation: 'Two effective strategies: Ctrl+P (Go to File) lets you jump to any file by typing its name — faster than scanning many tabs. Tab groups let you organise related files (e.g., frontend files in one group, backend files in another) so each group shows a manageable number of tabs. VS Code also has "pinned tabs" to keep frequently used files accessible and "preview mode" (single-click opens a temporary preview tab).' },

    { type: 'quiz', question: 'You want to compare yesterday\'s version of a file to today\'s to see what changed. What VS Code feature does this?', options: ['File → History (not a real VS Code feature)', 'Use git: `git diff` in the terminal or VS Code\'s Source Control panel to see changes between commits', 'Extensions → Install a diff tool', 'The VS Code Timeline (View → Open View → Timeline) shows file history and git diff for each entry'], correct: 3, explanation: 'VS Code\'s Timeline view shows the history of a file, including git commits. Click any commit to see a diff of what changed. The Source Control panel (Ctrl+Shift+G) also shows all changed files with inline diffs. For comparing two specific commits, use `git diff commit1 commit2 filename` in the terminal or the GitLens extension for a richer GUI experience.' }
  ]
},

'5-12': {
  addMinutes: 35,
  sections: [
    { type: 'workshop', tag: 'BUILD', title: 'Workshop A — VS Code Git Workflow Drill', content: 'This 8-minute drill gets you comfortable with VS Code\'s Source Control panel as your primary git interface.\n\n**Step 1 — Open a git repository** in VS Code (or initialise one: Ctrl+Shift+P → "Git: Initialize Repository").\n\n**Step 2 — Make a change** to any file — add a line, modify something.\n\n**Step 3 — Open Source Control** (Ctrl+Shift+G). Notice the changed file appears under "Changes".\n\n**Step 4 — Stage the change:** Click the + icon next to the file. It moves to "Staged Changes".\n\n**Step 5 — Write a commit message** in the message box at the top. Click the checkmark to commit.\n\n**Step 6 — View the git history:** Click the "..." menu → "View Git History" (or install GitLens for a richer history view).\n\n**Step 7 — Ask Claude:** *"I\'m learning to use VS Code\'s Source Control panel. What are the git operations I should know how to do from the VS Code GUI vs when should I use the terminal instead?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop B — Branch Workflow for a Real Feature', content: 'Practice the standard git branch workflow for a real feature you\'re building.\n\n**Step 1 — Create a new branch** for a feature you\'re working on:\n- Ctrl+Shift+P → "Git: Create Branch"\n- Name it: `feature/[what you\'re building]`\n\n**Step 2 — Make changes on the branch:** Build something small on this branch — add a file, write some code.\n\n**Step 3 — Commit the changes** to the feature branch (Source Control panel → stage → commit).\n\n**Step 4 — Switch back to main:** Click the branch name (bottom-left status bar) → select main.\n\n**Step 5 — Merge your feature:** Ctrl+Shift+P → "Git: Merge Branch" → select your feature branch.\n\n**Step 6 — Resolve conflicts** (if any): VS Code shows conflicts with merge markers. Choose "Accept Current Change", "Accept Incoming Change", or "Accept Both".\n\n**Step 7 — Ask Claude:** *"Explain the git branch workflow I just practiced. Why do developers use feature branches instead of committing directly to main?"*' },

    { type: 'workshop', tag: 'BROWSER', title: 'Workshop C — GitLens Power Features', content: 'GitLens is the most popular VS Code extension for git. This workshop explores its best features.\n\n**Step 1 — Install GitLens** (Ctrl+Shift+X → search "GitLens").\n\n**Step 2 — Explore Git Blame:** Open a code file. GitLens shows who last changed each line and when (inline, faded). Hover over any line to see the full commit details.\n\n**Step 3 — Explore Git History:** Right-click a file in Explorer → "Open Changes with Previous Revision". See exactly what changed.\n\n**Step 4 — Use the Repository View:** Ctrl+Shift+P → "GitLens: Show Repository" — see all branches, commits, stashes.\n\n**Step 5 — Use Interactive Rebase** (GitLens makes this visual): Ctrl+Shift+P → "GitLens: Git Interactive Rebase" — reorder or squash commits.\n\n**Step 6 — Ask Claude:** *"I installed GitLens. What are the 5 most useful features for someone who uses AI to generate code and wants to track what changed, when, and why?"*' },

    { type: 'workshop', tag: 'BUILD', title: 'Workshop D — AI-Assisted Git Commit Messages', content: 'Commit messages matter — they\'re documentation of why code changed. Use AI to write better ones.\n\n**Step 1 — Open Source Control** (Ctrl+Shift+G).\n\n**Step 2 — Stage your changes.** Look at the diff panel to see exactly what changed.\n\n**Step 3 — Ask Claude to write the commit message:**\n```\nI made the following code changes:\n[describe or paste the diff]\n\nWrite a commit message following these conventions:\n- First line: imperative mood, max 72 characters (e.g., "Add validation for empty input")\n- Optional body: what changed and WHY (not just what)\n- Reference any issue numbers if applicable\n\nProvide 3 options from most to least descriptive.\n```\n\n**Step 4 — Choose the best message** and paste it into VS Code\'s commit message box.\n\n**Step 5 — Mandatory habit:** Before every commit, spend 30 seconds making the commit message answer "why" not just "what". A git log full of "fix bug" messages is useless; "Fix validation that rejected valid email addresses with plus signs" is documentation.' },

    { type: 'quiz', question: 'You make changes to a file but accidentally make it much worse. You want to undo all changes and return the file to the last committed state. What is the safest approach in VS Code?', options: ['Ctrl+Z repeatedly until the changes are gone', 'Right-click the file in Source Control → "Discard Changes" — this reverts the file to its last committed state', 'Delete the file and restore it from git', 'Close VS Code without saving'], correct: 1, explanation: 'In VS Code\'s Source Control panel, right-clicking a changed file shows "Discard Changes" — this reverts the file to exactly what it looked like at the last commit. Ctrl+Z only undoes edits within the current session and may not go back far enough. Closing without saving works if you haven\'t saved, but if you have saved the bad version, Discard Changes (or `git checkout -- filename` in the terminal) is the correct approach.' },

    { type: 'quiz', question: 'You have two commits you want to combine into one before pushing to the team repository. What git operation does this?', options: ['git merge', 'git rebase -i (interactive rebase) — squash combines multiple commits into one', 'git reset --hard', 'git stash'], correct: 1, explanation: 'Interactive rebase (`git rebase -i HEAD~2` to work on the last 2 commits) lets you squash commits, reorder them, or rewrite messages. Squashing combines multiple commits into one, keeping a clean history. Important: only squash commits that haven\'t been pushed to a shared remote — rewriting shared history causes problems for others. GitLens in VS Code provides a visual interface for interactive rebase if you prefer not to use the command line.' }
  ]
}

};

function enhance(id, filePath) {
  const raw = fs.readFileSync(filePath, 'utf8');
  const lesson = JSON.parse(raw);
  const enh = enhancements[id];
  if (!enh) { console.log('SKIP '+id); return; }
  let successIdx = -1;
  for (let i = lesson.sections.length - 1; i >= 0; i--) {
    if (lesson.sections[i].type === 'callout' && lesson.sections[i].variant === 'success') {
      successIdx = i; break;
    }
  }
  const insertAt = successIdx >= 0 ? successIdx : lesson.sections.length;
  lesson.sections.splice(insertAt, 0, ...enh.sections);
  lesson.estimatedMinutes += enh.addMinutes;
  fs.writeFileSync(filePath, JSON.stringify(lesson, null, 2));
  const ws = lesson.sections.filter(s=>s.type==='workshop').length;
  const qz = lesson.sections.filter(s=>s.type==='quiz').length;
  console.log('OK '+id+' | ws:'+ws+' qz:'+qz+' mins:'+lesson.estimatedMinutes);
}

const lessons = [
  ['5-1','data/lessons/part-05/5-1.json'],
  ['5-2','data/lessons/part-05/5-2.json'],
  ['5-3','data/lessons/part-05/5-3.json'],
  ['5-4','data/lessons/part-05/5-4.json'],
  ['5-5','data/lessons/part-05/5-5.json'],
  ['5-6','data/lessons/part-05/5-6.json'],
  ['5-7','data/lessons/part-05/5-7.json'],
  ['5-8','data/lessons/part-05/5-8.json'],
  ['5-9','data/lessons/part-05/5-9.json'],
  ['5-10','data/lessons/part-05/5-10.json'],
  ['5-11','data/lessons/part-05/5-11.json'],
  ['5-12','data/lessons/part-05/5-12.json'],
];

lessons.forEach(([id, rel]) => {
  try { enhance(id, 'C:/Projects/Learning/'+rel); }
  catch(e) { console.log('FAIL '+id+': '+e.message); }
});
